### ISSUE TITLE
'rustc' panicked at 'Box<dyn Any>'. Error when making advent of code scripts

### ISSUE THREAD

**Issue by Bryson14** [rust-lang/rust-clippy#10052]
Rust Version : rustc 1.65.0 (897e37553 2022-11-02)
Clippy version: clippy 0.1.65 (897e3755 2022-11-02)
[Github Tag](https://github.com/Bryson14/RustLangFun/releases/tag/Clippy_Error)
```
error: internal compiler error: src\tools\clippy\clippy_utils\src\consts.rs:134:22: Not an int type
thread 'rustc' panicked at 'Box<dyn Any>', /rustc/897e37553bba8b42751c67658967889d11ecd120\compiler\rustc_errors\src\lib.rs:1462:9
note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust-clippy/issues/new

note: Clippy version: clippy 0.1.65 (897e3755 2022-11-02)

query stack during panic:
#0 [analysis] running analysis passes on this crate
end of query stack
```
When running `cargo clippy` in directory `RustLangFun\advent_of_code_2022>`, the error was thrown.

**Comment by xFrednet** [comment]
Hey, thank you for the raport! Could you try to provide the entire Stacktrace for the error? :)

**Comment by Guillermogsjc** [comment]
hi, hitting the same too from yesterday, the trace:

```rust
error: internal compiler error: src/tools/clippy/clippy_utils/src/consts.rs:134:22: Not an int type

thread 'rustc' panicked at 'Box<dyn Any>', /rustc/897e37553bba8b42751c67658967889d11ecd120/compiler/rustc_errors/src/lib.rs:1462:9
stack backtrace:
   0: std::panicking::begin_panic::<rustc_errors::ExplicitBug>
   1: std::panic::panic_any::<rustc_errors::ExplicitBug>
   2: <rustc_errors::HandlerInner>::bug::<&alloc::string::String>
   3: <rustc_errors::Handler>::bug::<&alloc::string::String>
   4: rustc_middle::ty::context::tls::with_context_opt::<rustc_middle::ty::context::tls::with_opt<rustc_middle::util::bug::opt_span_bug_fmt<rustc_span::span_encoding::Span>::{closure#0}, ()>::{closure#0}, ()>
   5: rustc_middle::util::bug::opt_span_bug_fmt::<rustc_span::span_encoding::Span>
   6: rustc_middle::util::bug::bug_fmt
   7: <clippy_utils::consts::Constant>::partial_cmp
   8: clippy_lints::ranges::check_possible_range_contains
   9: <clippy_lints::ranges::Ranges as rustc_lint::passes::LateLintPass>::check_expr
  10: <rustc_lint::early::EarlyLintPassObjects as rustc_lint::passes::EarlyLintPass>::check_generic_arg
  11: <rustc_lint::late::LateContextAndPass<rustc_lint::late::LateLintPassObjects> as rustc_hir::intravisit::Visitor>::visit_expr
  12: rustc_hir::intravisit::walk_local::<rustc_lint::late::LateContextAndPass<rustc_lint::late::LateLintPassObjects>>
  13: <rustc_lint::late::LateContextAndPass<rustc_lint::late::LateLintPassObjects> as rustc_hir::intravisit::Visitor>::visit_local
  14: rustc_hir::intravisit::walk_block::<rustc_lint::late::LateContextAndPass<rustc_lint::late::LateLintPassObjects>>
  15: <rustc_lint::late::LateContextAndPass<rustc_lint::late::LateLintPassObjects> as rustc_hir::intravisit::Visitor>::visit_block
  16: <rustc_lint::late::LateContextAndPass<rustc_lint::late::LateLintPassObjects> as rustc_hir::intravisit::Visitor>::visit_expr
  17: <rustc_lint::late::LateContextAndPass<rustc_lint::late::LateLintPassObjects> as rustc_hir::intravisit::Visitor>::visit_nested_body
  18: <rustc_lint::late::LateContextAndPass<rustc_lint::late::LateLintPassObjects> as rustc_hir::intravisit::Visitor>::visit_fn
  19: rustc_hir::intravisit::walk_item::<rustc_lint::late::LateContextAndPass<rustc_lint::late::LateLintPassObjects>>
  20: <rustc_lint::late::LateContextAndPass<rustc_lint::late::LateLintPassObjects> as rustc_hir::intravisit::Visitor>::visit_nested_item
  21: rustc_hir::intravisit::walk_mod::<rustc_lint::late::LateContextAndPass<rustc_lint::late::LateLintPassObjects>>
  22: <rustc_lint::late::LateContextAndPass<rustc_lint::late::LateLintPassObjects> as rustc_hir::intravisit::Visitor>::visit_nested_item
  23: rustc_hir::intravisit::walk_mod::<rustc_lint::late::LateContextAndPass<rustc_lint::late::LateLintPassObjects>>
  24: <rustc_lint::late::LateContextAndPass<rustc_lint::late::LateLintPassObjects> as rustc_hir::intravisit::Visitor>::visit_nested_item
  25: rustc_hir::intravisit::walk_mod::<rustc_lint::late::LateContextAndPass<rustc_lint::late::LateLintPassObjects>>
  26: rustc_lint::late::late_lint_pass_crate::<rustc_lint::late::LateLintPassObjects>
  27: rustc_lint::late::late_lint_crate::<rustc_lint::BuiltinCombinedLateLintPass>
  28: <rustc_session::session::Session>::time::<(), rustc_lint::late::check_crate<rustc_lint::BuiltinCombinedLateLintPass, rustc_interface::passes::analysis::{closure#5}::{closure#1}::{closure#2}::{closure#0}::{closure#0}>::{closure#0}::{closure#0}>
  29: <rustc_session::session::Session>::time::<(), rustc_interface::passes::analysis::{closure#5}::{closure#1}::{closure#2}::{closure#0}>
  30: <core::panic::unwind_safe::AssertUnwindSafe<rustc_interface::passes::analysis::{closure#5}::{closure#1}> as core::ops::function::FnOnce<()>>::call_once
  31: <rustc_session::session::Session>::time::<(), rustc_interface::passes::analysis::{closure#5}>
  32: rustc_interface::passes::analysis
  33: <rustc_query_system::dep_graph::graph::DepGraph<rustc_middle::dep_graph::dep_node::DepKind>>::with_task::<rustc_middle::ty::context::TyCtxt, (), core::result::Result<(), rustc_errors::ErrorGuaranteed>>
  34: rustc_query_system::query::plumbing::try_execute_query::<rustc_query_impl::plumbing::QueryCtxt, rustc_query_system::query::caches::DefaultCache<(), core::result::Result<(), rustc_errors::ErrorGuaranteed>>>
  35: rustc_query_system::query::plumbing::get_query::<rustc_query_impl::queries::analysis, rustc_query_impl::plumbing::QueryCtxt>
  36: <rustc_interface::passes::QueryContext>::enter::<rustc_driver::run_compiler::{closure#1}::{closure#2}::{closure#3}, core::result::Result<(), rustc_errors::ErrorGuaranteed>>
  37: rustc_interface::interface::create_compiler_and_run::<core::result::Result<(), rustc_errors::ErrorGuaranteed>, rustc_driver::run_compiler::{closure#1}>
  38: <scoped_tls::ScopedKey<rustc_span::SessionGlobals>>::set::<rustc_interface::interface::run_compiler<core::result::Result<(), rustc_errors::ErrorGuaranteed>, rustc_driver::run_compiler::{closure#1}>::{closure#0}, core::result::Result<(), rustc_errors::ErrorGuaranteed>>
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust-clippy/issues/new

note: Clippy version: clippy 0.1.65 (897e375 2022-11-02)

````

**Comment by Bryson14** [comment]
> Hey, thank you for the raport! Could you try to provide the entire Stacktrace for the error? :)

When I run `cargo clippy` that is all the output there is. Is there a way to show clippy --verbose?

**Comment by TheKysek** [comment]
Same here. Backtrace with `RUST_BACKTRACE=full`:

```
    Checking aoc-2022 v0.1.0 (/workspace/aoc-2022)
error: internal compiler error: src/tools/clippy/clippy_utils/src/consts.rs:134:22: Not an int type

thread 'rustc' panicked at 'Box<dyn Any>', /rustc/897e37553bba8b42751c67658967889d11ecd120/compiler/rustc_errors/src/lib.rs:1462:9
stack backtrace:
   0:     0x7fb4a559dd40 - std::backtrace_rs::backtrace::libunwind::trace::h32eb3e08e874dd27
                               at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
   1:     0x7fb4a559dd40 - std::backtrace_rs::backtrace::trace_unsynchronized::haa3f451d27bc11a5
                               at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x7fb4a559dd40 - std::sys_common::backtrace::_print_fmt::h5b94a01bb4289bb5
                               at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/std/src/sys_common/backtrace.rs:66:5
   3:     0x7fb4a559dd40 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::hb070b7fa7e3175df
                               at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/std/src/sys_common/backtrace.rs:45:22
   4:     0x7fb4a55f8bfe - core::fmt::write::hd5207aebbb9a86e9
                               at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/core/src/fmt/mod.rs:1202:17
   5:     0x7fb4a558e935 - std::io::Write::write_fmt::h3bd699bbd129ab8a
                               at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/std/src/io/mod.rs:1679:15
   6:     0x7fb4a55a09f3 - std::sys_common::backtrace::_print::h7a21be552fdf58da
                               at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/std/src/sys_common/backtrace.rs:48:5
   7:     0x7fb4a55a09f3 - std::sys_common::backtrace::print::ha85c41fe4dd80b13
                               at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/std/src/sys_common/backtrace.rs:35:9
   8:     0x7fb4a55a09f3 - std::panicking::default_hook::{{closure}}::h04cca40023d0eeca
                               at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/std/src/panicking.rs:295:22
   9:     0x7fb4a55a06df - std::panicking::default_hook::haa3ca8c310ed5402
                               at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/std/src/panicking.rs:314:9
  10:     0x556be83628af - clippy_driver[8edfe2ebdb33510b]::ICE_HOOK::{closure#0}::{closure#0}
  11:     0x7fb4a55a122d - std::panicking::rust_panic_with_hook::h7b190ce1a948faac
                               at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/std/src/panicking.rs:702:17
  12:     0x7fb4a8d54e51 - std[71cb4861428b0c25]::panicking::begin_panic::<rustc_errors[f77a66b68db622d5]::ExplicitBug>::{closure#0}
  13:     0x7fb4a8d52966 - std[71cb4861428b0c25]::sys_common::backtrace::__rust_end_short_backtrace::<std[71cb4861428b0c25]::panicking::begin_panic<rustc_errors[f77a66b68db622d5]::ExplicitBug>::{closure#0}, !>
  14:     0x7fb4a8dac316 - std[71cb4861428b0c25]::panicking::begin_panic::<rustc_errors[f77a66b68db622d5]::ExplicitBug>
  15:     0x7fb4a8d4f5f6 - std[71cb4861428b0c25]::panic::panic_any::<rustc_errors[f77a66b68db622d5]::ExplicitBug>
  16:     0x7fb4a8d4e1dd - <rustc_errors[f77a66b68db622d5]::HandlerInner>::bug::<&alloc[188ed69dc0d14b4b]::string::String>
  17:     0x7fb4a8d4dc10 - <rustc_errors[f77a66b68db622d5]::Handler>::bug::<&alloc[188ed69dc0d14b4b]::string::String>
  18:     0x7fb4a8e0a7ed - rustc_middle[a9ca1c3f9fd197cd]::ty::context::tls::with_context_opt::<rustc_middle[a9ca1c3f9fd197cd]::ty::context::tls::with_opt<rustc_middle[a9ca1c3f9fd197cd]::util::bug::opt_span_bug_fmt<rustc_span[8f00505efff112e2]::span_encoding::Span>::{closure#0}, ()>::{closure#0}, ()>
  19:     0x7fb4a8e0dc86 - rustc_middle[a9ca1c3f9fd197cd]::util::bug::opt_span_bug_fmt::<rustc_span[8f00505efff112e2]::span_encoding::Span>
  20:     0x7fb4a67aba83 - rustc_middle[a9ca1c3f9fd197cd]::util::bug::bug_fmt
  21:     0x556be87925b1 - <clippy_utils[6f190657543f79d8]::consts::Constant>::partial_cmp
  22:     0x556be866c851 - clippy_lints[641d7bf63abf0cc3]::ranges::check_possible_range_contains
  23:     0x556be866c116 - <clippy_lints[641d7bf63abf0cc3]::ranges::Ranges as rustc_lint[dab68e85e8b6d341]::passes::LateLintPass>::check_expr
  24:     0x7fb4a8b98954 - <rustc_lint[dab68e85e8b6d341]::early::EarlyLintPassObjects as rustc_lint[dab68e85e8b6d341]::passes::EarlyLintPass>::check_generic_arg
  25:     0x7fb4a7e92643 - <rustc_lint[dab68e85e8b6d341]::late::LateContextAndPass<rustc_lint[dab68e85e8b6d341]::late::LateLintPassObjects> as rustc_hir[f29014e7b3f8eb6c]::intravisit::Visitor>::visit_expr
  26:     0x7fb4a7e9264e - <rustc_lint[dab68e85e8b6d341]::late::LateContextAndPass<rustc_lint[dab68e85e8b6d341]::late::LateLintPassObjects> as rustc_hir[f29014e7b3f8eb6c]::intravisit::Visitor>::visit_expr
  27:     0x7fb4a7e953aa - rustc_hir[f29014e7b3f8eb6c]::intravisit::walk_expr::<rustc_lint[dab68e85e8b6d341]::late::LateContextAndPass<rustc_lint[dab68e85e8b6d341]::late::LateLintPassObjects>>
  28:     0x7fb4a7e9264e - <rustc_lint[dab68e85e8b6d341]::late::LateContextAndPass<rustc_lint[dab68e85e8b6d341]::late::LateLintPassObjects> as rustc_hir[f29014e7b3f8eb6c]::intravisit::Visitor>::visit_expr
  29:     0x7fb4a7e93f8a - rustc_hir[f29014e7b3f8eb6c]::intravisit::walk_block::<rustc_lint[dab68e85e8b6d341]::late::LateContextAndPass<rustc_lint[dab68e85e8b6d341]::late::LateLintPassObjects>>
  30:     0x7fb4a7e92799 - <rustc_lint[dab68e85e8b6d341]::late::LateContextAndPass<rustc_lint[dab68e85e8b6d341]::late::LateLintPassObjects> as rustc_hir[f29014e7b3f8eb6c]::intravisit::Visitor>::visit_block
  31:     0x7fb4a7e9264e - <rustc_lint[dab68e85e8b6d341]::late::LateContextAndPass<rustc_lint[dab68e85e8b6d341]::late::LateLintPassObjects> as rustc_hir[f29014e7b3f8eb6c]::intravisit::Visitor>::visit_expr
  32:     0x7fb4a7e95402 - rustc_hir[f29014e7b3f8eb6c]::intravisit::walk_expr::<rustc_lint[dab68e85e8b6d341]::late::LateContextAndPass<rustc_lint[dab68e85e8b6d341]::late::LateLintPassObjects>>
  33:     0x7fb4a7e9264e - <rustc_lint[dab68e85e8b6d341]::late::LateContextAndPass<rustc_lint[dab68e85e8b6d341]::late::LateLintPassObjects> as rustc_hir[f29014e7b3f8eb6c]::intravisit::Visitor>::visit_expr
  34:     0x7fb4a7e93f8a - rustc_hir[f29014e7b3f8eb6c]::intravisit::walk_block::<rustc_lint[dab68e85e8b6d341]::late::LateContextAndPass<rustc_lint[dab68e85e8b6d341]::late::LateLintPassObjects>>
  35:     0x7fb4a7e92799 - <rustc_lint[dab68e85e8b6d341]::late::LateContextAndPass<rustc_lint[dab68e85e8b6d341]::late::LateLintPassObjects> as rustc_hir[f29014e7b3f8eb6c]::intravisit::Visitor>::visit_block
  36:     0x7fb4a7e9264e - <rustc_lint[dab68e85e8b6d341]::late::LateContextAndPass<rustc_lint[dab68e85e8b6d341]::late::LateLintPassObjects> as rustc_hir[f29014e7b3f8eb6c]::intravisit::Visitor>::visit_expr
  37:     0x7fb4a7e95402 - rustc_hir[f29014e7b3f8eb6c]::intravisit::walk_expr::<rustc_lint[dab68e85e8b6d341]::late::LateContextAndPass<rustc_lint[dab68e85e8b6d341]::late::LateLintPassObjects>>
  38:     0x7fb4a7e9264e - <rustc_lint[dab68e85e8b6d341]::late::LateContextAndPass<rustc_lint[dab68e85e8b6d341]::late::LateLintPassObjects> as rustc_hir[f29014e7b3f8eb6c]::intravisit::Visitor>::visit_expr
  39:     0x7fb4a7e9264e - <rustc_lint[dab68e85e8b6d341]::late::LateContextAndPass<rustc_lint[dab68e85e8b6d341]::late::LateLintPassObjects> as rustc_hir[f29014e7b3f8eb6c]::intravisit::Visitor>::visit_expr
  40:     0x7fb4a7e93f8a - rustc_hir[f29014e7b3f8eb6c]::intravisit::walk_block::<rustc_lint[dab68e85e8b6d341]::late::LateContextAndPass<rustc_lint[dab68e85e8b6d341]::late::LateLintPassObjects>>
  41:     0x7fb4a7e92799 - <rustc_lint[dab68e85e8b6d341]::late::LateContextAndPass<rustc_lint[dab68e85e8b6d341]::late::LateLintPassObjects> as rustc_hir[f29014e7b3f8eb6c]::intravisit::Visitor>::visit_block
  42:     0x7fb4a7e9264e - <rustc_lint[dab68e85e8b6d341]::late::LateContextAndPass<rustc_lint[dab68e85e8b6d341]::late::LateLintPassObjects> as rustc_hir[f29014e7b3f8eb6c]::intravisit::Visitor>::visit_expr
  43:     0x7fb4a7e92799 - <rustc_lint[dab68e85e8b6d341]::late::LateContextAndPass<rustc_lint[dab68e85e8b6d341]::late::LateLintPassObjects> as rustc_hir[f29014e7b3f8eb6c]::intravisit::Visitor>::visit_block
  44:     0x7fb4a7e9264e - <rustc_lint[dab68e85e8b6d341]::late::LateContextAndPass<rustc_lint[dab68e85e8b6d341]::late::LateLintPassObjects> as rustc_hir[f29014e7b3f8eb6c]::intravisit::Visitor>::visit_expr
  45:     0x7fb4a7e93f8a - rustc_hir[f29014e7b3f8eb6c]::intravisit::walk_block::<rustc_lint[dab68e85e8b6d341]::late::LateContextAndPass<rustc_lint[dab68e85e8b6d341]::late::LateLintPassObjects>>
  46:     0x7fb4a7e92799 - <rustc_lint[dab68e85e8b6d341]::late::LateContextAndPass<rustc_lint[dab68e85e8b6d341]::late::LateLintPassObjects> as rustc_hir[f29014e7b3f8eb6c]::intravisit::Visitor>::visit_block
  47:     0x7fb4a7e9264e - <rustc_lint[dab68e85e8b6d341]::late::LateContextAndPass<rustc_lint[dab68e85e8b6d341]::late::LateLintPassObjects> as rustc_hir[f29014e7b3f8eb6c]::intravisit::Visitor>::visit_expr
  48:     0x7fb4a7e92adc - <rustc_lint[dab68e85e8b6d341]::late::LateContextAndPass<rustc_lint[dab68e85e8b6d341]::late::LateLintPassObjects> as rustc_hir[f29014e7b3f8eb6c]::intravisit::Visitor>::visit_nested_body
  49:     0x7fb4a7e92cd9 - <rustc_lint[dab68e85e8b6d341]::late::LateContextAndPass<rustc_lint[dab68e85e8b6d341]::late::LateLintPassObjects> as rustc_hir[f29014e7b3f8eb6c]::intravisit::Visitor>::visit_fn
  50:     0x7fb4a7e9562d - rustc_hir[f29014e7b3f8eb6c]::intravisit::walk_item::<rustc_lint[dab68e85e8b6d341]::late::LateContextAndPass<rustc_lint[dab68e85e8b6d341]::late::LateLintPassObjects>>
  51:     0x7fb4a7e935de - <rustc_lint[dab68e85e8b6d341]::late::LateContextAndPass<rustc_lint[dab68e85e8b6d341]::late::LateLintPassObjects> as rustc_hir[f29014e7b3f8eb6c]::intravisit::Visitor>::visit_nested_item
  52:     0x7fb4a7e94f27 - rustc_hir[f29014e7b3f8eb6c]::intravisit::walk_mod::<rustc_lint[dab68e85e8b6d341]::late::LateContextAndPass<rustc_lint[dab68e85e8b6d341]::late::LateLintPassObjects>>
  53:     0x7fb4a7e935de - <rustc_lint[dab68e85e8b6d341]::late::LateContextAndPass<rustc_lint[dab68e85e8b6d341]::late::LateLintPassObjects> as rustc_hir[f29014e7b3f8eb6c]::intravisit::Visitor>::visit_nested_item
  54:     0x7fb4a7e94f27 - rustc_hir[f29014e7b3f8eb6c]::intravisit::walk_mod::<rustc_lint[dab68e85e8b6d341]::late::LateContextAndPass<rustc_lint[dab68e85e8b6d341]::late::LateLintPassObjects>>
  55:     0x7fb4a7e92563 - rustc_lint[dab68e85e8b6d341]::late::late_lint_pass_crate::<rustc_lint[dab68e85e8b6d341]::late::LateLintPassObjects>
  56:     0x7fb4a7147511 - rustc_lint[dab68e85e8b6d341]::late::late_lint_crate::<rustc_lint[dab68e85e8b6d341]::BuiltinCombinedLateLintPass>
  57:     0x7fb4a7145ad6 - <rustc_session[c5946fac61f8bc34]::session::Session>::time::<(), rustc_lint[dab68e85e8b6d341]::late::check_crate<rustc_lint[dab68e85e8b6d341]::BuiltinCombinedLateLintPass, rustc_interface[3182dd864eff9d7d]::passes::analysis::{closure#5}::{closure#1}::{closure#2}::{closure#0}::{closure#0}>::{closure#0}::{closure#0}>
  58:     0x7fb4a71459d9 - <rustc_session[c5946fac61f8bc34]::session::Session>::time::<(), rustc_interface[3182dd864eff9d7d]::passes::analysis::{closure#5}::{closure#1}::{closure#2}::{closure#0}>
  59:     0x7fb4a71457cf - <core[8c92e53db3fc2eaa]::panic::unwind_safe::AssertUnwindSafe<rustc_interface[3182dd864eff9d7d]::passes::analysis::{closure#5}::{closure#1}> as core[8c92e53db3fc2eaa]::ops::function::FnOnce<()>>::call_once
  60:     0x7fb4a7144d9a - <rustc_session[c5946fac61f8bc34]::session::Session>::time::<(), rustc_interface[3182dd864eff9d7d]::passes::analysis::{closure#5}>
  61:     0x7fb4a7140cbc - rustc_interface[3182dd864eff9d7d]::passes::analysis
  62:     0x7fb4a7b9f382 - <rustc_query_system[860ed7b39cdfb46b]::dep_graph::graph::DepGraph<rustc_middle[a9ca1c3f9fd197cd]::dep_graph::dep_node::DepKind>>::with_task::<rustc_middle[a9ca1c3f9fd197cd]::ty::context::TyCtxt, (), core[8c92e53db3fc2eaa]::result::Result<(), rustc_errors[f77a66b68db622d5]::ErrorGuaranteed>>
  63:     0x7fb4a7b9ea4a - rustc_query_system[860ed7b39cdfb46b]::query::plumbing::try_execute_query::<rustc_query_impl[d6191eea714bd250]::plumbing::QueryCtxt, rustc_query_system[860ed7b39cdfb46b]::query::caches::DefaultCache<(), core[8c92e53db3fc2eaa]::result::Result<(), rustc_errors[f77a66b68db622d5]::ErrorGuaranteed>>>
  64:     0x7fb4a7b9e517 - rustc_query_system[860ed7b39cdfb46b]::query::plumbing::get_query::<rustc_query_impl[d6191eea714bd250]::queries::analysis, rustc_query_impl[d6191eea714bd250]::plumbing::QueryCtxt>
  65:     0x7fb4a6c8a897 - <rustc_interface[3182dd864eff9d7d]::passes::QueryContext>::enter::<rustc_driver[cfb34b1539811fe8]::run_compiler::{closure#1}::{closure#2}::{closure#3}, core[8c92e53db3fc2eaa]::result::Result<(), rustc_errors[f77a66b68db622d5]::ErrorGuaranteed>>
  66:     0x7fb4a6c7e28c - rustc_interface[3182dd864eff9d7d]::interface::create_compiler_and_run::<core[8c92e53db3fc2eaa]::result::Result<(), rustc_errors[f77a66b68db622d5]::ErrorGuaranteed>, rustc_driver[cfb34b1539811fe8]::run_compiler::{closure#1}>
  67:     0x7fb4a6c7cac1 - <scoped_tls[e395fa6e23b19669]::ScopedKey<rustc_span[8f00505efff112e2]::SessionGlobals>>::set::<rustc_interface[3182dd864eff9d7d]::interface::run_compiler<core[8c92e53db3fc2eaa]::result::Result<(), rustc_errors[f77a66b68db622d5]::ErrorGuaranteed>, rustc_driver[cfb34b1539811fe8]::run_compiler::{closure#1}>::{closure#0}, core[8c92e53db3fc2eaa]::result::Result<(), rustc_errors[f77a66b68db622d5]::ErrorGuaranteed>>
  68:     0x7fb4a6c7c7af - std[71cb4861428b0c25]::sys_common::backtrace::__rust_begin_short_backtrace::<rustc_interface[3182dd864eff9d7d]::util::run_in_thread_pool_with_globals<rustc_interface[3182dd864eff9d7d]::interface::run_compiler<core[8c92e53db3fc2eaa]::result::Result<(), rustc_errors[f77a66b68db622d5]::ErrorGuaranteed>, rustc_driver[cfb34b1539811fe8]::run_compiler::{closure#1}>::{closure#0}, core[8c92e53db3fc2eaa]::result::Result<(), rustc_errors[f77a66b68db622d5]::ErrorGuaranteed>>::{closure#0}, core[8c92e53db3fc2eaa]::result::Result<(), rustc_errors[f77a66b68db622d5]::ErrorGuaranteed>>
  69:     0x7fb4a7c31d70 - <<std[71cb4861428b0c25]::thread::Builder>::spawn_unchecked_<rustc_interface[3182dd864eff9d7d]::util::run_in_thread_pool_with_globals<rustc_interface[3182dd864eff9d7d]::interface::run_compiler<core[8c92e53db3fc2eaa]::result::Result<(), rustc_errors[f77a66b68db622d5]::ErrorGuaranteed>, rustc_driver[cfb34b1539811fe8]::run_compiler::{closure#1}>::{closure#0}, core[8c92e53db3fc2eaa]::result::Result<(), rustc_errors[f77a66b68db622d5]::ErrorGuaranteed>>::{closure#0}, core[8c92e53db3fc2eaa]::result::Result<(), rustc_errors[f77a66b68db622d5]::ErrorGuaranteed>>::{closure#1} as core[8c92e53db3fc2eaa]::ops::function::FnOnce<()>>::call_once::{shim:vtable#0}
  70:     0x7fb4a55ab003 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h49f797984e2121bf
                               at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/alloc/src/boxed.rs:1940:9
  71:     0x7fb4a55ab003 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::hfa4f3d0ee6440e0b
                               at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/alloc/src/boxed.rs:1940:9
  72:     0x7fb4a55ab003 - std::sys::unix::thread::Thread::new::thread_start::h62ca48b42d48a8fc
                               at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/std/src/sys/unix/thread.rs:108:17
  73:     0x7fb4a546f609 - start_thread
  74:     0x7fb4a5243133 - clone
  75:                0x0 - <unknown>

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust-clippy/issues/new

note: Clippy version: clippy 0.1.65 (897e375 2022-11-02)

query stack during panic:
#0 [analysis] running analysis passes on this crate
end of query stack
error: could not compile `aoc-2022`
```
