### ISSUE TITLE
ICE with Clippy in compiler/rustc_metadata/src/rmeta/decoder/cstore_impl.rs

### ISSUE THREAD

**Issue by mgree** [rust-lang/rust-clippy#10722]
I got the following error while compiling [expr-test-util](https://github.com/MaterializeInc/materialize/tree/main/src/expr-test-util).

```
thread 'rustc' panicked at 'DefId(45:434 ~ mz_ore[867d]::future::{impl#3}::T) does not have a "type_of"', compiler/rustc_metadata/src/rmeta/decoder/cstore_impl.rs:188:1
--
  | note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
  |  
  | error: internal compiler error: unexpected panic
  |  
  | note: the compiler unexpectedly panicked. this is a bug.
  |  
  | note: we would appreciate a bug report: https://github.com/rust-lang/rust-clippy/issues/new
  |  
  | note: Clippy version: clippy 0.1.68 (9eb3afe9 2023-03-27)
  |  
  | query stack during panic:
  | thread 'rustc' panicked at 'already borrowed: BorrowMutError', /rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/compiler/rustc_query_system/src/query/plumbing.rs:193:43
  | stack backtrace:
  | 0:        0x10c9b56e6 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h47bed05ceb7970ee
  | 1:        0x10ca12fca - core::fmt::write::hefd823d99333384a
  | 2:        0x10c9a7eac - std::io::Write::write_fmt::hb978956bb1b85e2b
  | 3:        0x10c9b54ca - std::sys_common::backtrace::print::hc9e298c4664da113
  | 4:        0x10c9b88c3 - std::panicking::default_hook::{{closure}}::hb97411d6e916e1d2
  | 5:        0x10c9b8618 - std::panicking::default_hook::hc3ac81176817192f
  | 6:        0x10bfabf85 - clippy_driver[eeaa0d7583535142]::ICE_HOOK::{closure#0}::{closure#0}
  | 7:        0x10c9b90b9 - std::panicking::rust_panic_with_hook::hc11209fa2686218a
  | 8:        0x10c9b8e54 - std::panicking::begin_panic_handler::{{closure}}::h5bad1bd665ab68a6
  | 9:        0x10c9b5b88 - std::sys_common::backtrace::__rust_end_short_backtrace::h6f4efa73918edf57
  | 10:        0x10c9b8b1d - _rust_begin_unwind
  | 11:        0x10ca3f5e3 - core::panicking::panic_fmt::hb5474ac70e328787
  | 12:        0x10ca3fa75 - core::result::unwrap_failed::h0d8a1201e19fe76f
  | 13:        0x110f1b8a1 - rustc_query_system[3d399bab0eaade7f]::query::plumbing::try_execute_query::<rustc_query_impl[469a71c953212c97]::queries::type_of, rustc_query_impl[469a71c953212c97]::plumbing::QueryCtxt>
  | 14:        0x1110392d2 - <rustc_query_impl[469a71c953212c97]::Queries as rustc_middle[7044477369b49eec]::ty::query::QueryEngine>::type_of
  | 15:        0x1106d1b38 - <rustc_middle[7044477369b49eec]::ty::context::TyCtxt>::bound_type_of
  | 16:        0x110756be9 - <rustc_middle[7044477369b49eec]::ty::print::pretty::FmtPrinter as rustc_middle[7044477369b49eec]::ty::print::Printer>::print_def_path
  | 17:        0x11075718d - <rustc_middle[7044477369b49eec]::ty::print::pretty::FmtPrinter as rustc_middle[7044477369b49eec]::ty::print::Printer>::print_def_path
  | 18:        0x11067fb0c - rustc_middle[7044477369b49eec]::query::descs::type_of
  | 19:        0x1111c4d76 - rustc_query_impl[469a71c953212c97]::plumbing::create_query_frame::<rustc_span[abe350e59e28df37]::def_id::DefId>
  | 20:        0x1111bccb9 - <rustc_query_impl[469a71c953212c97]::query_structs::type_of::{closure#0} as core[fd5e363bb4760a86]::ops::function::FnOnce<(rustc_query_impl[469a71c953212c97]::plumbing::QueryCtxt, &mut std[963c226d0575182f]::collections::hash::map::HashMap<rustc_query_system[3d399bab0eaade7f]::query::job::QueryJobId, rustc_query_system[3d399bab0eaade7f]::query::job::QueryJobInfo<rustc_middle[7044477369b49eec]::dep_graph::dep_node::DepKind>, core[fd5e363bb4760a86]::hash::BuildHasherDefault<rustc_hash[aebda07287555bf6]::FxHasher>>)>>::call_once
  | 21:        0x110f8a82d - rustc_query_system[3d399bab0eaade7f]::query::job::print_query_stack::<rustc_query_impl[469a71c953212c97]::plumbing::QueryCtxt>
  | 22:        0x1102dbd23 - rustc_interface[d2d1d1fbee7644ce]::interface::try_print_query_stack
  | 23:        0x10bfac4e9 - clippy_driver[eeaa0d7583535142]::ICE_HOOK::{closure#0}::{closure#0}
  | 24:        0x10c9b90b9 - std::panicking::rust_panic_with_hook::hc11209fa2686218a
  | 25:        0x10c9b8e54 - std::panicking::begin_panic_handler::{{closure}}::h5bad1bd665ab68a6
  | 26:        0x10c9b5b88 - std::sys_common::backtrace::__rust_end_short_backtrace::h6f4efa73918edf57
  | 27:        0x10c9b8b1d - _rust_begin_unwind
  | 28:        0x10ca3f5e3 - core::panicking::panic_fmt::hb5474ac70e328787
  | 29:        0x110595ef8 - rustc_metadata[85b4bacf0ed12305]::rmeta::decoder::cstore_impl::provide_extern::type_of::{closure#1}
  | 30:        0x110595dfe - rustc_metadata[85b4bacf0ed12305]::rmeta::decoder::cstore_impl::provide_extern::type_of
  | 31:        0x110f1b3ff - rustc_query_system[3d399bab0eaade7f]::query::plumbing::try_execute_query::<rustc_query_impl[469a71c953212c97]::queries::type_of, rustc_query_impl[469a71c953212c97]::plumbing::QueryCtxt>
  | 32:        0x1110392d2 - <rustc_query_impl[469a71c953212c97]::Queries as rustc_middle[7044477369b49eec]::ty::query::QueryEngine>::type_of
  | 33:        0x1106d1b38 - <rustc_middle[7044477369b49eec]::ty::context::TyCtxt>::bound_type_of
  | 34:        0x10ffb2c5c - <rustc_hir_typeck[6efceea4454c75c9]::fn_ctxt::FnCtxt>::instantiate_value_path
  | 35:        0x10ff40fb9 - <rustc_hir_typeck[6efceea4454c75c9]::fn_ctxt::FnCtxt>::check_expr_path
  | 36:        0x10ff405f6 - <rustc_hir_typeck[6efceea4454c75c9]::fn_ctxt::FnCtxt>::check_expr_with_expectation_and_args
  | 37:        0x10ff23edc - <rustc_hir_typeck[6efceea4454c75c9]::fn_ctxt::FnCtxt>::check_call
  | 38:        0x10ffa2bbf - <rustc_hir_typeck[6efceea4454c75c9]::fn_ctxt::FnCtxt>::check_expr_kind
  | 39:        0x10ff406b5 - <rustc_hir_typeck[6efceea4454c75c9]::fn_ctxt::FnCtxt>::check_expr_with_expectation_and_args
  | 40:        0x10ff9ca37 - <rustc_hir_typeck[6efceea4454c75c9]::fn_ctxt::FnCtxt>::check_match::{closure#0}
  | 41:        0x10ffa2b85 - <rustc_hir_typeck[6efceea4454c75c9]::fn_ctxt::FnCtxt>::check_expr_kind
  | 42:        0x10ff406b5 - <rustc_hir_typeck[6efceea4454c75c9]::fn_ctxt::FnCtxt>::check_expr_with_expectation_and_args
  | 43:        0x10ff5a52f - <rustc_hir_typeck[6efceea4454c75c9]::fn_ctxt::FnCtxt>::check_block_with_expected
  | 44:        0x10ffa2faf - <rustc_hir_typeck[6efceea4454c75c9]::fn_ctxt::FnCtxt>::check_expr_kind
  | 45:        0x10ff406b5 - <rustc_hir_typeck[6efceea4454c75c9]::fn_ctxt::FnCtxt>::check_expr_with_expectation_and_args
  | 46:        0x10ff420e0 - <rustc_hir_typeck[6efceea4454c75c9]::fn_ctxt::FnCtxt>::check_return_expr
  | 47:        0x11001dafc - rustc_hir_typeck[6efceea4454c75c9]::check::check_fn
  | 48:        0x110058670 - rustc_hir_typeck[6efceea4454c75c9]::typeck
  | 49:        0x110f18f99 - rustc_query_system[3d399bab0eaade7f]::query::plumbing::try_execute_query::<rustc_query_impl[469a71c953212c97]::queries::typeck, rustc_query_impl[469a71c953212c97]::plumbing::QueryCtxt>
  | 50:        0x11103db4e - <rustc_query_impl[469a71c953212c97]::Queries as rustc_middle[7044477369b49eec]::ty::query::QueryEngine>::typeck
  | 51:        0x10ffe3fab - rustc_data_structures[a3be787722aab228]::sync::par_for_each_in::<&[rustc_span[abe350e59e28df37]::def_id::LocalDefId], <rustc_middle[7044477369b49eec]::hir::map::Map>::par_body_owners<rustc_hir_typeck[6efceea4454c75c9]::typeck_item_bodies::{closure#0}>::{closure#0}>
  | 52:        0x1100560a4 - rustc_hir_typeck[6efceea4454c75c9]::typeck_item_bodies
  | 53:        0x110e7e749 - rustc_query_system[3d399bab0eaade7f]::query::plumbing::try_execute_query::<rustc_query_impl[469a71c953212c97]::queries::typeck_item_bodies, rustc_query_impl[469a71c953212c97]::plumbing::QueryCtxt>
  | 54:        0x11103da6f - <rustc_query_impl[469a71c953212c97]::Queries as rustc_middle[7044477369b49eec]::ty::query::QueryEngine>::typeck_item_bodies
  | 55:        0x10fdce0f7 - <rustc_session[d7fa5f284918d396]::session::Session>::time::<(), rustc_hir_analysis[27a8f7e0703a01ee]::check_crate::{closure#7}>
  | 56:        0x10fd6acb3 - rustc_hir_analysis[27a8f7e0703a01ee]::check_crate
  | 57:        0x1102c6079 - rustc_interface[d2d1d1fbee7644ce]::passes::analysis
  | 58:        0x110f1bfed - rustc_query_system[3d399bab0eaade7f]::query::plumbing::try_execute_query::<rustc_query_impl[469a71c953212c97]::queries::analysis, rustc_query_impl[469a71c953212c97]::plumbing::QueryCtxt>
  | 59:        0x1110395a8 - <rustc_query_impl[469a71c953212c97]::Queries as rustc_middle[7044477369b49eec]::ty::query::QueryEngine>::analysis
  | 60:        0x10faa996a - <rustc_interface[d2d1d1fbee7644ce]::passes::QueryContext>::enter::<rustc_driver[38920cb2344860e2]::run_compiler::{closure#1}::{closure#2}::{closure#2}, core[fd5e363bb4760a86]::result::Result<(), rustc_errors[112d18aeec5719f8]::ErrorGuaranteed>>
  | 61:        0x10fa8af5d - <rustc_interface[d2d1d1fbee7644ce]::queries::QueryResult<rustc_interface[d2d1d1fbee7644ce]::passes::QueryContext>>::enter::<core[fd5e363bb4760a86]::result::Result<(), rustc_errors[112d18aeec5719f8]::ErrorGuaranteed>, rustc_driver[38920cb2344860e2]::run_compiler::{closure#1}::{closure#2}::{closure#2}>
  | 62:        0x10fae8da3 - <rustc_interface[d2d1d1fbee7644ce]::interface::Compiler>::enter::<rustc_driver[38920cb2344860e2]::run_compiler::{closure#1}::{closure#2}, core[fd5e363bb4760a86]::result::Result<core[fd5e363bb4760a86]::option::Option<rustc_interface[d2d1d1fbee7644ce]::queries::Linker>, rustc_errors[112d18aeec5719f8]::ErrorGuaranteed>>
  | 63:        0x10fb05a86 - rustc_span[abe350e59e28df37]::with_source_map::<core[fd5e363bb4760a86]::result::Result<(), rustc_errors[112d18aeec5719f8]::ErrorGuaranteed>, rustc_interface[d2d1d1fbee7644ce]::interface::run_compiler<core[fd5e363bb4760a86]::result::Result<(), rustc_errors[112d18aeec5719f8]::ErrorGuaranteed>, rustc_driver[38920cb2344860e2]::run_compiler::{closure#1}>::{closure#0}::{closure#0}>
  | 64:        0x10fab03e5 - std[963c226d0575182f]::sys_common::backtrace::__rust_begin_short_backtrace::<rustc_interface[d2d1d1fbee7644ce]::util::run_in_thread_pool_with_globals<rustc_interface[d2d1d1fbee7644ce]::interface::run_compiler<core[fd5e363bb4760a86]::result::Result<(), rustc_errors[112d18aeec5719f8]::ErrorGuaranteed>, rustc_driver[38920cb2344860e2]::run_compiler::{closure#1}>::{closure#0}, core[fd5e363bb4760a86]::result::Result<(), rustc_errors[112d18aeec5719f8]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[fd5e363bb4760a86]::result::Result<(), rustc_errors[112d18aeec5719f8]::ErrorGuaranteed>>
  | 65:        0x10fa8f385 - <<std[963c226d0575182f]::thread::Builder>::spawn_unchecked_<rustc_interface[d2d1d1fbee7644ce]::util::run_in_thread_pool_with_globals<rustc_interface[d2d1d1fbee7644ce]::interface::run_compiler<core[fd5e363bb4760a86]::result::Result<(), rustc_errors[112d18aeec5719f8]::ErrorGuaranteed>, rustc_driver[38920cb2344860e2]::run_compiler::{closure#1}>::{closure#0}, core[fd5e363bb4760a86]::result::Result<(), rustc_errors[112d18aeec5719f8]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[fd5e363bb4760a86]::result::Result<(), rustc_errors[112d18aeec5719f8]::ErrorGuaranteed>>::{closure#1} as core[fd5e363bb4760a86]::ops::function::FnOnce<()>>::call_once::{shim:vtable#0}
  | 66:        0x10c9c25a7 - std::sys::unix::thread::Thread::new::thread_start::had0599fead9033cd
  | 67:     0x7fff6cd62109 - __pthread_start
  |  
  | error: internal compiler error: unexpected panic
  |  
  | note: the compiler unexpectedly panicked. this is a bug.
  |  
  | note: we would appreciate a bug report: https://github.com/rust-lang/rust-clippy/issues/new
  |  
  | note: Clippy version: clippy 0.1.68 (9eb3afe9 2023-03-27)
  |  
  | query stack during panic:
  | end of query stack
  | thread panicked while panicking. aborting.
  | error: could not compile `mz-expr`
  |  
  | Caused by:
  | process didn't exit successfully: `/Users/administrator/.rustup/toolchains/1.68.2-x86_64-apple-darwin/bin/clippy-driver rustc --crate-name mz_expr --edition=2021 src/expr/src/lib.rs --error-format=json --json=diagnostic-rendered-ansi,artifacts,future-incompat --emit=dep-info,metadata -C embed-bitcode=no -C split-debuginfo=unpacked -C debuginfo=2 --test -C metadata=267907b2f5c77320 -C extra-filename=-267907b2f5c77320 --out-dir /opt/builds/mac-1/materialize/tests/target/debug/deps -L dependency=/opt/builds/mac-1/materialize/tests/target/debug/deps --extern aho_corasick=/opt/builds/mac-1/materialize/tests/target/debug/deps/libaho_corasick-e42c1d25dd8f3e55.rmeta --extern anyhow=/opt/builds/mac-1/materialize/tests/target/debug/deps/libanyhow-9d3604a09fdad1b4.rmeta --extern bytes=/opt/builds/mac-1/materialize/tests/target/debug/deps/libbytes-c188c5f8495c9946.rmeta --extern bytesize=/opt/builds/mac-1/materialize/tests/target/debug/deps/libbytesize-dcac8b498e3dbcbe.rmeta --extern chrono=/opt/builds/mac-1/materialize/tests/target/debug/deps/libchrono-406668d0cf778dd7.rmeta --extern criterion=/opt/builds/mac-1/materialize/tests/target/debug/deps/libcriterion-61b3c3816e19cd75.rmeta --extern csv=/opt/builds/mac-1/materialize/tests/target/debug/deps/libcsv-2891e40086708963.rmeta --extern datadriven=/opt/builds/mac-1/materialize/tests/target/debug/deps/libdatadriven-54322fb3608bd2ad.rmeta --extern dec=/opt/builds/mac-1/materialize/tests/target/debug/deps/libdec-f3a3a0c16848acd7.rmeta --extern derivative=/opt/builds/mac-1/materialize/tests/target/debug/deps/libderivative-6dcf9d9f6fcd2acf.dylib --extern encoding=/opt/builds/mac-1/materialize/tests/target/debug/deps/libencoding-d9114f97c85a041d.rmeta --extern enum_iterator=/opt/builds/mac-1/materialize/tests/target/debug/deps/libenum_iterator-1756f02cdbb61103.rmeta --extern fallible_iterator=/opt/builds/mac-1/materialize/tests/target/debug/deps/libfallible_iterator-61564c874b4703d9.rmeta --extern hex=/opt/builds/mac-1/materialize/tests/target/debug/deps/libhex-acb085df55587967.rmeta --extern hmac=/opt/builds/mac-1/materialize/tests/target/debug/deps/libhmac-50c725376416eb04.rmeta --extern itertools=/opt/builds/mac-1/materialize/tests/target/debug/deps/libitertools-e152e543b957ae57.rmeta --extern md5=/opt/builds/mac-1/materialize/tests/target/debug/deps/libmd5-144b82534a1c3079.rmeta --extern mz_expr_test_util=/opt/builds/mac-1/materialize/tests/target/debug/deps/libmz_expr_test_util-bbd1f72653c8fca6.rmeta --extern mz_lowertest=/opt/builds/mac-1/materialize/tests/target/debug/deps/libmz_lowertest-db3b87154ce0f39a.rmeta --extern mz_ore=/opt/builds/mac-1/materialize/tests/target/debug/deps/libmz_ore-e6d7e4d6a4fa8759.rmeta --extern mz_persist_types=/opt/builds/mac-1/materialize/tests/target/debug/deps/libmz_persist_types-fa6d53be3d0d0f52.rmeta --extern mz_pgrepr=/opt/builds/mac-1/materialize/tests/target/debug/deps/libmz_pgrepr-2b0a1abfbc338862.rmeta --extern mz_proto=/opt/builds/mac-1/materialize/tests/target/debug/deps/libmz_proto-9d7141e976db624d.rmeta --extern mz_repr=/opt/builds/mac-1/materialize/tests/target/debug/deps/libmz_repr-193c98975419d3a5.rmeta --extern num=/opt/builds/mac-1/materialize/tests/target/debug/deps/libnum-4608b79cd79573d7.rmeta --extern num_enum=/opt/builds/mac-1/materialize/tests/target/debug/deps/libnum_enum-8d640274d77d468b.rmeta --extern once_cell=/opt/builds/mac-1/materialize/tests/target/debug/deps/libonce_cell-526851c21d0140ea.rmeta --extern ordered_float=/opt/builds/mac-1/materialize/tests/target/debug/deps/libordered_float-9af8d55f9d2e64e5.rmeta --extern paste=/opt/builds/mac-1/materialize/tests/target/debug/deps/libpaste-935228da5ed8f798.dylib --extern proc_macro2=/opt/builds/mac-1/materialize/tests/target/debug/deps/libproc_macro2-b804d88434ed982f.rmeta --extern proptest=/opt/builds/mac-1/materialize/tests/target/debug/deps/libproptest-874cd755a05e87e1.rmeta --extern proptest_derive=/opt/builds/mac-1/materialize/tests/target/debug/deps/libproptest_derive-a8796bc9a7a45a4c.dylib --extern prost=/opt/builds/mac-1/materialize/tests/target/debug/deps/libprost-980029a12c80d9fd.rmeta --extern regex=/opt/builds/mac-1/materialize/tests/target/debug/deps/libregex-331a2f289305aaef.rmeta --extern regex_syntax=/opt/builds/mac-1/materialize/tests/target/debug/deps/libregex_syntax-12bcfc1fdf5b8bde.rmeta --extern serde=/opt/builds/mac-1/materialize/tests/target/debug/deps/libserde-55310b84040edaa8.rmeta --extern serde_json=/opt/builds/mac-1/materialize/tests/target/debug/deps/libserde_json-582ba1092c08f078.rmeta --extern serde_regex=/opt/builds/mac-1/materialize/tests/target/debug/deps/libserde_regex-a26dfedceb8257f9.rmeta --extern sha1=/opt/builds/mac-1/materialize/tests/target/debug/deps/libsha1-24bc2bf69897e7db.rmeta --extern sha2=/opt/builds/mac-1/materialize/tests/target/debug/deps/libsha2-66a6d662cf3bd44b.rmeta --extern tracing=/opt/builds/mac-1/materialize/tests/target/debug/deps/libtracing-a47269257ad7b04e.rmeta --extern uncased=/opt/builds/mac-1/materialize/tests/target/debug/deps/libuncased-5b1a149cb6010723.rmeta --extern uuid=/opt/builds/mac-1/materialize/tests/target/debug/deps/libuuid-934b38ae070167ed.rmeta --extern workspace_hack=/opt/builds/mac-1/materialize/tests/target/debug/deps/libworkspace_hack-fd7c82c52f21d34e.rmeta -L native=/opt/builds/mac-1/materialize/tests/target/debug/build/decnumber-sys-39dc15dd6025acac/out/lib -L native=/opt/builds/mac-1/materialize/tests/target/debug/build/openssl-sys-76ba77ce59516a5b/out/openssl-build/install/lib -L native=/opt/builds/mac-1/materialize/tests/target/debug/build/psm-a16bd4870585941b/out -L native=/opt/builds/mac-1/materialize/tests/target/debug/build/libz-sys-16b45bebf38eb780/out/lib -L native=/opt/builds/mac-1/materialize/tests/target/debug/build/libz-sys-16b45bebf38eb780/out/lib -L native=/opt/builds/mac-1/materialize/tests/target/debug/build/rdkafka-sys-c734b7d0dcc58638/out/lib -L native=/opt/builds/mac-1/materialize/tests/target/debug/build/zstd-sys-613c7f10b331cd23/out -L native=/opt/builds/mac-1/materialize/tests/target/debug/build/ring-e879aad0d55f4d43/out` (signal: 6, SIGABRT: process abort signal)
```

**Comment by blyxyas** [comment]
I couldn't reproduce this isssue. Not even with the toolchain that caused your bug (`1.68.0`). Maybe a Windows issue.
If someone on Windows can confirm this, please notify
Try updating with `rustup update`. If that doesn't fixes the issue, I think this isn't Clippy's fault.

When you've updated, if the issue is still the same, could you re-send the first line of the error from the updated ICE?

**Comment by mgree** [comment]
I haven't been able to reproduce it, either---some other changes made it go away in CI. Maybe a transient misconfiguration on our end?
