### ISSUE TITLE
ice: `Contradiction with Some(DefId(0:50068 ~ core[8f25]::core_simd::alias::mask8x16)) and Some(DefId(0:21244 ~ core[8f25]::core_simd::masks::Mask)`

### ISSUE THREAD

**Issue by matthiaskrgr** [rust-lang/rust-clippy#11256]
### Summary

This happens when running a clippy (from the repo) on  `core` of its pinned nigthly

### Version

```text
29730969b196781e92ca8c8b2d0a8bf9bb105e22
```

### Error output

<details><summary>Backtrace</summary>
  <p>

  ```
  2023-07-30T00:18:02.5568815Z thread 'rustc' panicked at 'Contradiction with Some(DefId(0:50068 ~ core[8f25]::core_simd::alias::mask8x16)) and Some(DefId(0:21244 ~ core[8f25]::core_simd::masks::Mask))', clippy_utils/src/ty/type_certainty/certainty.rs:68:21
2023-07-30T00:18:02.5568929Z stack backtrace:
2023-07-30T00:18:02.5569458Z    0:     0x7f4d17bedfc1 - std::backtrace_rs::backtrace::libunwind::trace::h757b492de7e38f51
2023-07-30T00:18:02.5569811Z                                at /rustc/500647fd8138cc09e87edb08d62f81654fbf6ef8/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
2023-07-30T00:18:02.5570203Z    1:     0x7f4d17bedfc1 - std::backtrace_rs::backtrace::trace_unsynchronized::he91e3190ab8d9c4f
2023-07-30T00:18:02.5570455Z                                at /rustc/500647fd8138cc09e87edb08d62f81654fbf6ef8/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
2023-07-30T00:18:02.5570794Z    2:     0x7f4d17bedfc1 - std::sys_common::backtrace::_print_fmt::h6e24477d644418e5
2023-07-30T00:18:02.5571028Z                                at /rustc/500647fd8138cc09e87edb08d62f81654fbf6ef8/library/std/src/sys_common/backtrace.rs:65:5
2023-07-30T00:18:02.5571459Z    3:     0x7f4d17bedfc1 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h3878e1514fe266c9
2023-07-30T00:18:02.5571694Z                                at /rustc/500647fd8138cc09e87edb08d62f81654fbf6ef8/library/std/src/sys_common/backtrace.rs:44:22
2023-07-30T00:18:02.5572015Z    4:     0x7f4d17c5449c - core::fmt::rt::Argument::fmt::h407ed1ed725edf0f
2023-07-30T00:18:02.5572229Z                                at /rustc/500647fd8138cc09e87edb08d62f81654fbf6ef8/library/core/src/fmt/rt.rs:138:9
2023-07-30T00:18:02.5572927Z    5:     0x7f4d17c5449c - core::fmt::write::h80ad66db775b495e
2023-07-30T00:18:02.5573115Z                                at /rustc/500647fd8138cc09e87edb08d62f81654fbf6ef8/library/core/src/fmt/mod.rs:1094:21
2023-07-30T00:18:02.5573401Z    6:     0x7f4d17be06be - std::io::Write::write_fmt::h535bb7b7a3791561
2023-07-30T00:18:02.5573591Z                                at /rustc/500647fd8138cc09e87edb08d62f81654fbf6ef8/library/std/src/io/mod.rs:1714:15
2023-07-30T00:18:02.5573889Z    7:     0x7f4d17beddd5 - std::sys_common::backtrace::_print::hb86dcc235566a2df
2023-07-30T00:18:02.5574101Z                                at /rustc/500647fd8138cc09e87edb08d62f81654fbf6ef8/library/std/src/sys_common/backtrace.rs:47:5
2023-07-30T00:18:02.5574403Z    8:     0x7f4d17beddd5 - std::sys_common::backtrace::print::h720885d4d12f3280
2023-07-30T00:18:02.5574612Z                                at /rustc/500647fd8138cc09e87edb08d62f81654fbf6ef8/library/std/src/sys_common/backtrace.rs:34:9
2023-07-30T00:18:02.5574953Z    9:     0x7f4d17bf0e2a - std::panicking::panic_hook_with_disk_dump::{{closure}}::h760a0ce73306965a
2023-07-30T00:18:02.5575153Z                                at /rustc/500647fd8138cc09e87edb08d62f81654fbf6ef8/library/std/src/panicking.rs:278:22
2023-07-30T00:18:02.5575464Z   10:     0x7f4d17bf0ac3 - std::panicking::panic_hook_with_disk_dump::hd7987642ef347005
2023-07-30T00:18:02.5575646Z                                at /rustc/500647fd8138cc09e87edb08d62f81654fbf6ef8/library/std/src/panicking.rs:312:9
2023-07-30T00:18:02.5575982Z   11:     0x7f4d1ae0ef09 - rustc_driver_impl[4c3415319b4cba14]::install_ice_hook::{closure#0}
2023-07-30T00:18:02.5576430Z   12:     0x7f4d17bf16d0 - <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call::hc74b41dc32ec0c34
2023-07-30T00:18:02.5576628Z                                at /rustc/500647fd8138cc09e87edb08d62f81654fbf6ef8/library/alloc/src/boxed.rs:2021:9
2023-07-30T00:18:02.5576933Z   13:     0x7f4d17bf16d0 - std::panicking::rust_panic_with_hook::h917efb61d3f92bd6
2023-07-30T00:18:02.5577137Z                                at /rustc/500647fd8138cc09e87edb08d62f81654fbf6ef8/library/std/src/panicking.rs:733:13
2023-07-30T00:18:02.5577464Z   14:     0x7f4d17bf1457 - std::panicking::begin_panic_handler::{{closure}}::haad6fd7fd7304435
2023-07-30T00:18:02.5577816Z                                at /rustc/500647fd8138cc09e87edb08d62f81654fbf6ef8/library/std/src/panicking.rs:621:13
2023-07-30T00:18:02.5578144Z   15:     0x7f4d17bee426 - std::sys_common::backtrace::__rust_end_short_backtrace::hfe68e06c05b03ef8
2023-07-30T00:18:02.5578595Z                                at /rustc/500647fd8138cc09e87edb08d62f81654fbf6ef8/library/std/src/sys_common/backtrace.rs:151:18
2023-07-30T00:18:02.5579470Z   16:     0x7f4d17bf11a2 - rust_begin_unwind
2023-07-30T00:18:02.5579852Z                                at /rustc/500647fd8138cc09e87edb08d62f81654fbf6ef8/library/std/src/panicking.rs:617:5
2023-07-30T00:18:02.5580145Z   17:     0x7f4d17c50853 - core::panicking::panic_fmt::h17205bc5f2d82306
2023-07-30T00:18:02.5580351Z                                at /rustc/500647fd8138cc09e87edb08d62f81654fbf6ef8/library/core/src/panicking.rs:67:14
2023-07-30T00:18:02.5580879Z   18:     0x55f123627c25 - clippy_utils::ty::type_certainty::certainty::Certainty::join::h06532f784efd59b9
2023-07-30T00:18:02.5581439Z                                at /home/runner/work/rust-clippy/rust-clippy/clippy_utils/src/ty/type_certainty/certainty.rs:68:21
2023-07-30T00:18:02.5581811Z   19:     0x55f123547c51 - clippy_utils::ty::type_certainty::path_segment_certainty::hbd71eaf8cbcadc9d
2023-07-30T00:18:02.5582182Z                                at /home/runner/work/rust-clippy/rust-clippy/clippy_utils/src/ty/type_certainty/mod.rs:246:33
2023-07-30T00:18:02.5582901Z   20:     0x55f123547364 - clippy_utils::ty::type_certainty::qpath_certainty::{{closure}}::h6b5cf95f2f21f555
2023-07-30T00:18:02.5583642Z                                at /home/runner/work/rust-clippy/rust-clippy/clippy_utils/src/ty/type_certainty/mod.rs:164:21
2023-07-30T00:18:02.5584231Z   21:     0x55f1235e026c - <core::iter::adapters::enumerate::Enumerate<I> as core::iter::traits::iterator::Iterator>::fold::enumerate::{{closure}}::h8e25f75caaeada28
2023-07-30T00:18:02.5584652Z                                at /rustc/500647fd8138cc09e87edb08d62f81654fbf6ef8/library/core/src/iter/adapters/enumerate.rs:107:27
2023-07-30T00:18:02.5585074Z   22:     0x55f12343f7b4 - <core::slice::iter::Iter<T> as core::iter::traits::iterator::Iterator>::fold::h943817ec11c3e1e6
2023-07-30T00:18:02.5585303Z                                at /rustc/500647fd8138cc09e87edb08d62f81654fbf6ef8/library/core/src/slice/iter/macros.rs:232:27
2023-07-30T00:18:02.5585769Z   23:     0x55f1235dfffb - <core::iter::adapters::enumerate::Enumerate<I> as core::iter::traits::iterator::Iterator>::fold::h5106d30f1aac4e89
2023-07-30T00:18:02.5586015Z                                at /rustc/500647fd8138cc09e87edb08d62f81654fbf6ef8/library/core/src/iter/adapters/enumerate.rs:113:9
2023-07-30T00:18:02.5586384Z   24:     0x55f12354710c - clippy_utils::ty::type_certainty::qpath_certainty::hf70ce00a9486240e
2023-07-30T00:18:02.5586762Z                                at /home/runner/work/rust-clippy/rust-clippy/clippy_utils/src/ty/type_certainty/mod.rs:161:13
2023-07-30T00:18:02.5587679Z   25:     0x55f1235468fb - clippy_utils::ty::type_certainty::expr_type_certainty::h7f8f2dd19bcec382
2023-07-30T00:18:02.5588404Z                                at /home/runner/work/rust-clippy/rust-clippy/clippy_utils/src/ty/type_certainty/mod.rs:82:34
2023-07-30T00:18:02.5589042Z   26:     0x55f1235464e3 - clippy_utils::ty::type_certainty::expr_type_is_certain::hbc3b7b33bd8998d9
2023-07-30T00:18:02.5589524Z                                at /home/runner/work/rust-clippy/rust-clippy/clippy_utils/src/ty/type_certainty/mod.rs:27:5
2023-07-30T00:18:02.5589918Z   27:     0x55f122896ea7 - clippy_lints::methods::or_fun_call::check::check_unwrap_or_default::h1b1060041fe1f722
2023-07-30T00:18:02.5590290Z                                at /home/runner/work/rust-clippy/rust-clippy/clippy_lints/src/methods/or_fun_call.rs:40:13
2023-07-30T00:18:02.5590633Z   28:     0x55f122896b3a - clippy_lints::methods::or_fun_call::check::h1ae69605902366b9
2023-07-30T00:18:02.5591006Z                                at /home/runner/work/rust-clippy/rust-clippy/clippy_lints/src/methods/or_fun_call.rs:199:17
2023-07-30T00:18:02.5591443Z   29:     0x55f122d38328 - <clippy_lints::methods::Methods as rustc_lint::passes::LateLintPass>::check_expr::h4ea70c34dd570a1b
2023-07-30T00:18:02.5591799Z                                at /home/runner/work/rust-clippy/rust-clippy/clippy_lints/src/methods/mod.rs:3710:17
2023-07-30T00:18:02.5592438Z   30:     0x7f4d1b23f8d6 - <rustc_lint[59158b030fdc9e0]::early::RuntimeCombinedEarlyLintPass as rustc_lint[59158b030fdc9e0]::passes::EarlyLintPass>::check_generic_arg
2023-07-30T00:18:02.5593173Z   31:     0x7f4d1b1e4e97 - <rustc_lint[59158b030fdc9e0]::late::LateContextAndPass<rustc_lint[59158b030fdc9e0]::late::RuntimeCombinedLateLintPass> as rustc_hir[680107fc1872d849]::intravisit::Visitor>::visit_expr
2023-07-30T00:18:02.5593787Z   32:     0x7f4d1b1fe66b - rustc_hir[680107fc1872d849]::intravisit::walk_local::<rustc_lint[59158b030fdc9e0]::late::LateContextAndPass<rustc_lint[59158b030fdc9e0]::late::RuntimeCombinedLateLintPass>>
2023-07-30T00:18:02.5594418Z   33:     0x7f4d1b1e50cc - <rustc_lint[59158b030fdc9e0]::late::LateContextAndPass<rustc_lint[59158b030fdc9e0]::late::RuntimeCombinedLateLintPass> as rustc_hir[680107fc1872d849]::intravisit::Visitor>::visit_local
2023-07-30T00:18:02.5595026Z   34:     0x7f4d1b1fe61b - rustc_hir[680107fc1872d849]::intravisit::walk_block::<rustc_lint[59158b030fdc9e0]::late::LateContextAndPass<rustc_lint[59158b030fdc9e0]::late::RuntimeCombinedLateLintPass>>
2023-07-30T00:18:02.5595668Z   35:     0x7f4d1b1e5049 - <rustc_lint[59158b030fdc9e0]::late::LateContextAndPass<rustc_lint[59158b030fdc9e0]::late::RuntimeCombinedLateLintPass> as rustc_hir[680107fc1872d849]::intravisit::Visitor>::visit_block
2023-07-30T00:18:02.5596380Z   36:     0x7f4d1b1e4ea2 - <rustc_lint[59158b030fdc9e0]::late::LateContextAndPass<rustc_lint[59158b030fdc9e0]::late::RuntimeCombinedLateLintPass> as rustc_hir[680107fc1872d849]::intravisit::Visitor>::visit_expr
2023-07-30T00:18:02.5597044Z   37:     0x7f4d1b1e539a - <rustc_lint[59158b030fdc9e0]::late::LateContextAndPass<rustc_lint[59158b030fdc9e0]::late::RuntimeCombinedLateLintPass> as rustc_hir[680107fc1872d849]::intravisit::Visitor>::visit_nested_body
2023-07-30T00:18:02.5597669Z   38:     0x7f4d1b1e5530 - <rustc_lint[59158b030fdc9e0]::late::LateContextAndPass<rustc_lint[59158b030fdc9e0]::late::RuntimeCombinedLateLintPass> as rustc_hir[680107fc1872d849]::intravisit::Visitor>::visit_fn
2023-07-30T00:18:02.5598277Z   39:     0x7f4d1b1ffd69 - rustc_hir[680107fc1872d849]::intravisit::walk_expr::<rustc_lint[59158b030fdc9e0]::late::LateContextAndPass<rustc_lint[59158b030fdc9e0]::late::RuntimeCombinedLateLintPass>>
2023-07-30T00:18:02.5599446Z   40:     0x7f4d1b1e4ea2 - <rustc_lint[59158b030fdc9e0]::late::LateContextAndPass<rustc_lint[59158b030fdc9e0]::late::RuntimeCombinedLateLintPass> as rustc_hir[680107fc1872d849]::intravisit::Visitor>::visit_expr
2023-07-30T00:18:02.5599990Z   41:     0x7f4d1b1fe66b - rustc_hir[680107fc1872d849]::intravisit::walk_local::<rustc_lint[59158b030fdc9e0]::late::LateContextAndPass<rustc_lint[59158b030fdc9e0]::late::RuntimeCombinedLateLintPass>>
2023-07-30T00:18:02.5600560Z   42:     0x7f4d1b1e50cc - <rustc_lint[59158b030fdc9e0]::late::LateContextAndPass<rustc_lint[59158b030fdc9e0]::late::RuntimeCombinedLateLintPass> as rustc_hir[680107fc1872d849]::intravisit::Visitor>::visit_local
2023-07-30T00:18:02.5601193Z   43:     0x7f4d1b1fe61b - rustc_hir[680107fc1872d849]::intravisit::walk_block::<rustc_lint[59158b030fdc9e0]::late::LateContextAndPass<rustc_lint[59158b030fdc9e0]::late::RuntimeCombinedLateLintPass>>
2023-07-30T00:18:02.5601762Z   44:     0x7f4d1b1e5049 - <rustc_lint[59158b030fdc9e0]::late::LateContextAndPass<rustc_lint[59158b030fdc9e0]::late::RuntimeCombinedLateLintPass> as rustc_hir[680107fc1872d849]::intravisit::Visitor>::visit_block
2023-07-30T00:18:02.5602377Z   45:     0x7f4d1b1e4ea2 - <rustc_lint[59158b030fdc9e0]::late::LateContextAndPass<rustc_lint[59158b030fdc9e0]::late::RuntimeCombinedLateLintPass> as rustc_hir[680107fc1872d849]::intravisit::Visitor>::visit_expr
2023-07-30T00:18:02.5603144Z   46:     0x7f4d1b1e539a - <rustc_lint[59158b030fdc9e0]::late::LateContextAndPass<rustc_lint[59158b030fdc9e0]::late::RuntimeCombinedLateLintPass> as rustc_hir[680107fc1872d849]::intravisit::Visitor>::visit_nested_body
2023-07-30T00:18:02.5603828Z   47:     0x7f4d1b1e5530 - <rustc_lint[59158b030fdc9e0]::late::LateContextAndPass<rustc_lint[59158b030fdc9e0]::late::RuntimeCombinedLateLintPass> as rustc_hir[680107fc1872d849]::intravisit::Visitor>::visit_fn
2023-07-30T00:18:02.5604834Z   48:     0x7f4d1b1fff83 - rustc_hir[680107fc1872d849]::intravisit::walk_item::<rustc_lint[59158b030fdc9e0]::late::LateContextAndPass<rustc_lint[59158b030fdc9e0]::late::RuntimeCombinedLateLintPass>>
2023-07-30T00:18:02.5605482Z   49:     0x7f4d1b1e5daf - <rustc_lint[59158b030fdc9e0]::late::LateContextAndPass<rustc_lint[59158b030fdc9e0]::late::RuntimeCombinedLateLintPass> as rustc_hir[680107fc1872d849]::intravisit::Visitor>::visit_nested_item
2023-07-30T00:18:02.5606079Z   50:     0x7f4d1b1ff808 - rustc_hir[680107fc1872d849]::intravisit::walk_mod::<rustc_lint[59158b030fdc9e0]::late::LateContextAndPass<rustc_lint[59158b030fdc9e0]::late::RuntimeCombinedLateLintPass>>
2023-07-30T00:18:02.5606728Z   51:     0x7f4d1b1e5daf - <rustc_lint[59158b030fdc9e0]::late::LateContextAndPass<rustc_lint[59158b030fdc9e0]::late::RuntimeCombinedLateLintPass> as rustc_hir[680107fc1872d849]::intravisit::Visitor>::visit_nested_item
2023-07-30T00:18:02.5607330Z   52:     0x7f4d1b1ff808 - rustc_hir[680107fc1872d849]::intravisit::walk_mod::<rustc_lint[59158b030fdc9e0]::late::LateContextAndPass<rustc_lint[59158b030fdc9e0]::late::RuntimeCombinedLateLintPass>>
2023-07-30T00:18:02.5608054Z   53:     0x7f4d1b1e5daf - <rustc_lint[59158b030fdc9e0]::late::LateContextAndPass<rustc_lint[59158b030fdc9e0]::late::RuntimeCombinedLateLintPass> as rustc_hir[680107fc1872d849]::intravisit::Visitor>::visit_nested_item
2023-07-30T00:18:02.5608849Z   54:     0x7f4d1b1ff808 - rustc_hir[680107fc1872d849]::intravisit::walk_mod::<rustc_lint[59158b030fdc9e0]::late::LateContextAndPass<rustc_lint[59158b030fdc9e0]::late::RuntimeCombinedLateLintPass>>
2023-07-30T00:18:02.5609289Z   55:     0x7f4d1a2aca39 - rustc_lint[59158b030fdc9e0]::late::late_lint_crate::<rustc_lint[59158b030fdc9e0]::BuiltinCombinedLateLintPass>
2023-07-30T00:18:02.5610147Z   56:     0x7f4d1a2abed8 - <rustc_session[f4a3fd7c44936466]::session::Session>::time::<(), rustc_lint[59158b030fdc9e0]::late::check_crate<rustc_lint[59158b030fdc9e0]::BuiltinCombinedLateLintPass, rustc_interface[effa57ef6cdf43c8]::passes::analysis::{closure#5}::{closure#1}::{closure#2}::{closure#0}::{closure#0}>::{closure#0}::{closure#0}>
2023-07-30T00:18:02.5610700Z   57:     0x7f4d1a2abd73 - <rustc_session[f4a3fd7c44936466]::session::Session>::time::<(), rustc_interface[effa57ef6cdf43c8]::passes::analysis::{closure#5}::{closure#1}::{closure#2}::{closure#0}>
2023-07-30T00:18:02.5611310Z   58:     0x7f4d1a2ab8ab - <core[14419025a21183a1]::panic::unwind_safe::AssertUnwindSafe<rustc_interface[effa57ef6cdf43c8]::passes::analysis::{closure#5}::{closure#1}> as core[14419025a21183a1]::ops::function::FnOnce<()>>::call_once
2023-07-30T00:18:02.5611782Z   59:     0x7f4d1a2ab2c8 - <rustc_session[f4a3fd7c44936466]::session::Session>::time::<(), rustc_interface[effa57ef6cdf43c8]::passes::analysis::{closure#5}>
2023-07-30T00:18:02.5612277Z   60:     0x7f4d1a2a9e97 - rustc_interface[effa57ef6cdf43c8]::passes::analysis
2023-07-30T00:18:02.5613293Z   61:     0x7f4d1a304d2a - rustc_query_impl[9e9aac2bcfc5a39e]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[9e9aac2bcfc5a39e]::query_impl::analysis::dynamic_query::{closure#2}::{closure#0}, rustc_middle[b0c4fd38174bce7e]::query::erase::Erased<[u8; 1usize]>>
2023-07-30T00:18:02.5613949Z   62:     0x7f4d1a304d19 - <rustc_query_impl[9e9aac2bcfc5a39e]::query_impl::analysis::dynamic_query::{closure#2} as core[14419025a21183a1]::ops::function::FnOnce<(rustc_middle[b0c4fd38174bce7e]::ty::context::TyCtxt, ())>>::call_once
2023-07-30T00:18:02.5614928Z   63:     0x7f4d1a4b5a08 - rustc_query_system[bd77d5a6524fb1ee]::query::plumbing::try_execute_query::<rustc_query_impl[9e9aac2bcfc5a39e]::DynamicConfig<rustc_query_system[bd77d5a6524fb1ee]::query::caches::SingleCache<rustc_middle[b0c4fd38174bce7e]::query::erase::Erased<[u8; 1usize]>>, false, false, false>, rustc_query_impl[9e9aac2bcfc5a39e]::plumbing::QueryCtxt, false>
2023-07-30T00:18:02.5615465Z   64:     0x7f4d1a4b5797 - rustc_query_impl[9e9aac2bcfc5a39e]::query_impl::analysis::get_query_non_incr::__rust_end_short_backtrace
2023-07-30T00:18:02.5616272Z   65:     0x7f4d1a0907f5 - <rustc_middle[b0c4fd38174bce7e]::ty::context::GlobalCtxt>::enter::<rustc_driver_impl[4c3415319b4cba14]::run_compiler::{closure#1}::{closure#2}::{closure#4}, core[14419025a21183a1]::result::Result<(), rustc_span[a85072546ba3a5ab]::ErrorGuaranteed>>
2023-07-30T00:18:02.5618051Z   66:     0x7f4d1a08fe22 - <rustc_interface[effa57ef6cdf43c8]::interface::Compiler>::enter::<rustc_driver_impl[4c3415319b4cba14]::run_compiler::{closure#1}::{closure#2}, core[14419025a21183a1]::result::Result<core[14419025a21183a1]::option::Option<rustc_interface[effa57ef6cdf43c8]::queries::Linker>, rustc_span[a85072546ba3a5ab]::ErrorGuaranteed>>
2023-07-30T00:18:02.5619846Z   67:     0x7f4d1a088ed8 - std[5080124dd0971100]::sys_common::backtrace::__rust_begin_short_backtrace::<rustc_interface[effa57ef6cdf43c8]::util::run_in_thread_pool_with_globals<rustc_interface[effa57ef6cdf43c8]::interface::run_compiler<core[14419025a21183a1]::result::Result<(), rustc_span[a85072546ba3a5ab]::ErrorGuaranteed>, rustc_driver_impl[4c3415319b4cba14]::run_compiler::{closure#1}>::{closure#0}, core[14419025a21183a1]::result::Result<(), rustc_span[a85072546ba3a5ab]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[14419025a21183a1]::result::Result<(), rustc_span[a85072546ba3a5ab]::ErrorGuaranteed>>
2023-07-30T00:18:02.5621456Z   68:     0x7f4d1a08865e - <<std[5080124dd0971100]::thread::Builder>::spawn_unchecked_<rustc_interface[effa57ef6cdf43c8]::util::run_in_thread_pool_with_globals<rustc_interface[effa57ef6cdf43c8]::interface::run_compiler<core[14419025a21183a1]::result::Result<(), rustc_span[a85072546ba3a5ab]::ErrorGuaranteed>, rustc_driver_impl[4c3415319b4cba14]::run_compiler::{closure#1}>::{closure#0}, core[14419025a21183a1]::result::Result<(), rustc_span[a85072546ba3a5ab]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[14419025a21183a1]::result::Result<(), rustc_span[a85072546ba3a5ab]::ErrorGuaranteed>>::{closure#1} as core[14419025a21183a1]::ops::function::FnOnce<()>>::call_once::{shim:vtable#0}
2023-07-30T00:18:02.5621889Z   69:     0x7f4d17bfbdc5 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::heeee2b291a22389d
2023-07-30T00:18:02.5622110Z                                at /rustc/500647fd8138cc09e87edb08d62f81654fbf6ef8/library/alloc/src/boxed.rs:2007:9
2023-07-30T00:18:02.5622520Z   70:     0x7f4d17bfbdc5 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::hb0196af3fff8f8b5
2023-07-30T00:18:02.5622738Z                                at /rustc/500647fd8138cc09e87edb08d62f81654fbf6ef8/library/alloc/src/boxed.rs:2007:9
2023-07-30T00:18:02.5623098Z   71:     0x7f4d17bfbdc5 - std::sys::unix::thread::Thread::new::thread_start::hbcdc2efff7ecdfed
2023-07-30T00:18:02.5623321Z                                at /rustc/500647fd8138cc09e87edb08d62f81654fbf6ef8/library/std/src/sys/unix/thread.rs:108:17
2023-07-30T00:18:02.5623660Z   72:     0x7f4d17849b43 - <unknown>
2023-07-30T00:18:02.5623837Z   73:     0x7f4d178dba00 - <unknown>
2023-07-30T00:18:02.5623997Z   74:                0x0 - <unknown>
2023-07-30T00:18:02.5624010Z 
2023-07-30T00:18:02.5624167Z error: the compiler unexpectedly panicked. this is a bug.
2023-07-30T00:18:02.5624190Z 
2023-07-30T00:18:02.5624574Z note: we would appreciate a bug report: https://github.com/rust-lang/rust-clippy/issues/new?template=ice.yml
2023-07-30T00:18:02.5624583Z 
2023-07-30T00:18:02.5624988Z note: please attach the file at `/tmp/.tmpr3wtPY/rust/rustc-ice-2023-07-30T00:17:13.901829172Z-3338.txt` to your bug report
2023-07-30T00:18:02.5624996Z 
2023-07-30T00:18:02.5626299Z note: compiler flags: --crate-type lib -C opt-level=3 -C embed-bitcode=no -Z unstable-options -C symbol-mangling-version=legacy -Z unstable-options -Z unstable-options -Z force-unstable-if-unmarked -Z macro-backtrace -C link-args=-Wl,-z,origin -C link-args=-Wl,-rpath,$ORIGIN/../lib -C split-debuginfo=off -C prefer-dynamic -Z inline-mir -Z crate-attr=doc(html_root_url="https://doc.rust-lang.org/nightly/") -Z binary-dep-depinfo
2023-07-30T00:18:02.5626375Z 
2023-07-30T00:18:02.5626563Z note: some of the compiler flags provided by cargo are hidden
2023-07-30T00:18:02.5626570Z 
2023-07-30T00:18:02.5626683Z query stack during panic:
2023-07-30T00:18:02.5626839Z #0 [analysis] running analysis passes on this crate
2023-07-30T00:18:02.5626940Z end of query stack
2023-07-30T00:18:02.5627189Z note: Clippy version: clippy 0.1.73 (420aaba 2023-07-30)
  ```

  </p>
</details>

**Comment by Centri3** [comment]
cc @smoelius, you originally worked on the type certainty module

**Comment by smoelius** [comment]
@Centri3 Thank you very much for the heads up, and thank you @Jarcho for fixing the bug.
