### ISSUE TITLE
[ICE clippy]: `'rustc' panicked at src\tools\clippy\clippy_lints\src\redundant_locals.rs:67:49`

### ISSUE THREAD

**Issue by Recurse-blip** [rust-lang/rust-clippy#11954]
### Summary

While trying to run clippy on my rust project.

```
cargo clippy
```

### Version

```text
rustc 1.74.1 (a28077b28 2023-12-04)
binary: rustc
commit-hash: a28077b28a02b92985b3a3faecf92813155f1ea1
commit-date: 2023-12-04
host: x86_64-pc-windows-msvc
release: 1.74.1
LLVM version: 17.0.4
```

### Error output

<details><summary>Backtrace</summary>
  <p>

  ```
  thread 'rustc' panicked at src\tools\clippy\clippy_lints\src\redundant_locals.rs:67:49:
called `Option::unwrap()` on a `None` value
stack backtrace:
   0:     0x7ffbab6d594a - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::hce7f16cdb20fbfd8
   1:     0x7ffbab70a2eb - core::fmt::write::ha7deba3fa4a5d73d
   2:     0x7ffbab6cb4c1 - <std::io::IoSlice as core::fmt::Debug>::fmt::hc765b3768a844021
   3:     0x7ffbab6d56ca - std::sys_common::backtrace::lock::h057ac4e4a9589552
   4:     0x7ffbab6d8dca - std::panicking::default_hook::he79bec7d5a7fc7e0
   5:     0x7ffbab6d8a38 - std::panicking::default_hook::he79bec7d5a7fc7e0
   6:     0x7ffac29226b7 - <tracing_subscriber[50bcbe62d64bf606]::fmt::format::Writer>::write_fmt
   7:     0x7ffbab6d96c9 - std::panicking::rust_panic_with_hook::h494e665893a73306
   8:     0x7ffbab6d93d2 - <std::panicking::begin_panic_handler::StaticStrPayload as core::panic::PanicPayload>::get::h1f5b432ad38f4185
   9:     0x7ffbab6d6609 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::hce7f16cdb20fbfd8
  10:     0x7ffbab6d9130 - rust_begin_unwind
  11:     0x7ffbab73f237 - core::panicking::panic_fmt::hbf829af3c266e156
  12:     0x7ffbab73f2f2 - core::panicking::panic::hed1c862ca98ff0c3
  13:     0x7ff6b6b6446a - <unknown>
  14:     0x7ffac3798ab0 - <rustc_lint[84f4ef4ea065d03c]::reference_casting::InvalidReferenceCasting as rustc_lint_defs[bc231ca48d0fadb9]::LintPass>::name
  15:     0x7ffac37cc0dc - <rustc_lint[84f4ef4ea065d03c]::opaque_hidden_inferred_bound::OpaqueHiddenInferredBoundLint as rustc_errors[ae5992cadf1f8467]::diagnostic::DecorateLint<()>>::msg
  16:     0x7ffac3798b67 - <rustc_lint[84f4ef4ea065d03c]::reference_casting::InvalidReferenceCasting as rustc_lint_defs[bc231ca48d0fadb9]::LintPass>::name
  17:     0x7ffac379818c - <rustc_lint[84f4ef4ea065d03c]::reference_casting::InvalidReferenceCasting as rustc_lint_defs[bc231ca48d0fadb9]::LintPass>::name
  18:     0x7ffac379818c - <rustc_lint[84f4ef4ea065d03c]::reference_casting::InvalidReferenceCasting as rustc_lint_defs[bc231ca48d0fadb9]::LintPass>::name
  19:     0x7ffac3798b67 - <rustc_lint[84f4ef4ea065d03c]::reference_casting::InvalidReferenceCasting as rustc_lint_defs[bc231ca48d0fadb9]::LintPass>::name
  20:     0x7ffac379818c - <rustc_lint[84f4ef4ea065d03c]::reference_casting::InvalidReferenceCasting as rustc_lint_defs[bc231ca48d0fadb9]::LintPass>::name
  21:     0x7ffac3797c14 - <rustc_lint[84f4ef4ea065d03c]::reference_casting::InvalidReferenceCasting as rustc_lint_defs[bc231ca48d0fadb9]::LintPass>::name
  22:     0x7ffac379850d - <rustc_lint[84f4ef4ea065d03c]::reference_casting::InvalidReferenceCasting as rustc_lint_defs[bc231ca48d0fadb9]::LintPass>::name
  23:     0x7ffac37cee1b - <rustc_lint[84f4ef4ea065d03c]::opaque_hidden_inferred_bound::OpaqueHiddenInferredBoundLint as rustc_errors[ae5992cadf1f8467]::diagnostic::DecorateLint<()>>::msg
  24:     0x7ffac379818c - <rustc_lint[84f4ef4ea065d03c]::reference_casting::InvalidReferenceCasting as rustc_lint_defs[bc231ca48d0fadb9]::LintPass>::name
  25:     0x7ffac3797c14 - <rustc_lint[84f4ef4ea065d03c]::reference_casting::InvalidReferenceCasting as rustc_lint_defs[bc231ca48d0fadb9]::LintPass>::name
  26:     0x7ffac379850d - <rustc_lint[84f4ef4ea065d03c]::reference_casting::InvalidReferenceCasting as rustc_lint_defs[bc231ca48d0fadb9]::LintPass>::name
  27:     0x7ffac37cc7e6 - <rustc_lint[84f4ef4ea065d03c]::opaque_hidden_inferred_bound::OpaqueHiddenInferredBoundLint as rustc_errors[ae5992cadf1f8467]::diagnostic::DecorateLint<()>>::msg
  28:     0x7ffac379653b - <rustc_lint[84f4ef4ea065d03c]::reference_casting::InvalidReferenceCasting as rustc_lint_defs[bc231ca48d0fadb9]::LintPass>::name
  29:     0x7ffac37cf5ed - <rustc_lint[84f4ef4ea065d03c]::opaque_hidden_inferred_bound::OpaqueHiddenInferredBoundLint as rustc_errors[ae5992cadf1f8467]::diagnostic::DecorateLint<()>>::msg
  30:     0x7ffac379631f - <rustc_lint[84f4ef4ea065d03c]::reference_casting::InvalidReferenceCasting as rustc_lint_defs[bc231ca48d0fadb9]::LintPass>::name
  31:     0x7ffac37ce4db - <rustc_lint[84f4ef4ea065d03c]::opaque_hidden_inferred_bound::OpaqueHiddenInferredBoundLint as rustc_errors[ae5992cadf1f8467]::diagnostic::DecorateLint<()>>::msg
  32:     0x7ffac37cf43e - <rustc_lint[84f4ef4ea065d03c]::opaque_hidden_inferred_bound::OpaqueHiddenInferredBoundLint as rustc_errors[ae5992cadf1f8467]::diagnostic::DecorateLint<()>>::msg
  33:     0x7ffac379631f - <rustc_lint[84f4ef4ea065d03c]::reference_casting::InvalidReferenceCasting as rustc_lint_defs[bc231ca48d0fadb9]::LintPass>::name
  34:     0x7ffac37ce4db - <rustc_lint[84f4ef4ea065d03c]::opaque_hidden_inferred_bound::OpaqueHiddenInferredBoundLint as rustc_errors[ae5992cadf1f8467]::diagnostic::DecorateLint<()>>::msg
  35:     0x7ffac37cf43e - <rustc_lint[84f4ef4ea065d03c]::opaque_hidden_inferred_bound::OpaqueHiddenInferredBoundLint as rustc_errors[ae5992cadf1f8467]::diagnostic::DecorateLint<()>>::msg
  36:     0x7ffac379631f - <rustc_lint[84f4ef4ea065d03c]::reference_casting::InvalidReferenceCasting as rustc_lint_defs[bc231ca48d0fadb9]::LintPass>::name
  37:     0x7ffac37ce4db - <rustc_lint[84f4ef4ea065d03c]::opaque_hidden_inferred_bound::OpaqueHiddenInferredBoundLint as rustc_errors[ae5992cadf1f8467]::diagnostic::DecorateLint<()>>::msg
  38:     0x7ffac37cf43e - <rustc_lint[84f4ef4ea065d03c]::opaque_hidden_inferred_bound::OpaqueHiddenInferredBoundLint as rustc_errors[ae5992cadf1f8467]::diagnostic::DecorateLint<()>>::msg
  39:     0x7ffac379631f - <rustc_lint[84f4ef4ea065d03c]::reference_casting::InvalidReferenceCasting as rustc_lint_defs[bc231ca48d0fadb9]::LintPass>::name
  40:     0x7ffac37ce4db - <rustc_lint[84f4ef4ea065d03c]::opaque_hidden_inferred_bound::OpaqueHiddenInferredBoundLint as rustc_errors[ae5992cadf1f8467]::diagnostic::DecorateLint<()>>::msg
  41:     0x7ffac37cf43e - <rustc_lint[84f4ef4ea065d03c]::opaque_hidden_inferred_bound::OpaqueHiddenInferredBoundLint as rustc_errors[ae5992cadf1f8467]::diagnostic::DecorateLint<()>>::msg
  42:     0x7ffac379631f - <rustc_lint[84f4ef4ea065d03c]::reference_casting::InvalidReferenceCasting as rustc_lint_defs[bc231ca48d0fadb9]::LintPass>::name
  43:     0x7ffac37ce4db - <rustc_lint[84f4ef4ea065d03c]::opaque_hidden_inferred_bound::OpaqueHiddenInferredBoundLint as rustc_errors[ae5992cadf1f8467]::diagnostic::DecorateLint<()>>::msg
  44:     0x7ffac37cf43e - <rustc_lint[84f4ef4ea065d03c]::opaque_hidden_inferred_bound::OpaqueHiddenInferredBoundLint as rustc_errors[ae5992cadf1f8467]::diagnostic::DecorateLint<()>>::msg
  45:     0x7ffac379631f - <rustc_lint[84f4ef4ea065d03c]::reference_casting::InvalidReferenceCasting as rustc_lint_defs[bc231ca48d0fadb9]::LintPass>::name
  46:     0x7ffac37ce4db - <rustc_lint[84f4ef4ea065d03c]::opaque_hidden_inferred_bound::OpaqueHiddenInferredBoundLint as rustc_errors[ae5992cadf1f8467]::diagnostic::DecorateLint<()>>::msg
  47:     0x7ffac37a0246 - <rustc_lint[84f4ef4ea065d03c]::early::RuntimeCombinedEarlyLintPass as rustc_lint[84f4ef4ea065d03c]::passes::EarlyLintPass>::exit_where_predicate
  48:     0x7ffac188234f - <rustc_lint[84f4ef4ea065d03c]::levels::LintLevelsBuilder<rustc_lint[84f4ef4ea065d03c]::levels::LintLevelQueryMap> as rustc_hir[3729d7b659a6834f]::intravisit::Visitor>::visit_field_def
  49:     0x7ffac18777a1 - <rustc_lint[84f4ef4ea065d03c]::builtin::UnexpectedCfgs>::get_lints
  50:     0x7ffac188ae97 - <rustc_lint[84f4ef4ea065d03c]::types::ImproperCTypesDefinitions as rustc_lint[84f4ef4ea065d03c]::passes::LateLintPass>::check_field_def
  51:     0x7ffac1882484 - rustc_lint[84f4ef4ea065d03c]::late::check_crate
  52:     0x7ffabebacdda - <rustc_interface[19250cdf588f99d8]::queries::Linker>::link
  53:     0x7ffabebcb672 - rustc_interface[19250cdf588f99d8]::passes::start_codegen
  54:     0x7ffabebc53e3 - rustc_interface[19250cdf588f99d8]::passes::start_codegen
  55:     0x7ffabebadc9d - <rustc_interface[19250cdf588f99d8]::queries::Linker>::link
  56:     0x7ffabebbca3e - rustc_interface[19250cdf588f99d8]::passes::analysis
  57:     0x7ffac15f3f6d - rustc_query_impl[96ff538c3ae89c53]::profiling_support::alloc_self_profile_query_strings
  58:     0x7ffac15ded79 - rustc_query_impl[96ff538c3ae89c53]::profiling_support::alloc_self_profile_query_strings
  59:     0x7ffac1622ab5 - rustc_query_impl[96ff538c3ae89c53]::profiling_support::alloc_self_profile_query_strings
  60:     0x7ffac165c51d - rustc_query_impl[96ff538c3ae89c53]::profiling_support::alloc_self_profile_query_strings
  61:     0x7ffac162910a - rustc_query_impl[96ff538c3ae89c53]::profiling_support::alloc_self_profile_query_strings
  62:     0x7ffabeb6c855 - rustc_driver_impl[c5bebaef4fa80e13]::main
  63:     0x7ffabeb7a523 - rustc_driver_impl[c5bebaef4fa80e13]::main
  64:     0x7ffabeb78f27 - rustc_driver_impl[c5bebaef4fa80e13]::main
  65:     0x7ffabeb798cf - rustc_driver_impl[c5bebaef4fa80e13]::main
  66:     0x7ffbab6ecd7c - std::sys::windows::thread::Thread::new::h7046930f55702517
  67:     0x7ffc07367344 - BaseThreadInitThunk
  68:     0x7ffc07e626b1 - RtlUserThreadStart

error: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust-clippy/issues/new?template=ice.yml

note: rustc 1.74.1 (a28077b28 2023-12-04) running on x86_64-pc-windows-msvc

note: compiler flags: --crate-type bin -C embed-bitcode=no -C debuginfo=2 -C incremental=[REDACTED]

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
#0 [analysis] running analysis passes on this crate
end of query stack
note: Clippy version: clippy 0.1.74 (a28077b2 2023-12-04)

error: could not compile `redacted_redacted` (bin "redacted_redacted")
  ```

  </p>
</details>

**Comment by Recurse-blip** [comment]
Duplicate of 
https://github.com/rust-lang/rust-clippy/issues/11652
