### ISSUE TITLE
ICE: `src/tools/clippy/clippy_lints/src/mut_reference.rs`

### ISSUE THREAD

**Issue by matthiaskrgr** [rust-lang/rust-clippy#12171]
### Summary

There was a rustc ice on master which has been fixed but the code still crashes a clippy lint.

````rust
fn main() {
    let s = [(); {
        let mut n = 113383;
        while n != 0 {}
        n
    }];
    s.doit();
}

````

### Version

```text
rustc 1.77.0-nightly (a34faab15 2024-01-18)
binary: rustc
commit-hash: a34faab155417481e191e8d467a5ea9bdd2174a0
commit-date: 2024-01-18
host: x86_64-unknown-linux-gnu
release: 1.77.0-nightly
LLVM version: 17.0.6
```

### Error output

<details><summary>Backtrace</summary>
  <p>

  ```
  warning: variable does not need to be mutable
 --> 116893.rs:3:13
  |
3 |         let mut n = 113383;
  |             ----^
  |             |
  |             help: remove this `mut`
  |
  = note: `#[warn(unused_mut)]` on by default

error: constant evaluation is taking a long time
 --> 116893.rs:4:9
  |
4 |         while n != 0 {}
  |         ^^^^^^^^^^^^^^^
  |
  = note: this lint makes sure the compiler doesn't get stuck due to infinite loops in const eval.
          If your compilation actually takes a long time, you can safely allow the lint.
help: the constant being evaluated
 --> 116893.rs:2:18
  |
2 |       let s = [(); {
  |  __________________^
3 | |         let mut n = 113383;
4 | |         while n != 0 {}
5 | |         n
6 | |     }];
  | |_____^
  = note: `#[deny(long_running_const_eval)]` on by default

error: variables in the condition are not mutated in the loop body
 --> 116893.rs:4:15
  |
4 |         while n != 0 {}
  |               ^^^^^^
  |
  = note: this may lead to an infinite or to a never running loop
  = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#while_immutable_condition
  = note: `#[deny(clippy::while_immutable_condition)]` on by default

thread 'rustc' panicked at src/tools/clippy/clippy_lints/src/mut_reference.rs:58:82:
called `Option::unwrap()` on a `None` value
stack backtrace:
   0:     0x7fea0a78c806 - std::backtrace_rs::backtrace::libunwind::trace::h0af8eded948dde3f
                               at /rustc/a34faab155417481e191e8d467a5ea9bdd2174a0/library/std/src/../../backtrace/src/backtrace/libunwind.rs:104:5
   1:     0x7fea0a78c806 - std::backtrace_rs::backtrace::trace_unsynchronized::h43db88bfa8cfdf45
                               at /rustc/a34faab155417481e191e8d467a5ea9bdd2174a0/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x7fea0a78c806 - std::sys_common::backtrace::_print_fmt::h98c1e02c08596fec
                               at /rustc/a34faab155417481e191e8d467a5ea9bdd2174a0/library/std/src/sys_common/backtrace.rs:68:5
   3:     0x7fea0a78c806 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h62f1285b2d9f2eaf
                               at /rustc/a34faab155417481e191e8d467a5ea9bdd2174a0/library/std/src/sys_common/backtrace.rs:44:22
   4:     0x7fea0a7dee00 - core::fmt::rt::Argument::fmt::hc75548042bc247c3
                               at /rustc/a34faab155417481e191e8d467a5ea9bdd2174a0/library/core/src/fmt/rt.rs:142:9
   5:     0x7fea0a7dee00 - core::fmt::write::h46c64fc4380c98af
                               at /rustc/a34faab155417481e191e8d467a5ea9bdd2174a0/library/core/src/fmt/mod.rs:1120:17
   6:     0x7fea0a78013f - std::io::Write::write_fmt::h62745a560057113b
                               at /rustc/a34faab155417481e191e8d467a5ea9bdd2174a0/library/std/src/io/mod.rs:1810:15
   7:     0x7fea0a78c5e4 - std::sys_common::backtrace::_print::h1c4e8b82e392af33
                               at /rustc/a34faab155417481e191e8d467a5ea9bdd2174a0/library/std/src/sys_common/backtrace.rs:47:5
   8:     0x7fea0a78c5e4 - std::sys_common::backtrace::print::h75c91bcdb1710b32
                               at /rustc/a34faab155417481e191e8d467a5ea9bdd2174a0/library/std/src/sys_common/backtrace.rs:34:9
   9:     0x7fea0a78f377 - std::panicking::default_hook::{{closure}}::h7fafba1c2dcbe48e
  10:     0x7fea0a78f0d9 - std::panicking::default_hook::he31bd4e041a2793d
                               at /rustc/a34faab155417481e191e8d467a5ea9bdd2174a0/library/std/src/panicking.rs:292:9
  11:     0x7fea0d57f04c - std[a2a80539a663bae8]::panicking::update_hook::<alloc[ec632870deb937d7]::boxed::Box<rustc_driver_impl[a3d2b25fbdff1229]::install_ice_hook::{closure#0}>>::{closure#0}
  12:     0x7fea0a78fac6 - <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call::hf4e280a7c54e2dd6
                               at /rustc/a34faab155417481e191e8d467a5ea9bdd2174a0/library/alloc/src/boxed.rs:2030:9
  13:     0x7fea0a78fac6 - std::panicking::rust_panic_with_hook::hc420117f28b74410
                               at /rustc/a34faab155417481e191e8d467a5ea9bdd2174a0/library/std/src/panicking.rs:785:13
  14:     0x7fea0a78f7d9 - std::panicking::begin_panic_handler::{{closure}}::hb95bbd685aaef4f2
                               at /rustc/a34faab155417481e191e8d467a5ea9bdd2174a0/library/std/src/panicking.rs:651:13
  15:     0x7fea0a78cd06 - std::sys_common::backtrace::__rust_end_short_backtrace::h6c8999206f4230b1
                               at /rustc/a34faab155417481e191e8d467a5ea9bdd2174a0/library/std/src/sys_common/backtrace.rs:171:18
  16:     0x7fea0a78f564 - rust_begin_unwind
                               at /rustc/a34faab155417481e191e8d467a5ea9bdd2174a0/library/std/src/panicking.rs:647:5
  17:     0x7fea0a7db505 - core::panicking::panic_fmt::hbc3ac8e5c12d9b39
                               at /rustc/a34faab155417481e191e8d467a5ea9bdd2174a0/library/core/src/panicking.rs:72:14
  18:     0x7fea0a7db5c3 - core::panicking::panic::h5bd98bd0a761072f
                               at /rustc/a34faab155417481e191e8d467a5ea9bdd2174a0/library/core/src/panicking.rs:144:5
  19:     0x7fea0a7db246 - core::option::unwrap_failed::hb9bf99c1c0e76934
                               at /rustc/a34faab155417481e191e8d467a5ea9bdd2174a0/library/core/src/option.rs:1978:5
  20:     0x56005f9641da - <clippy_lints[53b9b9e4ea5bac3f]::mut_reference::UnnecessaryMutPassed as rustc_lint[b419fe77595ef77a]::passes::LateLintPass>::check_expr
  21:     0x7fea0d8f9863 - <rustc_lint[b419fe77595ef77a]::late::LateContextAndPass<rustc_lint[b419fe77595ef77a]::late::RuntimeCombinedLateLintPass> as rustc_hir[ee970281777264b3]::intravisit::Visitor>::visit_expr::{closure#0}
  22:     0x7fea0d8f96f8 - <rustc_lint[b419fe77595ef77a]::late::LateContextAndPass<rustc_lint[b419fe77595ef77a]::late::RuntimeCombinedLateLintPass> as rustc_hir[ee970281777264b3]::intravisit::Visitor>::visit_expr
  23:     0x7fea0d8fa7ee - <rustc_lint[b419fe77595ef77a]::late::LateContextAndPass<rustc_lint[b419fe77595ef77a]::late::RuntimeCombinedLateLintPass> as rustc_hir[ee970281777264b3]::intravisit::Visitor>::visit_block
  24:     0x7fea0d8f9f32 - <rustc_lint[b419fe77595ef77a]::late::LateContextAndPass<rustc_lint[b419fe77595ef77a]::late::RuntimeCombinedLateLintPass> as rustc_hir[ee970281777264b3]::intravisit::Visitor>::visit_expr::{closure#0}
  25:     0x7fea0d8f96f8 - <rustc_lint[b419fe77595ef77a]::late::LateContextAndPass<rustc_lint[b419fe77595ef77a]::late::RuntimeCombinedLateLintPass> as rustc_hir[ee970281777264b3]::intravisit::Visitor>::visit_expr
  26:     0x7fea0d8f7fca - <rustc_lint[b419fe77595ef77a]::late::LateContextAndPass<rustc_lint[b419fe77595ef77a]::late::RuntimeCombinedLateLintPass> as rustc_hir[ee970281777264b3]::intravisit::Visitor>::visit_nested_body
  27:     0x7fea0d8fa2c4 - <rustc_lint[b419fe77595ef77a]::late::LateContextAndPass<rustc_lint[b419fe77595ef77a]::late::RuntimeCombinedLateLintPass> as rustc_hir[ee970281777264b3]::intravisit::Visitor>::visit_fn
  28:     0x7fea0d8f880f - <rustc_lint[b419fe77595ef77a]::late::LateContextAndPass<rustc_lint[b419fe77595ef77a]::late::RuntimeCombinedLateLintPass> as rustc_hir[ee970281777264b3]::intravisit::Visitor>::visit_item
  29:     0x7fea0d8fa5fa - <rustc_lint[b419fe77595ef77a]::late::LateContextAndPass<rustc_lint[b419fe77595ef77a]::late::RuntimeCombinedLateLintPass> as rustc_hir[ee970281777264b3]::intravisit::Visitor>::visit_mod
  30:     0x7fea0f3be627 - rustc_lint[b419fe77595ef77a]::late::check_crate::{closure#0}
  31:     0x7fea0f3be875 - rustc_lint[b419fe77595ef77a]::late::check_crate
  32:     0x7fea0f1cd52a - rustc_interface[513bd0e5fe475c5b]::passes::analysis
  33:     0x7fea0f1cc21f - rustc_query_impl[ec4c7e4d40d65de2]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[ec4c7e4d40d65de2]::query_impl::analysis::dynamic_query::{closure#2}::{closure#0}, rustc_middle[1e0802606e48f8ce]::query::erase::Erased<[u8; 1usize]>>
  34:     0x7fea0f7d6cb2 - rustc_query_system[26dbb27a14114128]::query::plumbing::try_execute_query::<rustc_query_impl[ec4c7e4d40d65de2]::DynamicConfig<rustc_query_system[26dbb27a14114128]::query::caches::SingleCache<rustc_middle[1e0802606e48f8ce]::query::erase::Erased<[u8; 1usize]>>, false, false, false>, rustc_query_impl[ec4c7e4d40d65de2]::plumbing::QueryCtxt, false>
  35:     0x7fea0f7d6ab9 - rustc_query_impl[ec4c7e4d40d65de2]::query_impl::analysis::get_query_non_incr::__rust_end_short_backtrace
  36:     0x7fea0f5773f3 - rustc_interface[513bd0e5fe475c5b]::interface::run_compiler::<core[8eb7b864ab6fd61d]::result::Result<(), rustc_span[a83072b458b82ea]::ErrorGuaranteed>, rustc_driver_impl[a3d2b25fbdff1229]::run_compiler::{closure#0}>::{closure#0}
  37:     0x7fea0f7de790 - std[a2a80539a663bae8]::sys_common::backtrace::__rust_begin_short_backtrace::<rustc_interface[513bd0e5fe475c5b]::util::run_in_thread_with_globals<rustc_interface[513bd0e5fe475c5b]::util::run_in_thread_pool_with_globals<rustc_interface[513bd0e5fe475c5b]::interface::run_compiler<core[8eb7b864ab6fd61d]::result::Result<(), rustc_span[a83072b458b82ea]::ErrorGuaranteed>, rustc_driver_impl[a3d2b25fbdff1229]::run_compiler::{closure#0}>::{closure#0}, core[8eb7b864ab6fd61d]::result::Result<(), rustc_span[a83072b458b82ea]::ErrorGuaranteed>>::{closure#0}, core[8eb7b864ab6fd61d]::result::Result<(), rustc_span[a83072b458b82ea]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[8eb7b864ab6fd61d]::result::Result<(), rustc_span[a83072b458b82ea]::ErrorGuaranteed>>
  38:     0x7fea0f7de5bf - <<std[a2a80539a663bae8]::thread::Builder>::spawn_unchecked_<rustc_interface[513bd0e5fe475c5b]::util::run_in_thread_with_globals<rustc_interface[513bd0e5fe475c5b]::util::run_in_thread_pool_with_globals<rustc_interface[513bd0e5fe475c5b]::interface::run_compiler<core[8eb7b864ab6fd61d]::result::Result<(), rustc_span[a83072b458b82ea]::ErrorGuaranteed>, rustc_driver_impl[a3d2b25fbdff1229]::run_compiler::{closure#0}>::{closure#0}, core[8eb7b864ab6fd61d]::result::Result<(), rustc_span[a83072b458b82ea]::ErrorGuaranteed>>::{closure#0}, core[8eb7b864ab6fd61d]::result::Result<(), rustc_span[a83072b458b82ea]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[8eb7b864ab6fd61d]::result::Result<(), rustc_span[a83072b458b82ea]::ErrorGuaranteed>>::{closure#1} as core[8eb7b864ab6fd61d]::ops::function::FnOnce<()>>::call_once::{shim:vtable#0}
  39:     0x7fea0a7993b5 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h9d7160a066d7145e
                               at /rustc/a34faab155417481e191e8d467a5ea9bdd2174a0/library/alloc/src/boxed.rs:2016:9
  40:     0x7fea0a7993b5 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h50e4b361bb2f336b
                               at /rustc/a34faab155417481e191e8d467a5ea9bdd2174a0/library/alloc/src/boxed.rs:2016:9
  41:     0x7fea0a7993b5 - std::sys::pal::unix::thread::Thread::new::thread_start::h8286a212c368b932
                               at /rustc/a34faab155417481e191e8d467a5ea9bdd2174a0/library/std/src/sys/pal/unix/thread.rs:108:17
  42:     0x7fea0a4739eb - <unknown>
  43:     0x7fea0a4f77cc - <unknown>
  44:                0x0 - <unknown>

error: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust-clippy/issues/new?template=ice.yml

note: please attach the file at `/tmp/im/rustc-ice-2024-01-18T17_20_25-1592686.txt` to your bug report

query stack during panic:
#0 [analysis] running analysis passes on this crate
end of query stack
note: Clippy version: clippy 0.1.77 (a34faab 2024-01-18)

error: aborting due to 2 previous errors; 1 warning emitted
  ```

  </p>
</details>

**Comment by MolotovCherry** [comment]
I also encountered this ICE during my dev. This report is probably unneeded, but I'll send my ICE report anyways.

rustc version
```
cargo 1.78.0-nightly (194a60b29 2024-02-21)
release: 1.78.0-nightly
commit-hash: 194a60b2952bd5d12ba15dd2577a97eed7d3c587
commit-date: 2024-02-21
host: x86_64-pc-windows-msvc
libgit2: 1.7.2 (sys:0.18.2 vendored)
libcurl: 8.6.0-DEV (sys:0.4.71+curl-8.6.0 vendored ssl:Schannel)
os: Windows 10.0.22631 (Windows 11 Professional) [64-bit]
```

<details>
  <summary>ICE 🧊 </summary>

```
thread 'rustc' panicked at src\tools\clippy\clippy_lints\src\mut_reference.rs:58:82:
called `Option::unwrap()` on a `None` value
stack backtrace:
   0:     0x7ffee915d484 - std::backtrace::Backtrace::force_capture::h6c31e9cc248faf9a
   1:     0x7ffee915d3e4 - std::backtrace::Backtrace::force_capture::h6c31e9cc248faf9a
   2:     0x7ffed9ca05db - <tracing_subscriber[88b4fe7e20ce20ff]::util::TryInitError as core[f144f1f7cd8369f9]::fmt::Display>::fmt
   3:     0x7ffee9176a13 - std::panicking::rust_panic_with_hook::h2b50eaa30d99b6ac
   4:     0x7ffee917687b - <std::panicking::begin_panic_handler::StaticStrPayload as core::panic::PanicPayload>::take_box::h6e0528fbe4310117
   5:     0x7ffee9173bf9 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h600d07f2102760cc
   6:     0x7ffee9176576 - rust_begin_unwind
   7:     0x7ffee91cba47 - core::panicking::panic_fmt::h7003aef5c8a625be
   8:     0x7ffee91cbb22 - core::panicking::panic::hbcd867493ef26b29
   9:     0x7ffee91cb9e8 - core::option::unwrap_failed::h0992080e9c0bf47e
  10:     0x7ff68903b7df - <unknown>
  11:     0x7ffeda964e3a - <rustc_lint[c95c2594ac7be174]::deref_into_dyn_supertrait::DerefIntoDynSupertrait as rustc_lint[c95c2594ac7be174]::passes::LateLintPass>::check_item
  12:     0x7ffeda965421 - <rustc_lint[c95c2594ac7be174]::deref_into_dyn_supertrait::DerefIntoDynSupertrait as rustc_lint[c95c2594ac7be174]::passes::LateLintPass>::check_item
  13:     0x7ffeda964e4e - <rustc_lint[c95c2594ac7be174]::deref_into_dyn_supertrait::DerefIntoDynSupertrait as rustc_lint[c95c2594ac7be174]::passes::LateLintPass>::check_item
  14:     0x7ffeda965421 - <rustc_lint[c95c2594ac7be174]::deref_into_dyn_supertrait::DerefIntoDynSupertrait as rustc_lint[c95c2594ac7be174]::passes::LateLintPass>::check_item
  15:     0x7ffeda9aa136 - <rustc_lint[c95c2594ac7be174]::lints::BuiltinDerefNullptr as rustc_errors[f4920d02a698aaa8]::diagnostic::DecorateLint<()>>::decorate_lint
  16:     0x7ffeda964e4e - <rustc_lint[c95c2594ac7be174]::deref_into_dyn_supertrait::DerefIntoDynSupertrait as rustc_lint[c95c2594ac7be174]::passes::LateLintPass>::check_item
  17:     0x7ffeda965421 - <rustc_lint[c95c2594ac7be174]::deref_into_dyn_supertrait::DerefIntoDynSupertrait as rustc_lint[c95c2594ac7be174]::passes::LateLintPass>::check_item
  18:     0x7ffeda965ce7 - <rustc_lint[c95c2594ac7be174]::deref_into_dyn_supertrait::DerefIntoDynSupertrait as rustc_lint[c95c2594ac7be174]::passes::LateLintPass>::check_item
  19:     0x7ffeda964e4e - <rustc_lint[c95c2594ac7be174]::deref_into_dyn_supertrait::DerefIntoDynSupertrait as rustc_lint[c95c2594ac7be174]::passes::LateLintPass>::check_item
  20:     0x7ffeda965421 - <rustc_lint[c95c2594ac7be174]::deref_into_dyn_supertrait::DerefIntoDynSupertrait as rustc_lint[c95c2594ac7be174]::passes::LateLintPass>::check_item
  21:     0x7ffeda96501f - <rustc_lint[c95c2594ac7be174]::deref_into_dyn_supertrait::DerefIntoDynSupertrait as rustc_lint[c95c2594ac7be174]::passes::LateLintPass>::check_item
  22:     0x7ffeda96568d - <rustc_lint[c95c2594ac7be174]::deref_into_dyn_supertrait::DerefIntoDynSupertrait as rustc_lint[c95c2594ac7be174]::passes::LateLintPass>::check_item
  23:     0x7ffeda9a7d26 - <rustc_lint[c95c2594ac7be174]::lints::BuiltinDerefNullptr as rustc_errors[f4920d02a698aaa8]::diagnostic::DecorateLint<()>>::decorate_lint
  24:     0x7ffeda964354 - <rustc_lint[c95c2594ac7be174]::levels::LintStackIndex as core[f144f1f7cd8369f9]::fmt::Debug>::fmt
  25:     0x7ffeda9aa699 - <rustc_lint[c95c2594ac7be174]::lints::BuiltinDerefNullptr as rustc_errors[f4920d02a698aaa8]::diagnostic::DecorateLint<()>>::decorate_lint
  26:     0x7ffeda964138 - <rustc_lint[c95c2594ac7be174]::levels::LintStackIndex as core[f144f1f7cd8369f9]::fmt::Debug>::fmt
  27:     0x7ffeda9a975b - <rustc_lint[c95c2594ac7be174]::lints::BuiltinDerefNullptr as rustc_errors[f4920d02a698aaa8]::diagnostic::DecorateLint<()>>::decorate_lint
  28:     0x7ffeda9aa7dd - <rustc_lint[c95c2594ac7be174]::lints::BuiltinDerefNullptr as rustc_errors[f4920d02a698aaa8]::diagnostic::DecorateLint<()>>::decorate_lint
  29:     0x7ffeda964138 - <rustc_lint[c95c2594ac7be174]::levels::LintStackIndex as core[f144f1f7cd8369f9]::fmt::Debug>::fmt
  30:     0x7ffeda9a975b - <rustc_lint[c95c2594ac7be174]::lints::BuiltinDerefNullptr as rustc_errors[f4920d02a698aaa8]::diagnostic::DecorateLint<()>>::decorate_lint
  31:     0x7ffeda93bf96 - <rustc_lint[c95c2594ac7be174]::BuiltinCombinedModuleLateLintPass as rustc_lint_defs[f518f90adf3fcbe5]::LintPass>::name
  32:     0x7ffed88285c4 - <rustc_lint[c95c2594ac7be174]::async_fn_in_trait::AsyncFnInTrait as rustc_lint[c95c2594ac7be174]::passes::LateLintPass>::check_trait_item
  33:     0x7ffed881c7d1 - <rustc_lint[c95c2594ac7be174]::unused::UnusedBraces as rustc_lint[c95c2594ac7be174]::unused::UnusedDelimLint>::check_unused_delims_expr
  34:     0x7ffed882b287 - rustc_lint[c95c2594ac7be174]::late::check_crate
  35:     0x7ffed881137d - <rustc_lint[c95c2594ac7be174]::BuiltinCombinedModuleLateLintPass as rustc_lint[c95c2594ac7be174]::passes::LateLintPass>::check_variant
  36:     0x7ffed8828716 - rustc_lint[c95c2594ac7be174]::late::check_crate
  37:     0x7ffed5b2f821 - rustc_interface[838f679e91249f38]::interface::parse_check_cfg
  38:     0x7ffed5b2bd23 - rustc_interface[838f679e91249f38]::interface::parse_check_cfg
  39:     0x7ffed5b06919 - <rustc_interface[838f679e91249f38]::queries::Linker>::link
  40:     0x7ffed5b2ca42 - rustc_interface[838f679e91249f38]::interface::parse_check_cfg
  41:     0x7ffed5b3138c - rustc_interface[838f679e91249f38]::interface::parse_check_cfg
  42:     0x7ffed8b99761 - rustc_interface[838f679e91249f38]::passes::analysis
  43:     0x7ffed872675d - <rustc_query_impl[2766e1f47c281103]::plumbing::QueryCtxt as rustc_query_system[bb07ab768600e4a1]::query::QueryContext>::load_side_effects
  44:     0x7ffed876a079 - <rustc_query_impl[2766e1f47c281103]::plumbing::QueryCtxt as rustc_query_system[bb07ab768600e4a1]::query::QueryContext>::load_side_effects
  45:     0x7ffed87299e8 - <rustc_query_impl[2766e1f47c281103]::plumbing::QueryCtxt as rustc_query_system[bb07ab768600e4a1]::query::QueryContext>::load_side_effects
  46:     0x7ffed878ecdc - <windows[30a834fef61ab110]::Win32::Globalization::FONTSIGNATURE as core[f144f1f7cd8369f9]::cmp::PartialEq>::eq
  47:     0x7ffed873f297 - <rustc_query_impl[2766e1f47c281103]::plumbing::QueryCtxt as rustc_query_system[bb07ab768600e4a1]::query::QueryContext>::load_side_effects
  48:     0x7ffed5ae1e3d - rustc_driver_impl[539bfd6e9ddc88e5]::args::arg_expand_all
  49:     0x7ffed5ab1a1e - rustc_driver_impl[539bfd6e9ddc88e5]::args::arg_expand_all
  50:     0x7ffed5addcea - rustc_driver_impl[539bfd6e9ddc88e5]::args::arg_expand_all
  51:     0x7ffed5adf7ea - rustc_driver_impl[539bfd6e9ddc88e5]::args::arg_expand_all
  52:     0x7ffed5aed24f - <rustc_middle[3ad24d1b6f9f78ce]::ty::SymbolName as core[f144f1f7cd8369f9]::fmt::Debug>::fmt
  53:     0x7ffed5ae89a7 - rustc_driver_impl[539bfd6e9ddc88e5]::args::arg_expand_all
  54:     0x7ffee918709c - std::sys::pal::windows::thread::Thread::new::hb9ec5dcdbdaa66dc
  55:     0x7fffee69257d - BaseThreadInitThunk
  56:     0x7fffef30aa58 - RtlUserThreadStart


rustc version: 1.78.0-nightly (0ecbd0605 2024-02-25)
platform: x86_64-pc-windows-msvc

query stack during panic:
#0 [analysis] running analysis passes on this crate
end of query stack
```
</summary>

**Comment by Jarcho** [comment]
Why are lints even running here? Const eval fails which causes an incomplete array type.

**Comment by matthiaskrgr** [comment]
triage: still crashing 🧊
