### ISSUE TITLE
ICE in `NEEDLESS_RETURN` when building lint span

### ISSUE THREAD

**Issue by sunowfox** [rust-lang/rust-clippy#12328]
### Summary

The ICE happens in `check_final_expr`, according to the back trace, most likely in `emit_return_lint`. It looks like building the span ICEs:

```
thread 'rustc' panicked at compiler/rustc_span/src/lib.rs:1794:17:
assertion failed: bpos.to_u32() >= mbc.pos.to_u32() + mbc.bytes as u32
```

### Version

```text
rustc 1.75.0 (82e1608df 2023-12-21)
binary: rustc
commit-hash: 82e1608dfa6e0b5569232559e3d385fea5a93112
commit-date: 2023-12-21
host: x86_64-unknown-linux-gnu
release: 1.75.0
LLVM version: 17.0.6
```

### Error output

<details><summary>Backtrace</summary>
  <p>

```
root@sunow-ubuntu:/home/sunow/EMS/ems_gw# RUST_BACKTRACE=1 cargo clippy
    Checking ems_gw v0.1.0 (/home/sunow/EMS/ems_gw)
thread 'rustc' panicked at compiler/rustc_span/src/lib.rs:1794:17:
assertion failed: bpos.to_u32() >= mbc.pos.to_u32() + mbc.bytes as u32
stack backtrace:
   0:     0x7fc8fb6b762c - std::backtrace_rs::backtrace::libunwind::trace::ha637c64ce894333a
                               at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/../../backtrace/src/backtrace/libunwind.rs:104:5
   1:     0x7fc8fb6b762c - std::backtrace_rs::backtrace::trace_unsynchronized::h47f62dea28e0c88d
                               at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x7fc8fb6b762c - std::sys_common::backtrace::_print_fmt::h9eef0abe20ede486
                               at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/sys_common/backtrace.rs:67:5
   3:     0x7fc8fb6b762c - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::hed7f999df88cc644
                               at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/sys_common/backtrace.rs:44:22
   4:     0x7fc8fb70a630 - core::fmt::rt::Argument::fmt::h1539a9308b8d058d
                               at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/core/src/fmt/rt.rs:142:9
   5:     0x7fc8fb70a630 - core::fmt::write::h3a39390d8560d9c9
                               at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/core/src/fmt/mod.rs:1120:17
   6:     0x7fc8fb6ab54f - std::io::Write::write_fmt::h5fc9997dfe05f882
                               at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/io/mod.rs:1762:15
   7:     0x7fc8fb6b7414 - std::sys_common::backtrace::_print::h894006fb5c6f3d45
                               at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/sys_common/backtrace.rs:47:5
   8:     0x7fc8fb6b7414 - std::sys_common::backtrace::print::h23a2d212c6fff936
                               at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/sys_common/backtrace.rs:34:9
   9:     0x7fc8fb6ba0a7 - std::panicking::default_hook::{{closure}}::h8a1d2ee00185001a
  10:     0x7fc8fb6b9e0f - std::panicking::default_hook::h6038f2eba384e475
                               at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/panicking.rs:292:9
  11:     0x7fc8f8537190 - std[409886f6357001f0]::panicking::update_hook::<alloc[c1b021ad36e35877]::boxed::Box<rustc_driver_impl[7d23c5715ff089db]::install_ice_hook::{closure#0}>>::{closure#0}
  12:     0x7fc8fb6ba7e8 - <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call::h1f8f335eaa9cfaee
                               at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/alloc/src/boxed.rs:2021:9
  13:     0x7fc8fb6ba7e8 - std::panicking::rust_panic_with_hook::h2b5517d590cab22e
                               at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/panicking.rs:783:13
  14:     0x7fc8fb6ba509 - std::panicking::begin_panic_handler::{{closure}}::h233112c06e0ef43e
                               at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/panicking.rs:649:13
  15:     0x7fc8fb6b7af6 - std::sys_common::backtrace::__rust_end_short_backtrace::h6e893f24d7ebbff8
                               at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/sys_common/backtrace.rs:170:18
  16:     0x7fc8fb6ba2a2 - rust_begin_unwind
                               at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/panicking.rs:645:5
  17:     0x7fc8fb706d15 - core::panicking::panic_fmt::hbf0e066aabfa482c
                               at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/core/src/panicking.rs:72:14
  18:     0x7fc8fb706db3 - core::panicking::panic::h195fc2a96298d4c3
                               at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/core/src/panicking.rs:127:5
  19:     0x7fc8f9fa8af4 - <rustc_span[3d5dc97049ad8d50]::source_map::SourceMap>::lookup_char_pos
  20:     0x7fc8fa644b24 - <rustc_errors[1a9aa55769204d1a]::emitter::FileWithAnnotatedLines>::collect_annotations
  21:     0x7fc8fa7f796b - <rustc_errors[1a9aa55769204d1a]::emitter::EmitterWriter>::emit_message_default::{closure#0}
  22:     0x7fc8fa3aade5 - <rustc_errors[1a9aa55769204d1a]::emitter::EmitterWriter>::emit_messages_default
  23:     0x7fc8fa539101 - <rustc_errors[1a9aa55769204d1a]::emitter::EmitterWriter as rustc_errors[1a9aa55769204d1a]::emitter::Emitter>::emit_diagnostic
  24:     0x7fc8fa642abd - <rustc_errors[1a9aa55769204d1a]::json::Diagnostic>::from_errors_diagnostic
  25:     0x7fc8fa641f2a - <rustc_errors[1a9aa55769204d1a]::json::JsonEmitter as rustc_errors[1a9aa55769204d1a]::emitter::Emitter>::emit_diagnostic
  26:     0x7fc8fa6a6742 - <rustc_errors[1a9aa55769204d1a]::HandlerInner>::emit_diagnostic::{closure#2}
  27:     0x7fc8fa6a4ca2 - rustc_interface[fbb0cb4be6c0ba34]::callbacks::track_diagnostic
  28:     0x7fc8fa6a3c0c - <rustc_errors[1a9aa55769204d1a]::HandlerInner>::emit_diagnostic
  29:     0x7fc8fa8130ec - <() as rustc_errors[1a9aa55769204d1a]::diagnostic_builder::EmissionGuarantee>::diagnostic_builder_emit_producing_guarantee
  30:     0x55b0ca87ae39 - rustc_middle[aca4860da4e5a967]::lint::struct_lint_level::struct_lint_level_impl::<alloc[c1b021ad36e35877]::string::String>
  31:     0x55b0caa6e265 - clippy_lints[949beba6972a7ba0]::returns::check_final_expr
  32:     0x55b0caa6d81b - clippy_lints[949beba6972a7ba0]::returns::check_block_return
  33:     0x55b0caa6dc91 - clippy_lints[949beba6972a7ba0]::returns::check_final_expr
  34:     0x55b0caa6dff3 - clippy_lints[949beba6972a7ba0]::returns::check_final_expr
  35:     0x55b0caa6d81b - clippy_lints[949beba6972a7ba0]::returns::check_block_return
  36:     0x55b0caa6d793 - <clippy_lints[949beba6972a7ba0]::returns::Return as rustc_lint[cff927c46d08ae21]::passes::LateLintPass>::check_fn
  37:     0x7fc8f88ab8c5 - <rustc_lint[cff927c46d08ae21]::late::LateContextAndPass<rustc_lint[cff927c46d08ae21]::late::RuntimeCombinedLateLintPass> as rustc_hir[3ec930a01a564d4c]::intravisit::Visitor>::visit_fn
  38:     0x7fc8f88aab39 - <rustc_lint[cff927c46d08ae21]::late::LateContextAndPass<rustc_lint[cff927c46d08ae21]::late::RuntimeCombinedLateLintPass> as rustc_hir[3ec930a01a564d4c]::intravisit::Visitor>::visit_item
  39:     0x7fc8f88abc6a - <rustc_lint[cff927c46d08ae21]::late::LateContextAndPass<rustc_lint[cff927c46d08ae21]::late::RuntimeCombinedLateLintPass> as rustc_hir[3ec930a01a564d4c]::intravisit::Visitor>::visit_mod
  40:     0x7fc8f88aa001 - <rustc_lint[cff927c46d08ae21]::late::LateContextAndPass<rustc_lint[cff927c46d08ae21]::late::RuntimeCombinedLateLintPass> as rustc_hir[3ec930a01a564d4c]::intravisit::Visitor>::visit_item
  41:     0x7fc8f88abc6a - <rustc_lint[cff927c46d08ae21]::late::LateContextAndPass<rustc_lint[cff927c46d08ae21]::late::RuntimeCombinedLateLintPass> as rustc_hir[3ec930a01a564d4c]::intravisit::Visitor>::visit_mod
  42:     0x7fc8fa171877 - rustc_lint[cff927c46d08ae21]::late::check_crate
  43:     0x7fc8f9e8e5fa - rustc_interface[fbb0cb4be6c0ba34]::passes::analysis
  44:     0x7fc8f9e8d575 - rustc_query_impl[664ae873a521fa7c]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[664ae873a521fa7c]::query_impl::analysis::dynamic_query::{closure#2}::{closure#0}, rustc_middle[aca4860da4e5a967]::query::erase::Erased<[u8; 1usize]>>
  45:     0x7fc8fa324844 - rustc_query_system[b5dcdc06a735d5f1]::query::plumbing::try_execute_query::<rustc_query_impl[664ae873a521fa7c]::DynamicConfig<rustc_query_system[b5dcdc06a735d5f1]::query::caches::SingleCache<rustc_middle[aca4860da4e5a967]::query::erase::Erased<[u8; 1usize]>>, false, false, false>, rustc_query_impl[664ae873a521fa7c]::plumbing::QueryCtxt, true>
  46:     0x7fc8fa324520 - rustc_query_impl[664ae873a521fa7c]::query_impl::analysis::get_query_incr::__rust_end_short_backtrace
  47:     0x7fc8fa607021 - rustc_interface[fbb0cb4be6c0ba34]::interface::run_compiler::<core[21cdcf8e8af4c2d9]::result::Result<(), rustc_span[3d5dc97049ad8d50]::ErrorGuaranteed>, rustc_driver_impl[7d23c5715ff089db]::run_compiler::{closure#1}>::{closure#0}
  48:     0x7fc8fa60215b - std[409886f6357001f0]::sys_common::backtrace::__rust_begin_short_backtrace::<rustc_interface[fbb0cb4be6c0ba34]::util::run_in_thread_with_globals<rustc_interface[fbb0cb4be6c0ba34]::interface::run_compiler<core[21cdcf8e8af4c2d9]::result::Result<(), rustc_span[3d5dc97049ad8d50]::ErrorGuaranteed>, rustc_driver_impl[7d23c5715ff089db]::run_compiler::{closure#1}>::{closure#0}, core[21cdcf8e8af4c2d9]::result::Result<(), rustc_span[3d5dc97049ad8d50]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[21cdcf8e8af4c2d9]::result::Result<(), rustc_span[3d5dc97049ad8d50]::ErrorGuaranteed>>
  49:     0x7fc8fa601fb3 - <<std[409886f6357001f0]::thread::Builder>::spawn_unchecked_<rustc_interface[fbb0cb4be6c0ba34]::util::run_in_thread_with_globals<rustc_interface[fbb0cb4be6c0ba34]::interface::run_compiler<core[21cdcf8e8af4c2d9]::result::Result<(), rustc_span[3d5dc97049ad8d50]::ErrorGuaranteed>, rustc_driver_impl[7d23c5715ff089db]::run_compiler::{closure#1}>::{closure#0}, core[21cdcf8e8af4c2d9]::result::Result<(), rustc_span[3d5dc97049ad8d50]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[21cdcf8e8af4c2d9]::result::Result<(), rustc_span[3d5dc97049ad8d50]::ErrorGuaranteed>>::{closure#1} as core[21cdcf8e8af4c2d9]::ops::function::FnOnce<()>>::call_once::{shim:vtable#0}
  50:     0x7fc8fb6c46a5 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::hc7eafaff61e32df9
                               at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/alloc/src/boxed.rs:2007:9
  51:     0x7fc8fb6c46a5 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h6ba4a5de48dd2304
                               at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/alloc/src/boxed.rs:2007:9
  52:     0x7fc8fb6c46a5 - std::sys::unix::thread::Thread::new::thread_start::he469335aef763e45
                               at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/sys/unix/thread.rs:108:17
  53:     0x7fc8f568f6ba - start_thread
                               at ./nptl/pthread_create.c:444:8
  54:     0x7fc8f571e120 - __GI___clone3
                               at ./misc/../sysdeps/unix/sysv/linux/x86_64/clone3.S:81
  55:                0x0 - <unknown>

error: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust-clippy/issues/new?template=ice.yml

note: rustc 1.75.0 (82e1608df 2023-12-21) running on x86_64-unknown-linux-gnu

note: compiler flags: --crate-type lib -C embed-bitcode=no -C debuginfo=2 -C incremental=[REDACTED]

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
#0 [analysis] running analysis passes on this crate
end of query stack
note: Clippy version: clippy 0.1.75 (82e1608 2023-12-21)


error: could not compile `ems_gw` (lib)
```

  </p>
</details>

**Comment by sanxiyn** [comment]
How does one reproduce this?

**Comment by flip1995** [comment]
The ICE seems to happen on the `ems_gw` crate, which is closed source AFAICT. @sunowfox would need to provide a minimal reproducer or give access to that crate.

**Comment by y21** [comment]
A fix for another issue that looked identical to this one (and what I assume is the same bug) should be on nightly now. There is no reproducer here so it's just speculation that this is fixed.

If possible, @sunowfox can you verify that this is indeed fixed on latest nightly?
