### ISSUE TITLE
ice on glacier 28189.rs 

### ISSUE THREAD

**Issue by matthiaskrgr** [rust-lang/rust-clippy#4631]
clippy crashes on glacier ./fixed/28189.rs
````rustc
struct S<T>(T) where [T; (||{}, 1).1]: Copy;
fn main() {}
````

````
warning: struct is never constructed: `S`
 --> ./fixed/28189.rs:1:1
  |
1 | struct S<T>(T) where [T; (||{}, 1).1]: Copy;
  | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  |
  = note: `#[warn(dead_code)]` on by default

error: internal compiler error: src/librustc/ty/context.rs:552: node_type: no type for node `expr 1 (hir_id=HirId { owner: DefIndex(12), local_id: 12 })`

thread 'rustc' panicked at 'Box<Any>', src/librustc_errors/lib.rs:915:9
stack backtrace:
   0: backtrace::backtrace::libunwind::trace
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.37/src/backtrace/libunwind.rs:88
   1: backtrace::backtrace::trace_unsynchronized
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.37/src/backtrace/mod.rs:66
   2: std::sys_common::backtrace::_print_fmt
             at src/libstd/sys_common/backtrace.rs:76
   3: <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt
             at src/libstd/sys_common/backtrace.rs:60
   4: core::fmt::write
             at src/libcore/fmt/mod.rs:1028
   5: std::io::Write::write_fmt
             at src/libstd/io/mod.rs:1412
   6: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:64
   7: std::sys_common::backtrace::print
             at src/libstd/sys_common/backtrace.rs:49
   8: std::panicking::default_hook::{{closure}}
             at src/libstd/panicking.rs:196
   9: std::panicking::default_hook
             at src/libstd/panicking.rs:210
  10: rustc_driver::report_ice
  11: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:477
  12: std::panicking::begin_panic
  13: rustc_errors::HandlerInner::bug
  14: rustc_errors::Handler::bug
  15: rustc::util::bug::opt_span_bug_fmt::{{closure}}
  16: rustc::ty::context::tls::with_opt::{{closure}}
  17: rustc::ty::context::tls::with_context_opt
  18: rustc::ty::context::tls::with_opt
  19: rustc::util::bug::opt_span_bug_fmt
  20: rustc::util::bug::bug_fmt
  21: rustc::ty::context::TypeckTables::node_type::{{closure}}
  22: rustc::ty::context::TypeckTables::expr_ty
  23: clippy_lints::consts::ConstEvalLateContext::expr
  24: clippy_lints::consts::constant_simple
  25: clippy_lints::utils::hir_utils::SpanlessHash::hash_expr
  26: clippy_lints::utils::hir_utils::SpanlessHash::hash_expr
  27: clippy_lints::utils::hir_utils::SpanlessHash::hash_expr
  28: <clippy_lints::trait_bounds::TraitBounds as rustc::lint::LateLintPass>::check_generics
  29: <rustc::lint::context::LateLintPassObjects as rustc::lint::LateLintPass>::check_generics
  30: rustc::hir::intravisit::walk_item
  31: rustc::hir::intravisit::Visitor::visit_nested_item
  32: rustc::hir::intravisit::walk_crate
  33: rustc::lint::context::late_lint_pass_crate
  34: rustc::lint::context::late_lint_crate
  35: rustc::util::common::time
  36: rustc::util::common::time
  37: __rust_maybe_catch_panic
             at src/libpanic_unwind/lib.rs:80
  38: <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
  39: __rust_maybe_catch_panic
             at src/libpanic_unwind/lib.rs:80
  40: rustc_interface::passes::analysis::{{closure}}
  41: rustc::util::common::time
  42: rustc_interface::passes::analysis
  43: rustc::ty::query::__query_compute::analysis
  44: rustc::dep_graph::graph::DepGraph::with_task_impl
  45: rustc::ty::query::plumbing::<impl rustc::ty::context::TyCtxt>::get_query
  46: rustc_interface::passes::BoxedGlobalCtxt::access::{{closure}}
  47: rustc_interface::passes::create_global_ctxt::{{closure}}
  48: rustc_interface::interface::run_compiler_in_existing_thread_pool
  49: std::thread::local::LocalKey<T>::with
  50: syntax::with_globals
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports

note: rustc 1.40.0-nightly (032a53a06 2019-10-03) running on x86_64-unknown-linux-gnu

query stack during panic:
#0 [analysis] running analysis passes on this crate
end of query stack
error: aborting due to previous error
````

**Comment by flip1995** [comment]
Should've been fixed with #4590, but didn't hit nightly yet. Once the rustup #4628 is done and a clippyup in rustc is done, this should be fixed.
