### ISSUE TITLE
Clippy results in an ICE after adding `dyn`

### ISSUE THREAD

**Issue by Rantanen** [rust-lang/rust-clippy#4699]
Clippy version: 0.0.212 (e979eb4c 2019-10-17)

Turning the `ComRc<IIntercomInterfaceVariant>` into `ComRc<dyn IIntercomInterfaceVariant>` in
https://github.com/Rantanen/intercom/blob/c65bbe74c9d5af1e43822cbdc800eafb575eb4b3/intercom/src/typelib/mod.rs#L125 results in an ICE.

The `#[com_interface]` proc macro could be related to this. That proc macro expands to couple of function definitions, structs with function pointers, etc.

I didn't see direct connection to the recent (fixed) ICEs that Github is displaying in the possibly related issues.

```
error: internal compiler error: src\librustc\ty\context.rs:552: node_type: no type for node `type IIntercomInterfaceVariant (hir_id=HirId { owner: DefIndex(2462), local_id: 579 })`

thread 'rustc' panicked at 'Box<Any>', src\librustc_errors\lib.rs:925:9
stack backtrace:
   0: <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt
   1: core::fmt::write
   2: <std::io::IoSliceMut as core::fmt::Debug>::fmt
   3: std::panicking::take_hook
   4: std::panicking::take_hook
   5: rustc_driver::report_ice
   6: std::panicking::rust_panic_with_hook
   7: <rustc_errors::Level as core::fmt::Debug>::fmt
   8: rustc_errors::HandlerInner::abort_if_errors_and_should_abort
   9: rustc_errors::Handler::bug
  10: rustc::util::bug::bug_fmt
  11: rustc::ty::wf::object_region_bounds
  12: rustc::ty::wf::object_region_bounds
  13: rustc::ty::wf::object_region_bounds
  14: rustc::util::bug::bug_fmt
  15: rustc::util::bug::bug_fmt
  16: rustc::ty::context::TypeckTables::node_type
  17: rustc::ty::context::TypeckTables::node_type
  18: <rustc_privacy::TypePrivacyVisitor as rustc::hir::intravisit::Visitor>::visit_ty
  19: rustc_privacy::provide
  20: rustc_privacy::provide
  21: rustc_privacy::provide
  22: <rustc_privacy::TypePrivacyVisitor as rustc::hir::intravisit::Visitor>::visit_ty
  23: rustc_privacy::provide
  24: rustc_privacy::provide
  25: <rustc_privacy::TypePrivacyVisitor as rustc::hir::intravisit::Visitor>::visit_ty
  26: rustc_privacy::provide
  27: rustc_privacy::provide
  28: <rustc_privacy::TypePrivacyVisitor as rustc::hir::intravisit::Visitor>::visit_expr
  29: rustc_privacy::provide
  30: <rustc_privacy::TypePrivacyVisitor as rustc::hir::intravisit::Visitor>::visit_expr
  31: rustc_privacy::provide
  32: <rustc_privacy::TypePrivacyVisitor as rustc::hir::intravisit::Visitor>::visit_expr
  34: <rustc_privacy::TypePrivacyVisitor as rustc::hir::intravisit::Visitor>::visit_expr
  35: rustc_privacy::provide
  36: <rustc_privacy::TypePrivacyVisitor as rustc::hir::intravisit::Visitor>::visit_expr
  37: <rustc_privacy::TypePrivacyVisitor as rustc::hir::intravisit::Visitor>::visit_expr
  38: rustc_privacy::provide
  39: <rustc_privacy::TypePrivacyVisitor as rustc::hir::intravisit::Visitor>::visit_expr
  40: rustc_privacy::provide
  41: <rustc_privacy::TypePrivacyVisitor as rustc::hir::intravisit::Visitor>::visit_expr
  42: rustc_privacy::provide
  43: <rustc_privacy::TypePrivacyVisitor as rustc::hir::intravisit::Visitor>::visit_expr
  44: rustc_privacy::provide
  45: <rustc_privacy::TypePrivacyVisitor as rustc::hir::intravisit::Visitor>::visit_expr
  46: <rustc_privacy::TypePrivacyVisitor as rustc::hir::intravisit::Visitor>::visit_expr
  47: rustc_privacy::provide
  48: <rustc_privacy::TypePrivacyVisitor as rustc::hir::intravisit::Visitor>::visit_expr
  49: rustc_privacy::provide
  50: <rustc_privacy::TypePrivacyVisitor as rustc::hir::intravisit::Visitor>::visit_expr
  51: rustc_privacy::provide
  52: <rustc_privacy::TypePrivacyVisitor as rustc::hir::intravisit::Visitor>::visit_expr
  53: rustc_privacy::provide
  54: <rustc_privacy::TypePrivacyVisitor as rustc::hir::intravisit::Visitor>::visit_expr
  55: <rustc_privacy::TypePrivacyVisitor as rustc::hir::intravisit::Visitor>::visit_expr
  56: rustc_privacy::provide
  57: <rustc_privacy::TypePrivacyVisitor as rustc::hir::intravisit::Visitor>::visit_expr
  58: rustc_privacy::provide
  59: rustc_privacy::provide
  60: <rustc_privacy::TypePrivacyVisitor as rustc::hir::intravisit::Visitor>::visit_expr
  61: rustc_privacy::provide
  62: rustc_privacy::provide
  63: <rustc_privacy::TypePrivacyVisitor as rustc::hir::intravisit::Visitor>::visit_item
  64: rustc_privacy::provide
  65: <rustc_interface::util::ReplaceBodyWithLoop as syntax::mut_visit::MutVisitor>::visit_block
  66: termcolor::ParseColorError::invalid
  67: termcolor::ParseColorError::invalid
  68: termcolor::ParseColorError::invalid
  69: termcolor::ParseColorError::invalid
  70: <rustc_interface::util::ReplaceBodyWithLoop as syntax::mut_visit::MutVisitor>::visit_mac
  71: _rust_maybe_catch_panic
  72: <rustc_interface::util::ReplaceBodyWithLoop as syntax::mut_visit::MutVisitor>::visit_mac
  73: rustc_interface::passes::BoxedResolver::to_expansion_result
  74: <syntax_pos::symbol::LocalInternedString as core::fmt::Display>::fmt
  75: <rustc::ty::instance::InstanceDef as rustc::ty::query::keys::Key>::query_crate
  76: <rustc_resolve::Resolver as core::convert::AsMut<rustc_resolve::Resolver>>::as_mut
  77: <syntax_pos::symbol::LocalInternedString as core::fmt::Display>::fmt
  78: <rustc_resolve::Resolver as core::convert::AsMut<rustc_resolve::Resolver>>::as_mut
  79: rustc_interface::interface::Compiler::output_file
  80: <rustc_resolve::Resolver as core::convert::AsMut<rustc_resolve::Resolver>>::as_mut
  81: <syntax_pos::symbol::LocalInternedString as core::fmt::Display>::fmt
  82: <rustc_driver::Compilation as core::fmt::Debug>::fmt
  83: <syntax_pos::symbol::LocalInternedString as core::fmt::Display>::fmt
  84: <syntax_pos::symbol::LocalInternedString as core::fmt::Display>::fmt
  85: _rust_maybe_catch_panic
  86: <syntax_pos::symbol::LocalInternedString as core::fmt::Display>::fmt
  87: ZN244_$LT$std..error..$LT$impl$u20$core..convert..From$LT$alloc..string..String$GT$$u20$for$u20$alloc..boxed..Box$LT$dyn$u20$std..error..Error$u2b$core..marker..Send$u2b$core..marker..Sync$GT$$GT$..from..StringError$u20$as$u20$core..fmt..Display$GT$3fmt17
  88: std::sys::windows::thread::Thread::new
  89: BaseThreadInitThunk
  90: RtlUserThreadStart
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports

note: rustc 1.40.0-nightly (518deda77 2019-10-18) running on x86_64-pc-windows-msvc

note: compiler flags: -C debuginfo=2 -C incremental --crate-type lib

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
#0 [check_mod_privacy] checking privacy in module `typelib`
#1 [analysis] running analysis passes on this crate
end of query stack
error: aborting due to previous error

error: could not compile `intercom`.
```

**Comment by matthiaskrgr** [comment]
Hmm, the stacktrace is not mentioning clippy as far as I see, perhaps this is a rustc bug?

**Comment by Rantanen** [comment]
That's a good point. Didn't look at it that closely. rustc managed to compile the crate just fine though so I'm guessing it has something to do with the metadata clippy is pulling off rustc. I'll move this to rustc.

**Comment by llogiq** [comment]
Does `cargo check` work?

**Comment by mati865** [comment]
It's Rust bug:
```
$ RUST_BACKTRACE=1 cargo check
    Checking intercom v0.3.0 (/tmp/intercom/intercom)
error: internal compiler error: src/librustc/ty/context.rs:552: node_type: no type for node `type IIntercomInterfaceVariant (hir_id=HirId { owner: DefIndex(2453), local_id: 579 })`

thread 'rustc' panicked at 'Box<Any>', src/librustc_errors/lib.rs:925:9
stack backtrace:
   0: backtrace::backtrace::libunwind::trace
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.37/src/backtrace/libunwind.rs:88
   1: backtrace::backtrace::trace_unsynchronized
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.37/src/backtrace/mod.rs:66
   2: std::sys_common::backtrace::_print_fmt
             at src/libstd/sys_common/backtrace.rs:77
   3: <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt
             at src/libstd/sys_common/backtrace.rs:61
   4: core::fmt::write
             at src/libcore/fmt/mod.rs:1028
   5: std::io::Write::write_fmt
             at src/libstd/io/mod.rs:1412
   6: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:65
   7: std::sys_common::backtrace::print
             at src/libstd/sys_common/backtrace.rs:50
   8: std::panicking::default_hook::{{closure}}
             at src/libstd/panicking.rs:189
   9: std::panicking::default_hook
             at src/libstd/panicking.rs:206
  10: rustc_driver::report_ice
  11: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:473
  12: std::panicking::begin_panic
  13: rustc_errors::HandlerInner::bug
  14: rustc_errors::Handler::bug
  15: rustc::util::bug::opt_span_bug_fmt::{{closure}}
  16: rustc::ty::context::tls::with_opt::{{closure}}
  17: rustc::ty::context::tls::with_context_opt
  18: rustc::ty::context::tls::with_opt
  19: rustc::util::bug::opt_span_bug_fmt
  20: rustc::util::bug::bug_fmt
  21: rustc::ty::context::TypeckTables::node_type::{{closure}}
  22: rustc::ty::context::TypeckTables::node_type
  23: <rustc_privacy::TypePrivacyVisitor as rustc::hir::intravisit::Visitor>::visit_ty
  24: rustc::hir::intravisit::walk_generic_args
  25: rustc::hir::intravisit::walk_qpath
  26: <rustc_privacy::TypePrivacyVisitor as rustc::hir::intravisit::Visitor>::visit_ty
  27: rustc::hir::intravisit::walk_qpath
  28: <rustc_privacy::TypePrivacyVisitor as rustc::hir::intravisit::Visitor>::visit_ty
  29: rustc::hir::intravisit::walk_qpath
  30: <rustc_privacy::TypePrivacyVisitor as rustc::hir::intravisit::Visitor>::visit_expr
  31: rustc::hir::intravisit::walk_expr
  32: <rustc_privacy::TypePrivacyVisitor as rustc::hir::intravisit::Visitor>::visit_expr
  33: rustc::hir::intravisit::walk_expr
  34: <rustc_privacy::TypePrivacyVisitor as rustc::hir::intravisit::Visitor>::visit_expr
  35: rustc::hir::intravisit::walk_expr
  36: <rustc_privacy::TypePrivacyVisitor as rustc::hir::intravisit::Visitor>::visit_expr
  37: rustc::hir::intravisit::walk_expr
  38: <rustc_privacy::TypePrivacyVisitor as rustc::hir::intravisit::Visitor>::visit_expr
  39: <rustc_privacy::TypePrivacyVisitor as rustc::hir::intravisit::Visitor>::visit_expr
  40: rustc::hir::intravisit::walk_expr
  41: <rustc_privacy::TypePrivacyVisitor as rustc::hir::intravisit::Visitor>::visit_expr
  42: rustc::hir::intravisit::walk_expr
  43: <rustc_privacy::TypePrivacyVisitor as rustc::hir::intravisit::Visitor>::visit_expr
  44: rustc::hir::intravisit::walk_expr
  45: <rustc_privacy::TypePrivacyVisitor as rustc::hir::intravisit::Visitor>::visit_expr
  46: rustc::hir::intravisit::walk_expr
  47: <rustc_privacy::TypePrivacyVisitor as rustc::hir::intravisit::Visitor>::visit_expr
  48: <rustc_privacy::TypePrivacyVisitor as rustc::hir::intravisit::Visitor>::visit_expr
  49: rustc::hir::intravisit::walk_expr
  50: <rustc_privacy::TypePrivacyVisitor as rustc::hir::intravisit::Visitor>::visit_expr
  51: rustc::hir::intravisit::walk_expr
  52: <rustc_privacy::TypePrivacyVisitor as rustc::hir::intravisit::Visitor>::visit_expr
  53: rustc::hir::intravisit::walk_expr
  54: <rustc_privacy::TypePrivacyVisitor as rustc::hir::intravisit::Visitor>::visit_expr
  55: rustc::hir::intravisit::walk_expr
  56: <rustc_privacy::TypePrivacyVisitor as rustc::hir::intravisit::Visitor>::visit_expr
  57: <rustc_privacy::TypePrivacyVisitor as rustc::hir::intravisit::Visitor>::visit_expr
  58: rustc::hir::intravisit::walk_expr
  59: <rustc_privacy::TypePrivacyVisitor as rustc::hir::intravisit::Visitor>::visit_expr
  60: <rustc_privacy::TypePrivacyVisitor as rustc::hir::intravisit::Visitor>::visit_local
  61: rustc::hir::intravisit::walk_expr
  62: <rustc_privacy::TypePrivacyVisitor as rustc::hir::intravisit::Visitor>::visit_expr
  63: <rustc_privacy::TypePrivacyVisitor as rustc::hir::intravisit::Visitor>::visit_nested_body
  64: rustc::hir::intravisit::walk_item
  65: <rustc_privacy::TypePrivacyVisitor as rustc::hir::intravisit::Visitor>::visit_item
  66: rustc_privacy::check_mod_privacy
  67: rustc::ty::query::__query_compute::check_mod_privacy
  68: rustc::ty::query::<impl rustc::ty::query::config::QueryAccessors for rustc::ty::query::queries::check_mod_privacy>::compute
  69: rustc::dep_graph::graph::DepGraph::with_task_impl
  70: rustc::ty::query::plumbing::<impl rustc::ty::context::TyCtxt>::get_query
  71: rustc::ty::query::plumbing::<impl rustc::ty::context::TyCtxt>::ensure_query
  72: rustc_interface::passes::analysis::{{closure}}::{{closure}}::{{closure}}
  73: rustc::util::common::time
  74: __rust_maybe_catch_panic
             at src/libpanic_unwind/lib.rs:80
  75: rustc_interface::passes::analysis::{{closure}}
  76: rustc::util::common::time
  77: rustc_interface::passes::analysis
  78: rustc::ty::query::__query_compute::analysis
  79: rustc::dep_graph::graph::DepGraph::with_task_impl
  80: rustc::ty::query::plumbing::<impl rustc::ty::context::TyCtxt>::get_query
  81: rustc_interface::passes::BoxedGlobalCtxt::access::{{closure}}
  82: rustc_interface::passes::create_global_ctxt::{{closure}}
  83: rustc_interface::passes::BoxedGlobalCtxt::enter
  84: rustc_interface::interface::run_compiler_in_existing_thread_pool
  85: std::thread::local::LocalKey<T>::with
  86: scoped_tls::ScopedKey<T>::set
  87: syntax::with_globals
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports

note: rustc 1.40.0-nightly (518deda77 2019-10-18) running on x86_64-unknown-linux-gnu

note: compiler flags: -C debuginfo=2 -C incremental --crate-type lib

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
#0 [check_mod_privacy] checking privacy in module `typelib`
#1 [analysis] running analysis passes on this crate
end of query stack
error: aborting due to previous error

error: could not compile `intercom`.
```

**Comment by Rantanen** [comment]
An old issue. Seems to only affect incremental builds: https://github.com/rust-lang/rust/issues/51716

Verified, `cargo clean && cargo check` works - ironically this also did reproduce on `cargo build`. I guess the builds I did didn't end up being incremental so I never caught it with those.
