### ISSUE TITLE
"Index out of bounds" panic on running clippy-driver

### ISSUE THREAD

**Issue by cole-miller** [rust-lang/rust-clippy#4923]
I've just upgraded (with rustup) to rustc 1.40.0, and I'm getting a compiler panic when running `clippy-driver`:

```
$ which clippy-driver
/home/hexbienium/.cargo/bin/clippy-driver
$ env RUST_BACKTRACE=full clippy-driver
thread 'main' panicked at 'index out of bounds: the len is 1 but the index is 1', /rustc/73528e339aae0f17a15ffa49a8ac608f50c6cf14/src/libcore/slice/mod.rs:2796:10
stack backtrace:
   0:     0x7faec50f5b24 - backtrace::backtrace::libunwind::trace::h65597d255cb1398b
                               at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.40/src/backtrace/libunwind.rs:88
   1:     0x7faec50f5b24 - backtrace::backtrace::trace_unsynchronized::hd4f479d7150ec4a0
                               at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.40/src/backtrace/mod.rs:66
   2:     0x7faec50f5b24 - std::sys_common::backtrace::_print_fmt::h015072984a2b172c
                               at src/libstd/sys_common/backtrace.rs:77
   3:     0x7faec50f5b24 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h6df05d3335f32194
                               at src/libstd/sys_common/backtrace.rs:61
   4:     0x7faec512e45c - core::fmt::write::h1f444f4312eb6c27
                               at src/libcore/fmt/mod.rs:1028
   5:     0x7faec50e9f07 - std::io::Write::write_fmt::h8d147888220078ef
                               at src/libstd/io/mod.rs:1412
   6:     0x7faec50fa38e - std::sys_common::backtrace::_print::h8a6df0fa81d6af62
                               at src/libstd/sys_common/backtrace.rs:65
   7:     0x7faec50fa38e - std::sys_common::backtrace::print::h6f05b4733407e509
                               at src/libstd/sys_common/backtrace.rs:50
   8:     0x7faec50fa38e - std::panicking::default_hook::{{closure}}::h0d0a23bd02315dd8
                               at src/libstd/panicking.rs:188
   9:     0x7faec50fa081 - std::panicking::default_hook::h8d15a9aecb4efac6
                               at src/libstd/panicking.rs:205
  10:     0x7faec55db853 - rustc_driver::report_ice::h604244c68c1c9a3a
  11:     0x7faec50fab60 - std::panicking::rust_panic_with_hook::hbe174577402a475d
                               at src/libstd/panicking.rs:468
  12:     0x7faec50fa62e - std::panicking::continue_panic_fmt::h4d855dad868accf3
                               at src/libstd/panicking.rs:373
  13:     0x7faec50fa516 - rust_begin_unwind
                               at src/libstd/panicking.rs:302
  14:     0x7faec5127ebe - core::panicking::panic_fmt::hdeb7979ab6591473
                               at src/libcore/panicking.rs:139
  15:     0x7faec5127e85 - core::panicking::panic_bounds_check::h48b559825fef6c92
                               at src/libcore/panicking.rs:96
  16:     0x55719e032dc0 - <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once::h29e91fb942ca53fd
  17:     0x55719e031529 - std::panicking::try::do_call::h71d14e48e25dd4d0
  18:     0x7faec510b44a - __rust_maybe_catch_panic
                               at src/libpanic_unwind/lib.rs:78
  19:     0x55719e033147 - rustc_driver::catch_fatal_errors::hc41e1afd9582cd86
  20:     0x55719e037cd2 - clippy_driver::main::h9a0bac04d2ff3357
  21:     0x55719e031463 - std::rt::lang_start::{{closure}}::h7133c9057e9ac829
  22:     0x7faec50fa4b3 - std::rt::lang_start_internal::{{closure}}::h6ea535ec5c50fc3e
                               at src/libstd/rt.rs:48
  23:     0x7faec50fa4b3 - std::panicking::try::do_call::h631c6408dfccc6f5
                               at src/libstd/panicking.rs:287
  24:     0x7faec510b44a - __rust_maybe_catch_panic
                               at src/libpanic_unwind/lib.rs:78
  25:     0x7faec50fb02d - std::panicking::try::hab539b2d1255d635
                               at src/libstd/panicking.rs:265
  26:     0x7faec50fb02d - std::panic::catch_unwind::hd5e0a26424bd7f34
                               at src/libstd/panic.rs:396
  27:     0x7faec50fb02d - std::rt::lang_start_internal::h3bdc4c7d98181bf9
                               at src/libstd/rt.rs:47
  28:     0x55719e037d12 - main
  29:     0x7faec4e8b09b - __libc_start_main
  30:     0x55719e02d629 - <unknown>

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports

note: rustc 1.40.0 (73528e339 2019-12-16) running on x86_64-unknown-linux-gnu

query stack during panic:
end of query stack
```

This happens whether or not I run it from a directory containing a `Cargo.toml`. `cargo clippy` works as expected. Let me know if some additional information would be helpful.

ETA: added verbose backtrace.

**Comment by mati865** [comment]
Duplicate of https://github.com/rust-lang/rust-clippy/issues/4716 fixed in nightly and beta. I think it's not worth backporting because users aren't supposed to call `clippy-driver` directly.

**Comment by cole-miller** [comment]
Thanks—sorry for opening this in the wrong repo.
