### ISSUE TITLE
ICE: Clippy panics, during constructing a span in `TabsInDocComments::check_attribute`

### ISSUE THREAD

**Issue by emacsist** [rust-lang/rust-clippy#5835]
env

- clippy: `clippy 0.0.212 (5c1f21c 2020-07-13)`
- rustc : `rustc 1.45.0 (5c1f21c3b 2020-07-13)`
- os:  `Mint 18.3 sylvia`

```bash
 $ cargo clippy --all-targets --all-features -- -D warnings
    Checking rtb-rust v0.1.0 (/home/hello/rtb-rust)
thread 'rustc' panicked at 'assertion failed: bpos.to_u32() >= mbc.pos.to_u32() + mbc.bytes as u32', src/librustc_span/source_map.rs:906:17
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust-clippy/issues/new

note: Clippy version: clippy 0.0.212 (5c1f21c 2020-07-13)

thread 'rustc' panicked at 'assertion failed: bpos.to_u32() >= mbc.pos.to_u32() + mbc.bytes as u32', src/librustc_span/source_map.rs:906:17
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust-clippy/issues/new

note: Clippy version: clippy 0.0.212 (5c1f21c 2020-07-13)

error: could not compile `rtb-rust`.

To learn more, run the command again with --verbose.
warning: build failed, waiting for other jobs to finish...
error: build failed
```

**Comment by matthiaskrgr** [comment]
Thanks for the report. Is the code you run clippy on available somehow?

**Comment by emacsist** [comment]
> Thanks for the report. Is the code you run clippy on available somehow?

`cargo clippy` is OK

**Comment by flip1995** [comment]
@emacsist Can you share the code or a minimal example, that produces this ICE with us? Without example code debugging this is nearly impossible.

Another thing that might help is, if you could share the output of 
```
RUST_BACKTRACE=1 cargo clippy --all-targets --all-features -- -D warnings
```

**Comment by emacsist** [comment]
Sorry, code the is company project, so it's inconvenient to share. 

The output is 

```bash
    Checking rtb-rust v0.1.0 (/home/hello/rtb-rust)
thread 'rustc' panicked at 'assertion failed: bpos.to_u32() >= mbc.pos.to_u32() + mbc.bytes as u32', src/librustc_span/source_map.rs:906:17
stack backtrace:
thread 'rustc' panicked at 'assertion failed: bpos.to_u32() >= mbc.pos.to_u32() + mbc.bytes as u32', src/librustc_span/source_map.rs:906:17
stack backtrace:
   0: backtrace::backtrace::libunwind::trace
   0: backtrace::backtrace::libunwind::trace
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.46/src/backtrace/libunwind.rs:86
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.46/src/backtrace/libunwind.rs:86
   1: backtrace::backtrace::trace_unsynchronized
   1: backtrace::backtrace::trace_unsynchronized
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.46/src/backtrace/mod.rs:66
   2: std::sys_common::backtrace::_print_fmt
             at src/libstd/sys_common/backtrace.rs:78
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.46/src/backtrace/mod.rs:66
   2: std::sys_common::backtrace::_print_fmt
             at src/libstd/sys_common/backtrace.rs:78
   3: <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt
   3: <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt
             at src/libstd/sys_common/backtrace.rs:59
             at src/libstd/sys_common/backtrace.rs:59
   4: core::fmt::write
             at src/libcore/fmt/mod.rs:1076
   5: std::io::Write::write_fmt
             at src/libstd/io/mod.rs:1537
   6: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:62
   7: std::sys_common::backtrace::print
             at src/libstd/sys_common/backtrace.rs:49
   8: std::panicking::default_hook::{{closure}}
             at src/libstd/panicking.rs:198
   9: std::panicking::default_hook
             at src/libstd/panicking.rs:218
  10: clippy_driver::report_clippy_ice
  11: <alloc::boxed::Box<F> as core::ops::function::Fn<A>>::call
             at /home/hello/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/src/liballoc/boxed.rs:1090
  12: proc_macro::bridge::client::<impl proc_macro::bridge::Bridge>::enter::{{closure}}::{{closure}}
             at /home/hello/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/src/libproc_macro/bridge/client.rs:318
  13: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:490
   4: core::fmt::write
             at src/libcore/fmt/mod.rs:1076
   5: std::io::Write::write_fmt
             at src/libstd/io/mod.rs:1537
   6: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:62
   7: std::sys_common::backtrace::print
             at src/libstd/sys_common/backtrace.rs:49
   8: std::panicking::default_hook::{{closure}}
             at src/libstd/panicking.rs:198
   9: std::panicking::default_hook
             at src/libstd/panicking.rs:218
  10: clippy_driver::report_clippy_ice
  11: <alloc::boxed::Box<F> as core::ops::function::Fn<A>>::call
             at /home/hello/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/src/liballoc/boxed.rs:1090
  12: proc_macro::bridge::client::<impl proc_macro::bridge::Bridge>::enter::{{closure}}::{{closure}}
             at /home/hello/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/src/libproc_macro/bridge/client.rs:318
  13: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:490
  14: std::panicking::begin_panic
  15: rustc_span::source_map::SourceMap::bytepos_to_file_charpos
  16: rustc_span::source_map::SourceMap::lookup_char_pos
  17: rustc_errors::emitter::EmitterWriter::get_multispan_max_line_num
  18: <rustc_errors::emitter::EmitterWriter as rustc_errors::emitter::Emitter>::emit_diagnostic
  19: <rustc_errors::json::JsonEmitter as rustc_errors::emitter::Emitter>::emit_diagnostic
  20: rustc_errors::HandlerInner::emit_diagnostic
  14: std::panicking::begin_panic
  15: rustc_span::source_map::SourceMap::bytepos_to_file_charpos
  16: rustc_span::source_map::SourceMap::lookup_char_pos
  21: rustc_errors::diagnostic_builder::DiagnosticBuilder::emit
  17: rustc_errors::emitter::EmitterWriter::get_multispan_max_line_num
  18: <rustc_errors::emitter::EmitterWriter as rustc_errors::emitter::Emitter>::emit_diagnostic
  22: core::ops::function::FnOnce::call_once{{vtable.shim}}
  19: <rustc_errors::json::JsonEmitter as rustc_errors::emitter::Emitter>::emit_diagnostic
  20: rustc_errors::HandlerInner::emit_diagnostic
  21: rustc_errors::diagnostic_builder::DiagnosticBuilder::emit
  22: core::ops::function::FnOnce::call_once{{vtable.shim}}
  23: rustc_middle::lint::struct_lint_level::struct_lint_level_impl
  23: rustc_middle::lint::struct_lint_level::struct_lint_level_impl
  24: rustc_lint::levels::LintLevelsBuilder::struct_lint
  24: rustc_lint::levels::LintLevelsBuilder::struct_lint
  25: <clippy_lints::tabs_in_doc_comments::TabsInDocComments as rustc_lint::passes::EarlyLintPass>::check_attribute
  25: <clippy_lints::tabs_in_doc_comments::TabsInDocComments as rustc_lint::passes::EarlyLintPass>::check_attribute
  26: <rustc_lint::early::EarlyLintPassObjects as rustc_lint::passes::EarlyLintPass>::check_attribute
  26: <rustc_lint::early::EarlyLintPassObjects as rustc_lint::passes::EarlyLintPass>::check_attribute
  27: rustc_ast::visit::walk_item
  28: rustc_ast::visit::walk_mod
  29: rustc_ast::visit::walk_item
  30: rustc_ast::visit::walk_mod
  31: rustc_ast::visit::walk_item
  32: rustc_ast::visit::walk_mod
  27: rustc_ast::visit::walk_item
  28: rustc_ast::visit::walk_mod
  29: rustc_ast::visit::walk_item
  30: rustc_ast::visit::walk_mod
  31: rustc_ast::visit::walk_item
  32: rustc_ast::visit::walk_mod
  33: rustc_lint::early::early_lint_crate
  33: rustc_lint::early::early_lint_crate
  34: rustc_lint::early::check_ast_crate
  34: rustc_lint::early::check_ast_crate
  35: rustc_session::utils::<impl rustc_session::session::Session>::time
  36: rustc_interface::passes::BoxedResolver::access::{{closure}}
  37: rustc_interface::passes::configure_and_expand::{{closure}}
  38: rustc_interface::queries::Queries::lower_to_hir
  35: rustc_session::utils::<impl rustc_session::session::Session>::time
  39: rustc_interface::queries::Queries::global_ctxt
  40: rustc_interface::interface::run_compiler_in_existing_thread_pool
  36: rustc_interface::passes::BoxedResolver::access::{{closure}}
  37: rustc_interface::passes::configure_and_expand::{{closure}}
  38: rustc_interface::queries::Queries::lower_to_hir
  39: rustc_interface::queries::Queries::global_ctxt
  40: rustc_interface::interface::run_compiler_in_existing_thread_pool
  41: rustc_ast::attr::with_globals
  41: rustc_ast::attr::with_globals
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust-clippy/issues/new

note: Clippy version: clippy 0.0.212 (5c1f21c 2020-07-13)

query stack during panic:
end of query stack
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust-clippy/issues/new

note: Clippy version: clippy 0.0.212 (5c1f21c 2020-07-13)

query stack during panic:
end of query stack
error: could not compile `rtb-rust`.

To learn more, run the command again with --verbose.
warning: build failed, waiting for other jobs to finish...
error: build failed

```

**Comment by flip1995** [comment]
I think this is the offending code:

https://github.com/rust-lang/rust-clippy/blob/f5d429cd762423901f946abd800dc2cd91366ccf/clippy_lints/src/tabs_in_doc_comments.rs#L67-L71

**Comment by phansch** [comment]
It's possible that this was fixed in Rust 1.45.1. It seems to have been a rustc issue? https://github.com/rust-lang/rust/issues/68730

@emacsist Could you upgrade to Rust 1.45.1 and check if the panic still happens?

**Comment by phansch** [comment]
I'm going to close this issue as it seems like it has been fixed with rust-lang/rust#68730. Feel free to re-open it, if it still happens.

**Comment by WiSaGaN** [comment]
This still happens on 1.51.0:

```
hread 'rustc' panicked at 'assertion failed: bpos.to_u32() >= mbc.pos.to_u32() + mbc.bytes as u32', compiler/rustc_span/src/lib.rs:1512:17
stack backtrace:
   0:     0x7f2815b70ee0 - std::backtrace_rs::backtrace::libunwind::trace::h5e9d00f0cdf4f57e
                               at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/std/src/../../backtrace/src/backtrace/libunwind.rs:90:5
   1:     0x7f2815b70ee0 - std::backtrace_rs::backtrace::trace_unsynchronized::hd5302bd66215dab9
                               at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x7f2815b70ee0 - std::sys_common::backtrace::_print_fmt::ha0237cd11a34e2bf
                               at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/std/src/sys_common/backtrace.rs:67:5
   3:     0x7f2815b70ee0 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h171d4c10df1a98ee
                               at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/std/src/sys_common/backtrace.rs:46:22
   4:     0x7f2815be1d0c - core::fmt::write::h89e4288724daa3fa
                               at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/core/src/fmt/mod.rs:1096:17
   5:     0x7f2815b63ff2 - std::io::Write::write_fmt::h6d40f996e84584d9
                               at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/std/src/io/mod.rs:1568:15
   6:     0x7f2815b74d95 - std::sys_common::backtrace::_print::h0c0b93221682afc8
                               at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/std/src/sys_common/backtrace.rs:49:5
   7:     0x7f2815b74d95 - std::sys_common::backtrace::print::h57a9f95204c2fdd6
                               at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/std/src/sys_common/backtrace.rs:36:9
   8:     0x7f2815b74d95 - std::panicking::default_hook::{{closure}}::h4245258b50e37e69
                               at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/std/src/panicking.rs:208:50
   9:     0x7f2815b748f3 - std::panicking::default_hook::h7b00dcc1d0944747
                               at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/std/src/panicking.rs:225:9
  10:     0x55dff0efc4f7 - clippy_driver::ICE_HOOK::{{closure}}::{{closure}}::h0bbd19626cb2f5b5
  11:     0x7f2808d35826 - <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call::haa3e7efb343ae8bd
                               at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/alloc/src/boxed.rs:1535:9
  12:     0x7f2808d18819 - proc_macro::bridge::client::<impl proc_macro::bridge::Bridge>::enter::{{closure}}::{{closure}}::h924fe6021cb4ef29
                               at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/proc_macro/src/bridge/client.rs:320:21
  13:     0x7f2815b75696 - std::panicking::rust_panic_with_hook::h71e6a073d87de1f5
                               at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/std/src/panicking.rs:595:17
  14:     0x7f2815b75187 - std::panicking::begin_panic_handler::{{closure}}::hd549436f6bb6dbb8
                               at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/std/src/panicking.rs:495:13
  15:     0x7f2815b7137c - std::sys_common::backtrace::__rust_end_short_backtrace::h4e5f4b72b04174c3
                               at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/std/src/sys_common/backtrace.rs:141:18
  16:     0x7f2815b75119 - rust_begin_unwind
                               at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/std/src/panicking.rs:493:5
  17:     0x7f2815bde331 - core::panicking::panic_fmt::hcd56f7f635f62c74
                               at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/core/src/panicking.rs:92:14
  18:     0x7f2815bde27d - core::panicking::panic::h07405d6be4bce887
                               at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/core/src/panicking.rs:50:5
  19:     0x7f28186e6257 - rustc_span::SourceFile::lookup_file_pos::hc48ce89a8a472104
  20:     0x7f28186e630c - rustc_span::SourceFile::lookup_file_pos_with_col_display::h494b342704bddacf
  21:     0x7f28186df6a1 - rustc_span::source_map::SourceMap::lookup_char_pos::hcc3c691d7733ebd2
  22:     0x7f2819325449 - rustc_errors::emitter::EmitterWriter::get_multispan_max_line_num::hd3db9b0c3c613ba9
  23:     0x7f2819321a3f - <rustc_errors::emitter::EmitterWriter as rustc_errors::emitter::Emitter>::emit_diagnostic::h244edcba8cce0b8a
  24:     0x7f2817b9266a - rustc_errors::json::Diagnostic::from_errors_diagnostic::ha6dbe3e60e0ac4bb
  25:     0x7f2817b9216a - <rustc_errors::json::JsonEmitter as rustc_errors::emitter::Emitter>::emit_diagnostic::h0046edf66037eca0
  26:     0x7f2819334ac8 - rustc_errors::HandlerInner::emit_diagnostic::h6fcba1d3bfd026d3
  27:     0x7f2819332bfe - rustc_errors::diagnostic_builder::DiagnosticBuilder::emit::h20a1684e1367e0b2
  28:     0x55dff0f88528 - core::ops::function::FnOnce::call_once{{vtable.shim}}::h4862d84244e9e65a
  29:     0x7f28186a0e90 - rustc_middle::lint::struct_lint_level::struct_lint_level_impl::hb2215ad4fc523e38
  30:     0x55dff113b3b4 - rustc_lint::context::LintContext::struct_span_lint::h7f10662d1f2ebd4b
  31:     0x55dff11348f1 - <clippy_lints::tabs_in_doc_comments::TabsInDocComments as rustc_lint::passes::EarlyLintPass>::check_attribute::hf11485ecbed68a21
  32:     0x7f28173e3962 - <rustc_lint::early::EarlyLintPassObjects as rustc_lint::passes::EarlyLintPass>::check_attribute::hac37bf9a3bd8f055
  33:     0x7f281653dc56 - rustc_ast::visit::walk_struct_field::h3b709190d724524b
  34:     0x7f2816577488 - <rustc_lint::early::EarlyContextAndPass<T> as rustc_ast::visit::Visitor>::visit_struct_field::h949d302cf03f0ffa
  35:     0x7f281653d92d - rustc_ast::visit::walk_struct_def::h4a829df7cc7181bc
  36:     0x7f28165774fc - <rustc_lint::early::EarlyContextAndPass<T> as rustc_ast::visit::Visitor>::visit_variant_data::h673afb3be77e60bb
  37:     0x7f281653ea15 - rustc_ast::visit::walk_item::haa6379120322d33c
  38:     0x7f2816576c1b - <rustc_lint::early::EarlyContextAndPass<T> as rustc_ast::visit::Visitor>::visit_item::hd54b81dd94016852
  39:     0x7f281653e2f9 - rustc_ast::visit::walk_mod::h5dd69bb8e1bf3b4d
  40:     0x7f2816577756 - <rustc_lint::early::EarlyContextAndPass<T> as rustc_ast::visit::Visitor>::visit_mod::h3332843da9c77b0b
  41:     0x7f281653ec86 - rustc_ast::visit::walk_item::haa6379120322d33c
  42:     0x7f2816576c1b - <rustc_lint::early::EarlyContextAndPass<T> as rustc_ast::visit::Visitor>::visit_item::hd54b81dd94016852
  43:     0x7f281653e2f9 - rustc_ast::visit::walk_mod::h5dd69bb8e1bf3b4d
  44:     0x7f2816577756 - <rustc_lint::early::EarlyContextAndPass<T> as rustc_ast::visit::Visitor>::visit_mod::h3332843da9c77b0b
  45:     0x7f281653d2ff - rustc_ast::visit::walk_crate::h7543aff17597c227
  46:     0x7f2816564e70 - rustc_lint::early::early_lint_crate::hc1bdde5bfebaca4a
  47:     0x7f281877c0a8 - rustc_lint::early::check_ast_crate::hc205a2c131dff380
  48:     0x7f2818761267 - rustc_session::utils::<impl rustc_session::session::Session>::time::hf6cdec4c8fcedda8
  49:     0x7f2818776960 - rustc_interface::passes::BoxedResolver::access::{{closure}}::hb9c484859450932f
  50:     0x7f2818767f54 - rustc_interface::passes::configure_and_expand::{{closure}}::h3a41a297ff107384
  51:     0x7f2818776756 - rustc_interface::passes::BoxedResolver::access::hfd0e687e2c8082e4
  52:     0x7f28187861b5 - rustc_interface::queries::Queries::lower_to_hir::h526946090fe9ea3a
  53:     0x7f2818786c1e - rustc_interface::queries::Queries::global_ctxt::hd6c3bc1c7f006419
  54:     0x7f281871ac23 - rustc_interface::queries::<impl rustc_interface::interface::Compiler>::enter::hc8c0f3e9bba77540
  55:     0x7f2818714643 - rustc_span::with_source_map::hedfeccc0422f91c4
  56:     0x7f281871beca - rustc_interface::interface::create_compiler_and_run::h7abf0b53119fd7ea
  57:     0x7f2818714d05 - rustc_span::with_session_globals::hb5dbfdbd3bd12723
  58:     0x7f281871c36a - std::sys_common::backtrace::__rust_begin_short_backtrace::hfe0fde7e082e2baf
  59:     0x7f2818738c4a - core::ops::function::FnOnce::call_once{{vtable.shim}}::h83306388c44d16bf
  60:     0x7f2815b85c8a - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h61144a2be4ee36d8
                               at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/alloc/src/boxed.rs:1521:9
  61:     0x7f2815b85c8a - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::hcf5d395fdd120c17
                               at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/alloc/src/boxed.rs:1521:9
  62:     0x7f2815b85c8a - std::sys::unix::thread::Thread::new::thread_start::hb5e40d3d934ebb7a
                               at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/std/src/sys/unix/thread.rs:71:17
  63:     0x7f2815a8d3f9 - start_thread
  64:     0x7f2815872b53 - __clone
  65:                0x0 - <unknown>

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust-clippy/issues/new

note: Clippy version: clippy 0.1.51 (2fd73fa 2021-03-23)

query stack during panic:
end of query stack
```

**Comment by flip1995** [comment]
@WiSaGaN can you share code, where this happens. We don't have anything to go off of here.

**Comment by WiSaGaN** [comment]
Ok. I did trim down to [this](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=9eb2dc827dbdd48f139d01b72ce156b7) in playground.

I think there is a character after the unicode in the doc comment that causes this.
