### ISSUE TITLE
internal error: entered unreachable code

### ISSUE THREAD

**Issue by bkontur** [rust-lang/rust-clippy#5872]
```
...
thread 'rustc' panicked at 'internal error: entered unreachable code', src/tools/clippy/clippy_lints/src/loops.rs:2448:5
stack backtrace:
   0: backtrace::backtrace::libunwind::trace
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.46/src/backtrace/libunwind.rs:86
   1: backtrace::backtrace::trace_unsynchronized
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.46/src/backtrace/mod.rs:66
   2: std::sys_common::backtrace::_print_fmt
             at src/libstd/sys_common/backtrace.rs:78
   3: <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt
             at src/libstd/sys_common/backtrace.rs:59
   4: core::fmt::write
             at src/libcore/fmt/mod.rs:1076
   5: std::io::Write::write_fmt
             at src/libstd/io/mod.rs:1537
   6: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:62
   7: std::sys_common::backtrace::print
             at src/libstd/sys_common/backtrace.rs:49
   8: std::panicking::default_hook::{{closure}}
             at src/libstd/panicking.rs:198
   9: std::panicking::default_hook
             at src/libstd/panicking.rs:217
  10: clippy_driver::report_clippy_ice
  11: <alloc::boxed::Box<F> as core::ops::function::Fn<A>>::call
             at /rustc/346aec9b02f3c74f3fce97fd6bda24709d220e49/src/liballoc/boxed.rs:1095
  12: proc_macro::bridge::client::<impl proc_macro::bridge::Bridge>::enter::{{closure}}::{{closure}}
             at /rustc/346aec9b02f3c74f3fce97fd6bda24709d220e49/src/libproc_macro/bridge/client.rs:318
  13: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:530
  14: std::panicking::begin_panic
  15: clippy_lints::loops::shorten_span
  16: <clippy_lints::loops::Loops as rustc_lint::passes::LateLintPass>::check_expr
  17: <rustc_lint::late::LateLintPassObjects as rustc_lint::passes::LateLintPass>::check_expr
  18: <rustc_lint::late::LateContextAndPass<T> as rustc_hir::intravisit::Visitor>::visit_expr
  19: rustc_hir::intravisit::walk_local
  20: rustc_hir::intravisit::walk_stmt
  21: rustc_hir::intravisit::walk_expr
  22: <rustc_lint::late::LateContextAndPass<T> as rustc_hir::intravisit::Visitor>::visit_expr
  23: <rustc_lint::late::LateContextAndPass<T> as rustc_hir::intravisit::Visitor>::visit_nested_body
  24: <rustc_lint::late::LateContextAndPass<T> as rustc_hir::intravisit::Visitor>::visit_fn
  25: rustc_hir::intravisit::walk_impl_item
  26: rustc_hir::intravisit::Visitor::visit_nested_impl_item
  27: rustc_hir::intravisit::walk_item
  28: rustc_hir::intravisit::Visitor::visit_nested_item
  29: rustc_hir::intravisit::walk_item
  30: rustc_hir::intravisit::Visitor::visit_nested_item
  31: rustc_hir::intravisit::walk_crate
  32: rustc_lint::late::late_lint_pass_crate
  33: rustc_session::utils::<impl rustc_session::session::Session>::time
  34: rustc_session::utils::<impl rustc_session::session::Session>::time
  35: <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
  36: rustc_session::utils::<impl rustc_session::session::Session>::time
  37: rustc_interface::passes::analysis
  38: rustc_middle::ty::query::<impl rustc_query_system::query::config::QueryAccessors<rustc_middle::ty::context::TyCtxt> for rustc_middle::ty::query::queries::analysis>::compute
  39: rustc_middle::dep_graph::<impl rustc_query_system::dep_graph::DepKind for rustc_middle::dep_graph::dep_node::DepKind>::with_deps
  40: rustc_query_system::dep_graph::graph::DepGraph<K>::with_task_impl
  41: rustc_query_system::query::plumbing::get_query_impl
  42: rustc_middle::ty::context::tls::enter_global
  43: rustc_interface::queries::<impl rustc_interface::interface::Compiler>::enter
  44: rustc_span::with_source_map
  45: rustc_interface::interface::create_compiler_and_run
  46: scoped_tls::ScopedKey<T>::set
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust-clippy/issues/new

note: Clippy version: clippy 0.0.212 (346aec9 2020-07-11)

query stack during panic:
#0 [analysis] running analysis passes on this crate
end of query stack
error: could not compile `xyz`.

To learn more, run the command again with --verbose.
```

**Comment by ebroto** [comment]
Minimal repro:
```rust
fn main() {
    let _ = vec![1, 2, 3].into_iter().collect::<Vec<_>>().is_empty();
}
```
([playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=3821cb432ca85a57e025f1155df87bc0))

I will prepare a fix soon.
