### ISSUE TITLE
ICE: "already checked this is a reference" checking `rustc_ast_passes`

### ISSUE THREAD

**Issue by matthiaskrgr** [rust-lang/rust-clippy#6332]
### Code

EDIT:
````rust
fn cmark_check(bad: &mut bool) {
	let mut link_err = false;
	*&bad = true;
    macro_rules! cmark_error {
        ($bad:expr) => {
            *$bad = true;

        }
    }
	cmark_error!(
		&mut link_err
	);
}

pub fn main() {}

````

### Meta
clippy is @ 408b615d3451d00c21b303fd8aeb74b77970a4a9

### Error output

```

    Checking rustc_ast_passes v0.0.0 (/home/matthias/vcs/github/rust/compiler/rustc_ast_passes)
thread 'rustc' panicked at 'already checked this is a reference', clippy_lints/src/reference.rs:66:53
```

<details><summary>Backtrace</summary>
  <p>
  
  ```
     Checking rustc_ast_passes v0.0.0 (/home/matthias/vcs/github/rust/compiler/rustc_ast_passes)
thread 'rustc' panicked at 'already checked this is a reference', clippy_lints/src/reference.rs:66:53
stack backtrace:
   0:     0x7fd6123ece20 - std::backtrace_rs::backtrace::libunwind::trace::h448c56741b6011d3
                               at /rustc/74f7e32f43b5fb0f83896d124566d8242eb786b1/library/std/src/../../backtrace/src/backtrace/libunwind.rs:100:5
   1:     0x7fd6123ece20 - std::backtrace_rs::backtrace::trace_unsynchronized::h2d26397c5720fdbb
                               at /rustc/74f7e32f43b5fb0f83896d124566d8242eb786b1/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x7fd6123ece20 - std::sys_common::backtrace::_print_fmt::h720a2f61f75b9f58
                               at /rustc/74f7e32f43b5fb0f83896d124566d8242eb786b1/library/std/src/sys_common/backtrace.rs:67:5
   3:     0x7fd6123ece20 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h8d62bbfda6d5c836
                               at /rustc/74f7e32f43b5fb0f83896d124566d8242eb786b1/library/std/src/sys_common/backtrace.rs:46:22
   4:     0x7fd61245d31c - core::fmt::write::h1857a60b204f1b6a
                               at /rustc/74f7e32f43b5fb0f83896d124566d8242eb786b1/library/core/src/fmt/mod.rs:1078:17
   5:     0x7fd6123dea82 - std::io::Write::write_fmt::h16a9fe7680ac245c
                               at /rustc/74f7e32f43b5fb0f83896d124566d8242eb786b1/library/std/src/io/mod.rs:1518:15
   6:     0x7fd6123f1e85 - std::sys_common::backtrace::_print::h9ba51a6db618de7d
                               at /rustc/74f7e32f43b5fb0f83896d124566d8242eb786b1/library/std/src/sys_common/backtrace.rs:49:5
   7:     0x7fd6123f1e85 - std::sys_common::backtrace::print::h5f20e41c85e91716
                               at /rustc/74f7e32f43b5fb0f83896d124566d8242eb786b1/library/std/src/sys_common/backtrace.rs:36:9
   8:     0x7fd6123f1e85 - std::panicking::default_hook::{{closure}}::h5b7294ca19e8edab
                               at /rustc/74f7e32f43b5fb0f83896d124566d8242eb786b1/library/std/src/panicking.rs:208:50
   9:     0x7fd6123f1b28 - std::panicking::default_hook::hb3948d1f74b6ff4c
                               at /rustc/74f7e32f43b5fb0f83896d124566d8242eb786b1/library/std/src/panicking.rs:227:9
  10:     0x55ce5e2cb727 - clippy_driver::ICE_HOOK::{{closure}}::{{closure}}::hee0bf3ae704978b0
  11:     0x7fd6123f2786 - std::panicking::rust_panic_with_hook::h55d23fef0ad751bc
                               at /rustc/74f7e32f43b5fb0f83896d124566d8242eb786b1/library/std/src/panicking.rs:597:17
  12:     0x7fd6123f22a7 - std::panicking::begin_panic_handler::{{closure}}::h56ae74c6dea6e141
                               at /rustc/74f7e32f43b5fb0f83896d124566d8242eb786b1/library/std/src/panicking.rs:499:13
  13:     0x7fd6123ed2bc - std::sys_common::backtrace::__rust_end_short_backtrace::h3c4721f56689fae4
                               at /rustc/74f7e32f43b5fb0f83896d124566d8242eb786b1/library/std/src/sys_common/backtrace.rs:141:18
  14:     0x7fd6123f2209 - rust_begin_unwind
                               at /rustc/74f7e32f43b5fb0f83896d124566d8242eb786b1/library/std/src/panicking.rs:495:5
  15:     0x7fd6124596d1 - core::panicking::panic_fmt::hb15d6f55e8472f62
                               at /rustc/74f7e32f43b5fb0f83896d124566d8242eb786b1/library/core/src/panicking.rs:92:14
  16:     0x7fd6124592b3 - core::option::expect_failed::h6bc6a05976f4cb88
                               at /rustc/74f7e32f43b5fb0f83896d124566d8242eb786b1/library/core/src/option.rs:1260:5
  17:     0x55ce5e4f064a - <clippy_lints::reference::DerefAddrOf as rustc_lint::passes::EarlyLintPass>::check_expr::h0dcab03f86af510d
  18:     0x7fd614f808f3 - <rustc_lint::early::EarlyLintPassObjects as rustc_lint::passes::EarlyLintPass>::check_expr::h67486da5f8180b22
  19:     0x7fd612f291a2 - <rustc_lint::early::EarlyContextAndPass<T> as rustc_ast::visit::Visitor>::visit_expr::ha60b568984b279cc
  20:     0x7fd612ee1b6d - rustc_ast::visit::walk_expr::hd1898a410652890d
  21:     0x7fd612f291ad - <rustc_lint::early::EarlyContextAndPass<T> as rustc_ast::visit::Visitor>::visit_expr::ha60b568984b279cc
  22:     0x7fd612ee120c - rustc_ast::visit::walk_expr::hd1898a410652890d
  23:     0x7fd612f291ad - <rustc_lint::early::EarlyContextAndPass<T> as rustc_ast::visit::Visitor>::visit_expr::ha60b568984b279cc
  24:     0x7fd612f29d7d - <rustc_lint::early::EarlyContextAndPass<T> as rustc_ast::visit::Visitor>::visit_local::hcf56e1b84fc9e5ae
  25:     0x7fd612ee1e0e - rustc_ast::visit::walk_expr::hd1898a410652890d
  26:     0x7fd612f291ad - <rustc_lint::early::EarlyContextAndPass<T> as rustc_ast::visit::Visitor>::visit_expr::ha60b568984b279cc
  27:     0x7fd612ee1e0e - rustc_ast::visit::walk_expr::hd1898a410652890d
  28:     0x7fd612f291ad - <rustc_lint::early::EarlyContextAndPass<T> as rustc_ast::visit::Visitor>::visit_expr::ha60b568984b279cc
  29:     0x7fd612edea1d - rustc_ast::visit::walk_arm::h9c25f9f313bff502
  30:     0x7fd612ee137b - rustc_ast::visit::walk_expr::hd1898a410652890d
  31:     0x7fd612f291ad - <rustc_lint::early::EarlyContextAndPass<T> as rustc_ast::visit::Visitor>::visit_expr::ha60b568984b279cc
  32:     0x7fd612edd936 - rustc_ast::visit::walk_fn::hd6e248739436ac58
  33:     0x7fd612ed8aa2 - rustc_ast::visit::walk_assoc_item::ha8bb6f311e782725
  34:     0x7fd612ee6265 - rustc_ast::visit::walk_item::h8d42bcb073fa8b68
  35:     0x7fd612eded57 - rustc_ast::visit::walk_mod::h55cb6f2491c71208
  36:     0x7fd612ee555c - rustc_ast::visit::walk_item::h8d42bcb073fa8b68
  37:     0x7fd612eded57 - rustc_ast::visit::walk_mod::h55cb6f2491c71208
  38:     0x7fd612f1b2e5 - rustc_lint::early::early_lint_crate::hbcae213aadb307c1
  39:     0x7fd612f19f82 - rustc_lint::early::check_ast_crate::h23e8dd238a077082
  40:     0x7fd612eb9b51 - rustc_session::utils::<impl rustc_session::session::Session>::time::h43eda2cf7e9114cc
  41:     0x7fd612f0b6a8 - rustc_interface::passes::BoxedResolver::access::{{closure}}::h2626c54196ee0a8d
  42:     0x7fd612e97027 - rustc_interface::passes::configure_and_expand::{{closure}}::h1898eef861d20c91
  43:     0x7fd612f0b3f4 - rustc_interface::passes::BoxedResolver::access::h0580d4ae736eed05
  44:     0x7fd612f38c87 - rustc_interface::queries::Queries::lower_to_hir::h5df62c3f33b6b949
  45:     0x7fd612f398cc - rustc_interface::queries::Queries::global_ctxt::h7be406895213a9d5
  46:     0x7fd612ce4701 - rustc_interface::queries::<impl rustc_interface::interface::Compiler>::enter::ha4de22cb0dda795a
  47:     0x7fd612cd285e - rustc_span::with_source_map::h29633e90c8bdca16
  48:     0x7fd612ce5f52 - rustc_interface::interface::create_compiler_and_run::h646ae36fd2c94a87
  49:     0x7fd612cd3b0a - rustc_span::with_session_globals::hda575f9d899f5c60
  50:     0x7fd612ceb7cf - std::sys_common::backtrace::__rust_begin_short_backtrace::hc0d91feb93491fb8
  51:     0x7fd612c50b38 - core::ops::function::FnOnce::call_once{{vtable.shim}}::h425334629854e612
  52:     0x7fd61240186a - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h9e7afb7a0a438236
                               at /rustc/74f7e32f43b5fb0f83896d124566d8242eb786b1/library/alloc/src/boxed.rs:1307:9
  53:     0x7fd61240186a - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h70c646c4271337a1
                               at /rustc/74f7e32f43b5fb0f83896d124566d8242eb786b1/library/alloc/src/boxed.rs:1307:9
  54:     0x7fd61240186a - std::sys::unix::thread::Thread::new::thread_start::h35d2b8d36f210d02
                               at /rustc/74f7e32f43b5fb0f83896d124566d8242eb786b1/library/std/src/sys/unix/thread.rs:71:17
  55:     0x7fd6122e23e9 - start_thread
  56:     0x7fd6120ca293 - __GI___clone
  57:                0x0 - <unknown>

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust-clippy/issues/new

note: Clippy version: clippy 0.0.212 (408b615d3 2020-11-14)

query stack during panic:
end of query stack
error: could not compile `rustc_ast_passes`

To learn more, run the command again with --verbose.
command did not execute successfully: "/home/matthias/vcs/github/rust/build/x86_64-unknown-linux-gnu/stage0/bin/cargo" "clippy" "--target" "x86_64-unknown-linux-gnu" "-Zunstable-options" "-Zbinary-dep-depinfo" "-j" "1" "--release" "--features" " llvm max_level_info" "--manifest-path" "/home/matthias/vcs/github/rust/compiler/rustc/Cargo.toml" "-p" "rustc-main" "-p" "rustc_driver" "-p" "rustc_ast_pretty" "-p" "rustc_hir" "-p" "rustc_macros" "-p" "rustc_index" "-p" "rustc_hir_pretty" "-p" "rustc_mir" "-p" "rustc_infer" "-p" "rustc_graphviz" "-p" "rustc_lexer" "-p" "rustc_trait_selection" "-p" "rustc_parse_format" "-p" "rustc_attr" "-p" "rustc_apfloat" "-p" "rustc_target" "-p" "rustc_metadata" "-p" "rustc_expand" "-p" "rustc_ast_passes" "-p" "rustc_span" "-p" "rustc_arena" "-p" "rustc_session" "-p" "rustc_lint_defs" "-p" "rustc_fs_util" "-p" "rustc_serialize" "-p" "rustc_interface" "-p" "rustc_typeck" "-p" "rustc_resolve" "-p" "rustc_ast_lowering" "-p" "rustc_passes" "-p" "rustc_ty" "-p" "rustc_builtin_macros" "-p" "rustc_codegen_llvm" "-p" "rustc_llvm" "-p" "rustc_incremental" "-p" "rustc_privacy" "-p" "rustc_mir_build" "-p" "rustc_traits" "-p" "rustc_symbol_mangling" "-p" "rustc_errors" "-p" "rustc_data_structures" "-p" "rustc_feature" "-p" "rustc_error_codes" "-p" "rustc_middle" "-p" "rustc_query_system" "-p" "rustc_parse" "-p" "rustc_ast" "-p" "rustc_save_analysis" "-p" "rustc_lint" "-p" "rustc_plugin_impl" "-p" "rustc_codegen_ssa" "--message-format" "json-render-diagnostics" "--" "--cap-lints" "warn"
expected success, got: exit code: 101
failed to run: /home/matthias/vcs/github/rust/build/bootstrap/debug/bootstrap clippy -j 1
Build completed unsuccessfully in 0:00:11
  ```
  
  </p>
</details>

**Comment by matthiaskrgr** [comment]
reduced:
````rust
fn cmark_check(bad: &mut bool) {
	let mut link_err = false;
	*&bad = true;
    macro_rules! cmark_error {
        ($bad:expr) => {
            *$bad = true;

        }
    }
	cmark_error!(
		&mut link_err
	);
}

pub fn main() {}

````

**Comment by matthiaskrgr** [comment]
cc @ThibsG
