### ISSUE TITLE
ICE with `#![feature(trivial_bounds)]`: SizeOf nullary MIR operator called for unsized type

### ISSUE THREAD

**Issue by hyd-dev** [rust-lang/rust-clippy#6663]
I [tried](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=34c85b5e42a7f161764e3eed8a858f4d) this code:
```rust
#![feature(trivial_bounds)]
#![warn(const_err)]

use core::mem::size_of;

struct Helper<T: ?Sized>(T);

trait Unsized<T: ?Sized> {
    const SIZE: usize = usize::MAX;
}

impl<T: ?Sized> Unsized<T> for Helper<T> {}

impl<T> Helper<T> {
    const SIZE: usize = size_of::<T>();
}

struct TrickClippy(str);

impl TrickClippy {
    fn trick_clippy() -> bool
    where
        Self: Sized,
    {
        Helper::<Self>::SIZE == Helper::<str>::SIZE
    }
}
```
rustc compiled the code successfully with only `dead_code` warnings, while Clippy gave me an additional `const_err` warning and an ICE (`SizeOf nullary MIR operator called for unsized type TrickClippy`):
<details>

```
warning: any use of this value will cause an error
   --> /rustup/home/toolchains/nightly-2021-01-28-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/mem/mod.rs:310:5
    |
310 |     intrinsics::size_of::<T>()
    |     ^^^^^^^^^^^^^^^^^^^^^^^^^^
    |     |
    |     size_of called on unsized type `TrickClippy`
    |     inside `std::mem::size_of::<TrickClippy>` at /rustup/home/toolchains/nightly-2021-01-28-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/mem/mod.rs:310:5
    |     inside `Helper::<TrickClippy>::SIZE` at <anon>:15:25
    | 
   ::: <anon>:15:5
    |
15  |     const SIZE: usize = size_of::<T>();
    |     -----------------------------------
    |
note: the lint level is defined here
   --> <anon>:2:9
    |
2   | #![warn(const_err)]
    |         ^^^^^^^^^

warning: 4 warnings emitted

error: internal compiler error: SizeOf nullary MIR operator called for unsized type TrickClippy
   --> /rustup/home/toolchains/nightly-2021-01-28-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/mem/mod.rs:310:5
    |
310 |     intrinsics::size_of::<T>()
    |     ^^^^^^^^^^^^^^^^^^^^^^^^^^
    |
    = note: delayed at compiler/rustc_mir/src/interpret/step.rs:269:35

thread 'rustc' panicked at 'no errors encountered even though `delay_span_bug` issued', compiler/rustc_errors/src/lib.rs:974:13
stack backtrace:
   0:     0x7f59e4f57dd7 - std::backtrace_rs::backtrace::libunwind::trace::h8bc78f7bc1f75bdb
                               at /rustc/a2f8f6281817d430e20726128b739d3c6708561c/library/std/src/../../backtrace/src/backtrace/libunwind.rs:90:5
   1:     0x7f59e4f57dd7 - std::backtrace_rs::backtrace::trace_unsynchronized::ha4c961c9576f95ba
                               at /rustc/a2f8f6281817d430e20726128b739d3c6708561c/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x7f59e4f57dd7 - std::sys_common::backtrace::_print_fmt::hc20cfdc233d6eb02
                               at /rustc/a2f8f6281817d430e20726128b739d3c6708561c/library/std/src/sys_common/backtrace.rs:67:5
   3:     0x7f59e4f57dd7 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h04bea14549780a0f
                               at /rustc/a2f8f6281817d430e20726128b739d3c6708561c/library/std/src/sys_common/backtrace.rs:46:22
   4:     0x7f59e4fc8eac - core::fmt::write::h3868db8542c90941
                               at /rustc/a2f8f6281817d430e20726128b739d3c6708561c/library/core/src/fmt/mod.rs:1096:17
   5:     0x7f59e4f4a602 - std::io::Write::write_fmt::h55dd75636eef6a5c
                               at /rustc/a2f8f6281817d430e20726128b739d3c6708561c/library/std/src/io/mod.rs:1568:15
   6:     0x7f59e4f5bd35 - std::sys_common::backtrace::_print::h6439e8525077c7da
                               at /rustc/a2f8f6281817d430e20726128b739d3c6708561c/library/std/src/sys_common/backtrace.rs:49:5
   7:     0x7f59e4f5bd35 - std::sys_common::backtrace::print::h02b685f728ce3931
                               at /rustc/a2f8f6281817d430e20726128b739d3c6708561c/library/std/src/sys_common/backtrace.rs:36:9
   8:     0x7f59e4f5bd35 - std::panicking::default_hook::{{closure}}::h7c29625065fafae1
                               at /rustc/a2f8f6281817d430e20726128b739d3c6708561c/library/std/src/panicking.rs:208:50
   9:     0x7f59e4f5b893 - std::panicking::default_hook::hba441710bb71f4d5
                               at /rustc/a2f8f6281817d430e20726128b739d3c6708561c/library/std/src/panicking.rs:225:9
  10:     0x55b324ebffe7 - clippy_driver::ICE_HOOK::{{closure}}::{{closure}}::hfa46ae5294546c19
  11:     0x7f59e4f5c636 - std::panicking::rust_panic_with_hook::ha936eb00e51bc4d9
                               at /rustc/a2f8f6281817d430e20726128b739d3c6708561c/library/std/src/panicking.rs:595:17
  12:     0x7f59e4f5c157 - std::panicking::begin_panic_handler::{{closure}}::hcd15140e0238536e
                               at /rustc/a2f8f6281817d430e20726128b739d3c6708561c/library/std/src/panicking.rs:497:13
  13:     0x7f59e4f5829c - std::sys_common::backtrace::__rust_end_short_backtrace::hb13a021bb64823a1
                               at /rustc/a2f8f6281817d430e20726128b739d3c6708561c/library/std/src/sys_common/backtrace.rs:141:18
  14:     0x7f59e4f5c0b9 - rust_begin_unwind
                               at /rustc/a2f8f6281817d430e20726128b739d3c6708561c/library/std/src/panicking.rs:493:5
  15:     0x7f59e4f5c06b - std::panicking::begin_panic_fmt::h3ef6798fa589483b
                               at /rustc/a2f8f6281817d430e20726128b739d3c6708561c/library/std/src/panicking.rs:435:5
  16:     0x7f59e876a513 - rustc_errors::HandlerInner::flush_delayed::hb4ed3fcc7df94332
  17:     0x7f59e8768dc4 - <rustc_errors::HandlerInner as core::ops::drop::Drop>::drop::hb549d70799c8423b
  18:     0x7f59e7b3502b - core::ptr::drop_in_place<rustc_session::parse::ParseSess>::h9c5f1afa233e17cb
  19:     0x7f59e7b386a0 - <alloc::rc::Rc<T> as core::ops::drop::Drop>::drop::h827436d78276eb65
  20:     0x7f59e7b35fed - core::ptr::drop_in_place<rustc_interface::interface::Compiler>::h33ad0635be1ad697
  21:     0x7f59e7b33221 - rustc_span::with_source_map::h05af58868046c383
  22:     0x7f59e7b3e49a - rustc_interface::interface::create_compiler_and_run::hd6bcde8a021d388e
  23:     0x7f59e7b33d1f - std::sys_common::backtrace::__rust_begin_short_backtrace::h079be7663f9274fd
  24:     0x7f59e7b19b6a - core::ops::function::FnOnce::call_once{{vtable.shim}}::had52829d2d210307
  25:     0x7f59e4f6cb4a - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h8ffdf8dc1f37e360
                               at /rustc/a2f8f6281817d430e20726128b739d3c6708561c/library/alloc/src/boxed.rs:1487:9
  26:     0x7f59e4f6cb4a - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h74f6ec149ce6acc8
                               at /rustc/a2f8f6281817d430e20726128b739d3c6708561c/library/alloc/src/boxed.rs:1487:9
  27:     0x7f59e4f6cb4a - std::sys::unix::thread::Thread::new::thread_start::h565bef3956c58d58
                               at /rustc/a2f8f6281817d430e20726128b739d3c6708561c/library/std/src/sys/unix/thread.rs:71:17
  28:     0x7f59e4e6e609 - start_thread
  29:     0x7f59e4c44293 - clone
  30:                0x0 - <unknown>

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust-clippy/issues/new

note: Clippy version: clippy 0.1.51 (a2f8f62 2021-01-27)
```
</details>

I believe the `const_err` warning was incorrect. rustc did *not* report it and `core::intrinsics::size_of()` [has](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=9bb42b5a2d00d4bfb21434768938e922) a `Sized` bound.

cc rust-lang/rust#48214

By the way, removing `#![warn(const_err)]` (it's a deny-by-default *lint*) makes the ICE disappear. Looks like `delay_span_bug` does not differentiate between hard errors and denied lints?

**Comment by matthiaskrgr** [comment]
Weird, this only happens when clippy is trying to do codegen (??) but I wasn't able to reproduce with rustc alone :|
