### ISSUE TITLE
clippy crashing on after upgrade to Rust 1.50

### ISSUE THREAD

**Issue by nayato** [rust-lang/rust-clippy#6734]
Upgrading Rust from 1.49 to 1.50 and running `cargo clippy` I got this:
```
thread 'rustc' panicked at 'forcing query with already existing `DepNode`
- query-key: ParamEnvAnd { param_env: ParamEnv { caller_bounds: [], reveal: UserFacing }, value: Const { ty: ntex_amqp::codec::types::Symbol, val: Value(ByRef { alloc: Allocation { bytes: [2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 21, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], relocations: Relocations(SortedMap { data: [(Size { raw: 8 }, ((), alloc937))] }), init_mask: InitMask { blocks: [16777215], len: Size { raw: 40 } }, size: Size { raw: 40 }, align: Align { pow2: 3 }, mutability: Not, extra: () }, offset: Size { raw: 0 } }) } }
- dep-node: destructure_const(60166cbe13284287-b88e2fb08e16350e)', /rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b/compiler/rustc_query_system/src/query/plumbing.rs:586:5
stack backtrace:
   0: rust_begin_unwind
             at /rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b/library/std/src/panicking.rs:493:5
   1: std::panicking::begin_panic_fmt
             at /rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b/library/std/src/panicking.rs:435:5
   2: rustc_query_system::query::plumbing::get_query_impl
   3: clippy_lints::non_copy_const::is_value_unfrozen_raw::inner
   4: <clippy_lints::non_copy_const::NonCopyConst as rustc_lint::passes::LateLintPass>::check_item
   5: <rustc_lint::late::LateLintPassObjects as rustc_lint::passes::LateLintPass>::check_item
   6: rustc_hir::intravisit::Visitor::visit_nested_item
   7: rustc_hir::intravisit::walk_mod
   8: <rustc_lint::late::LateContextAndPass<T> as rustc_hir::intravisit::Visitor>::visit_mod
   9: rustc_hir::intravisit::walk_item
  10: rustc_hir::intravisit::Visitor::visit_nested_item
  11: rustc_hir::intravisit::walk_mod
  12: <rustc_lint::late::LateContextAndPass<T> as rustc_hir::intravisit::Visitor>::visit_mod
  13: rustc_hir::intravisit::walk_item
  14: rustc_hir::intravisit::Visitor::visit_nested_item
  15: rustc_hir::intravisit::walk_mod
  16: <rustc_lint::late::LateContextAndPass<T> as rustc_hir::intravisit::Visitor>::visit_mod
  17: rustc_hir::intravisit::walk_crate
  18: rustc_lint::late::late_lint_pass_crate
  19: rustc_session::utils::<impl rustc_session::session::Session>::time
  20: <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
  21: rustc_session::utils::<impl rustc_session::session::Session>::time
  22: rustc_interface::passes::analysis
  23: rustc_middle::ty::query::<impl rustc_query_system::query::config::QueryAccessors<rustc_middle::ty::context::TyCtxt> for rustc_middle::ty::query::queries::analysis>::compute
  24: rustc_middle::dep_graph::<impl rustc_query_system::dep_graph::DepKind for rustc_middle::dep_graph::dep_node::DepKind>::with_deps
  25: rustc_query_system::dep_graph::graph::DepGraph<K>::with_task_impl
  26: rustc_data_structures::stack::ensure_sufficient_stack
  27: rustc_query_system::query::plumbing::get_query_impl
  28: rustc_interface::passes::QueryContext::enter
  29: rustc_interface::queries::<impl rustc_interface::interface::Compiler>::enter
  30: rustc_span::with_source_map
  31: rustc_interface::interface::create_compiler_and_run
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust-clippy/issues/new

note: Clippy version: clippy 0.0.212 (cb75ad5 2021-02-10)

query stack during panic:
#0 [analysis] running analysis passes on this crate
end of query stack
```

**Comment by phansch** [comment]
Thanks for the report @nayato!

Are you able to share the source code or reduced example code that causes the crash?

**Comment by matthiaskrgr** [comment]
Could as well be a rustc issue :thinking: 
https://github.com/rust-lang/rust/issues?q=is%3Aissue+is%3Aopen+%22forcing+query+with+already+existing+DepNode%22

**Comment by nayato** [comment]
Unfortunately I can't provide small isolated sample at this time.
Changing CARGO_INCREMENTAL to 0 makes `cargo clippy` succeed. `cargo build` works fine regardless of CARGO_INCREMENTAL value.

**Comment by kalzoo** [comment]
Saw the same general issue, can't share code but can share this little bit:

```
thread 'rustc' panicked at 'forcing query with already existing `DepNode`
- query-key: ParamEnvAnd { param_env: ParamEnv { caller_bounds: [], reveal: All }, value: &Omitted }
- dep-node: layout_raw(15c5b4f91f9d8cc8-730d1c4d385f7728)', /rustc/0fa28ce074ef8c458103391d17ad305ed65a1aa2/compiler/rustc_query_system/src/query/plumbing.rs:640:5
stack backtrace:
   0: _rust_begin_unwind
   1: std::panicking::begin_panic_fmt
   2: rustc_query_system::query::plumbing::get_query_impl
   3: <rustc_query_impl::Queries as rustc_middle::ty::query::QueryEngine>::layout_raw
   4: <rustc_middle::ty::layout::LayoutCx<rustc_middle::ty::context::TyCtxt> as rustc_target::abi::LayoutOf>::layout_of
   5: <core::iter::adapters::copied::Copied<I> as core::iter::traits::iterator::Iterator>::try_fold
   6: <alloc::vec::Vec<T> as alloc::vec::spec_from_iter::SpecFromIter<T,I>>::from_iter
   7: rustc_middle::ty::layout::LayoutCx<rustc_middle::ty::context::TyCtxt>::layout_raw_uncached
   8: rustc_middle::ty::layout::layout_raw
   9: rustc_query_impl::<impl rustc_query_system::query::config::QueryAccessors<rustc_query_impl::plumbing::QueryCtxt> for rustc_query_impl::queries::layout_raw>::compute
  10: rustc_query_system::dep_graph::graph::DepGraph<K>::with_task_impl
  11: rustc_data_structures::stack::ensure_sufficient_stack
  12: rustc_query_system::query::plumbing::get_query_impl
  13: <rustc_query_impl::Queries as rustc_middle::ty::query::QueryEngine>::layout_raw
  14: <rustc_middle::ty::layout::LayoutCx<rustc_middle::ty::context::TyCtxt> as rustc_target::abi::LayoutOf>::layout_of
  15: <rustc_lint::context::LateContext as rustc_target::abi::LayoutOf>::layout_of
  16: <clippy_lints::zero_sized_map_values::ZeroSizedMapValues as rustc_lint::passes::LateLintPass>::check_ty
  17: <rustc_lint::late::LateLintPassObjects as rustc_lint::passes::LateLintPass>::check_ty
  18: rustc_hir::intravisit::Visitor::visit_generic_arg
  19: rustc_hir::intravisit::walk_generic_args
  20: rustc_hir::intravisit::walk_qpath
  21: rustc_hir::intravisit::walk_fn
  22: <rustc_lint::late::LateContextAndPass<T> as rustc_hir::intravisit::Visitor>::visit_fn
  23: rustc_hir::intravisit::walk_item
  24: rustc_hir::intravisit::Visitor::visit_nested_item
  25: rustc_hir::intravisit::walk_item
  26: rustc_hir::intravisit::Visitor::visit_nested_item
  27: rustc_hir::intravisit::walk_item
  28: rustc_hir::intravisit::Visitor::visit_nested_item
  29: rustc_hir::intravisit::walk_item
  30: rustc_hir::intravisit::Visitor::visit_nested_item
  31: rustc_hir::intravisit::walk_item
  32: rustc_hir::intravisit::Visitor::visit_nested_item
  33: rustc_hir::intravisit::walk_crate
  34: rustc_lint::late::late_lint_pass_crate
  35: rustc_lint::late::late_lint_crate
  36: rustc_data_structures::sync::join
  37: rustc_interface::passes::analysis::{{closure}}::{{closure}}
  38: rustc_session::utils::<impl rustc_session::session::Session>::time
  39: rustc_interface::passes::analysis
  40: rustc_query_system::dep_graph::graph::DepGraph<K>::with_task_impl
  41: rustc_data_structures::stack::ensure_sufficient_stack
  42: rustc_query_system::query::plumbing::force_query_with_job
  43: rustc_query_system::query::plumbing::get_query_impl
  44: <rustc_query_impl::Queries as rustc_middle::ty::query::QueryEngine>::analysis
  45: rustc_interface::queries::<impl rustc_interface::interface::Compiler>::enter
  46: rustc_span::with_source_map
  47: rustc_interface::interface::create_compiler_and_run
  48: scoped_tls::ScopedKey<T>::set
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust-clippy/issues/new

note: Clippy version: clippy 0.1.54 (0fa28ce074e 2021-07-02)

query stack during panic:
#0 [layout_raw] computing layout of `(omitted)`
#1 [analysis] running analysis passes on this crate
end of query stack
warning: 5 warnings emitted

error: could not compile `package-name`
```

Can confirm that `CARGO_INCREMENTAL=0` also works for me.

Thanks!

**Comment by rdrpenguin04** [comment]
Is this needed to be open at this point? Rust stable is on 1.66. If there is still a point to fix it (and it hasn't been fixed by mistake), it should probably be fixed, or its priority should be changed.
