### ISSUE TITLE
Clippy Panic 'found unstable fingerprints for predicates_of'

### ISSUE THREAD

**Issue by JoshuaHall** [rust-lang/rust-clippy#7048]
I was running `clippy --release` in my project mostly and that was working perfect, and then I tried just `clippy` and that produced this error.

Here's the repo that the issue happened in: https://github.com/JoshuaHall/project-euler-rust

Command output from just `clippy`:
```zsh
    Checking rust v0.1.0 (/Users/jhall3/projects/project-euler-rust)
thread 'rustc' panicked at 'found unstable fingerprints for predicates_of(core[40e9]::marker::Sized): GenericPredicates { parent: None, predicates: [(Binder(TraitPredicate(<Self as std::marker::Sized>)), /Users/jhall3/.rustup/toolchains/nightly-x86_64-apple-darwin/lib/rustlib/src/rust/library/core/src/marker.rs:92:1: 92:16 (#0))] }', /rustc/07e0e2ec268c140e607e1ac7f49f145612d0f597/compiler/rustc_query_system/src/query/plumbing.rs:593:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust-clippy/issues/new

note: Clippy version: clippy 0.1.52 (07e0e2ec 2021-03-24)

query stack during panic:
#0 [predicates_of] computing predicates of `std::marker::Sized`
#1 [check_item_well_formed] checking that `utils::<impl at src/utils.rs:170:1: 174:2>` is well-formed
end of query stack
thread 'rustc' panicked at 'found unstable fingerprints for predicates_of(core[40e9]::default::Default): GenericPredicates { parent: None, predicates: [(Binder(TraitPredicate(<Self as std::marker::Sized>)), /Users/jhall3/.rustup/toolchains/nightly-x86_64-apple-darwin/lib/rustlib/src/rust/library/core/src/default.rs:85:20: 85:25 (#0)), (Binder(TraitPredicate(<Self as std::default::Default>)), /Users/jhall3/.rustup/toolchains/nightly-x86_64-apple-darwin/lib/rustlib/src/rust/library/core/src/default.rs:85:1: 85:25 (#0))] }', /rustc/07e0e2ec268c140e607e1ac7f49f145612d0f597/compiler/rustc_query_system/src/query/plumbing.rs:593:5

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust-clippy/issues/new

note: Clippy version: clippy 0.1.52 (07e0e2ec 2021-03-24)

query stack during panic:
#0 [predicates_of] computing predicates of `std::default::Default`
#1 [check_item_well_formed] checking that `utils::<impl at src/utils.rs:210:1: 214:2>` is well-formed
end of query stack
thread 'rustc' panicked at 'found unstable fingerprints for predicates_of(core[40e9]::iter::traits::iterator::Iterator): GenericPredicates { parent: None, predicates: [(Binder(TraitPredicate(<Self as std::iter::Iterator>)), /Users/jhall3/.rustup/toolchains/nightly-x86_64-apple-darwin/lib/rustlib/src/rust/library/core/src/iter/traits/iterator.rs:98:1: 98:19 (#0))] }', /rustc/07e0e2ec268c140e607e1ac7f49f145612d0f597/compiler/rustc_query_system/src/query/plumbing.rs:593:5

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust-clippy/issues/new

note: Clippy version: clippy 0.1.52 (07e0e2ec 2021-03-24)

query stack during panic:
#0 [predicates_of] computing predicates of `std::iter::Iterator`
#1 [check_item_well_formed] checking that `utils::<impl at src/utils.rs:216:1: 227:2>` is well-formed
end of query stack
thread 'rustc' panicked at 'found unstable fingerprints for predicates_of(core[40e9]::clone::Clone): GenericPredicates { parent: None, predicates: [(Binder(TraitPredicate(<Self as std::marker::Sized>)), /Users/jhall3/.rustup/toolchains/nightly-x86_64-apple-darwin/lib/rustlib/src/rust/library/core/src/clone.rs:108:18: 108:23 (#0)), (Binder(TraitPredicate(<Self as std::clone::Clone>)), /Users/jhall3/.rustup/toolchains/nightly-x86_64-apple-darwin/lib/rustlib/src/rust/library/core/src/clone.rs:108:1: 108:23 (#0))] }', /rustc/07e0e2ec268c140e607e1ac7f49f145612d0f597/compiler/rustc_query_system/src/query/plumbing.rs:593:5

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust-clippy/issues/new

note: Clippy version: clippy 0.1.52 (07e0e2ec 2021-03-24)

query stack during panic:
#0 [predicates_of] computing predicates of `std::clone::Clone`
#1 [check_item_well_formed] checking that `utils::<impl at src/utils.rs:392:10: 392:15>` is well-formed
end of query stack
error: could not compile `rust`

To learn more, run the command again with --verbose.
```

Some meta data info:
```zsh
~/projects/project-euler-rust main !11 ?2 ❯ cargo clippy -V
clippy 0.1.52 (07e0e2ec 2021-03-24)
~/projects/project-euler-rust main !11 ?2 ❯ rustc -Vv
rustc 1.53.0-nightly (07e0e2ec2 2021-03-24)
binary: rustc
commit-hash: 07e0e2ec268c140e607e1ac7f49f145612d0f597
commit-date: 2021-03-24
host: x86_64-apple-darwin
release: 1.53.0-nightly
LLVM version: 12.0.0
```

**Comment by giraffate** [comment]
This is similar to https://github.com/rust-lang/rust/issues/83226.

> Here's the repo that the issue happened in: https://github.com/JoshuaHall/project-euler-rust, commit 3ff18b4052462e53ea85d3b9a56b5ed455be5dd5 (should be latest commit)

The `JoshuaHall/project-euler-rust` repository is missing, I saw 404. Can you have another reproduction?

**Comment by matthiaskrgr** [comment]
Yes, this is a rustc incremental crash.
Incremental builds are disabled in release mode which is why this does not reproduce with `--release`.
@Manishearth  can you please move this over to the rustc repo? Thanks!
