### ISSUE TITLE
Unexpected panic computing predicates of std::marker::Freeze

### ISSUE THREAD

**Issue by 132ikl** [rust-lang/rust-clippy#7116]
Hi, I encountered this while running `cargo xtask ci` on [ruma](https://github.com/ruma/ruma). Others (included the automated CI) do not seem to be having this issue. This is on a fresh installation of nightly x86.

```
To learn more, run the command again with --verbose.
thread 'rustc' panicked at 'assertion failed: `(left == right)`
  left: `Some(Fingerprint(14102990140023404743, 9006884895215956278))`,
 right: `Some(Fingerprint(6642314836680145768, 1529582154985885595))`: found unstable fingerprints for predicates_of(core[ec89]::marker::Freeze): GenericPredicates { parent: None, predicates: [(Binder(TraitPredicate(<Self as std::marker::Freeze>), []), /rustc/6df26f897cffb2d86880544bb451c6b5f8509b2d/library/core/src/marker.rs:716:1: 716:39 (#0))] }', /rustc/6df26f897cffb2d86880544bb451c6b5f8509b2d/compiler/rustc_query_system/src/query/plumbing.rs:593:5
stack backtrace:
   0: rust_begin_unwind
             at /rustc/6df26f897cffb2d86880544bb451c6b5f8509b2d/library/std/src/panicking.rs:493:5
   1: core::panicking::panic_fmt
             at /rustc/6df26f897cffb2d86880544bb451c6b5f8509b2d/library/core/src/panicking.rs:92:14
   2: core::panicking::assert_failed_inner
   3: core::panicking::assert_failed
   4: rustc_query_system::query::plumbing::incremental_verify_ich
   5: rustc_query_system::query::plumbing::load_from_disk_and_cache_in_memory
   6: rustc_query_system::query::plumbing::get_query_impl
   7: <rustc_query_impl::Queries as rustc_middle::ty::query::QueryEngine>::predicates_of
   8: rustc_trait_selection::traits::select::SelectionContext::impl_or_trait_obligations
   9: rustc_infer::infer::InferCtxt::commit_unconditionally
  10: rustc_data_structures::stack::ensure_sufficient_stack
  11: rustc_trait_selection::traits::select::confirmation::<impl rustc_trait_selection::traits::select::SelectionContext>::confirm_candidate
  12: rustc_infer::infer::InferCtxt::probe
  13: rustc_trait_selection::traits::select::SelectionContext::evaluate_candidate
  14: rustc_trait_selection::traits::select::SelectionContext::evaluate_stack
  15: rustc_middle::dep_graph::<impl rustc_query_system::dep_graph::DepKind for rustc_middle::dep_graph::dep_node::DepKind>::with_deps
  16: rustc_query_system::dep_graph::graph::DepGraph<K>::with_anon_task
  17: rustc_trait_selection::traits::select::SelectionContext::evaluate_trait_predicate_recursively
  18: rustc_data_structures::stack::ensure_sufficient_stack
  19: rustc_trait_selection::traits::select::SelectionContext::evaluate_predicate_recursively
  20: rustc_infer::infer::InferCtxt::probe
  21: rustc_trait_selection::traits::select::SelectionContext::evaluate_root_obligation
  22: rustc_infer::infer::InferCtxtBuilder::enter_with_canonical
  23: rustc_traits::evaluate_obligation::evaluate_obligation
  24: rustc_query_impl::<impl rustc_query_system::query::config::QueryAccessors<rustc_query_impl::plumbing::QueryCtxt> for rustc_query_impl::queries::evaluate_obligation>::compute
  25: rustc_middle::dep_graph::<impl rustc_query_system::dep_graph::DepKind for rustc_middle::dep_graph::dep_node::DepKind>::with_deps
  26: rustc_query_system::query::plumbing::load_from_disk_and_cache_in_memory
  27: rustc_data_structures::stack::ensure_sufficient_stack
  28: rustc_query_system::query::plumbing::get_query_impl
  29: <rustc_query_impl::Queries as rustc_middle::ty::query::QueryEngine>::evaluate_obligation
  30: <rustc_infer::infer::InferCtxt as rustc_trait_selection::traits::query::evaluate_obligation::InferCtxtExt>::evaluate_obligation
  31: <rustc_infer::infer::InferCtxt as rustc_trait_selection::traits::query::evaluate_obligation::InferCtxtExt>::evaluate_obligation_no_overflow
  32: rustc_trait_selection::traits::type_known_to_meet_bound_modulo_regions
  33: rustc_infer::infer::InferCtxtBuilder::enter
  34: rustc_ty_utils::common_traits::is_freeze_raw
  35: rustc_middle::dep_graph::<impl rustc_query_system::dep_graph::DepKind for rustc_middle::dep_graph::dep_node::DepKind>::with_deps
  36: rustc_query_system::query::plumbing::load_from_disk_and_cache_in_memory
  37: rustc_data_structures::stack::ensure_sufficient_stack
  38: rustc_query_system::query::plumbing::get_query_impl
  39: <rustc_query_impl::Queries as rustc_middle::ty::query::QueryEngine>::is_freeze_raw
  40: rustc_middle::ty::util::<impl rustc_middle::ty::TyS>::is_freeze
  41: clippy_lints::functions::must_use::is_mutable_ty
  42: clippy_lints::functions::must_use::check_must_use_candidate
  43: clippy_lints::functions::must_use::check_impl_item
  44: <clippy_lints::functions::Functions as rustc_lint::passes::LateLintPass>::check_impl_item
  45: <rustc_lint::late::LateLintPassObjects as rustc_lint::passes::LateLintPass>::check_impl_item
  46: rustc_hir::intravisit::Visitor::visit_nested_impl_item
  47: rustc_hir::intravisit::walk_impl_item_ref
  48: rustc_hir::intravisit::walk_item
  49: rustc_hir::intravisit::Visitor::visit_nested_item
  50: rustc_hir::intravisit::walk_mod
  51: <rustc_lint::late::LateContextAndPass<T> as rustc_hir::intravisit::Visitor>::visit_mod
  52: rustc_hir::intravisit::Visitor::visit_nested_item
  53: rustc_hir::intravisit::walk_mod
  54: <rustc_lint::late::LateContextAndPass<T> as rustc_hir::intravisit::Visitor>::visit_mod
  55: rustc_hir::intravisit::walk_crate
  56: rustc_lint::late::late_lint_pass_crate
  57: rustc_lint::late::late_lint_crate
  58: rustc_session::utils::<impl rustc_session::session::Session>::time
  59: std::panic::catch_unwind
  60: rustc_session::utils::<impl rustc_session::session::Session>::time
  61: rustc_interface::passes::analysis
  62: rustc_middle::dep_graph::<impl rustc_query_system::dep_graph::DepKind for rustc_middle::dep_graph::dep_node::DepKind>::with_deps
  63: rustc_query_system::dep_graph::graph::DepGraph<K>::with_task_impl
  64: rustc_data_structures::stack::ensure_sufficient_stack
  65: rustc_query_system::query::plumbing::force_query_with_job
  66: rustc_query_system::query::plumbing::get_query_impl
  67: <rustc_query_impl::Queries as rustc_middle::ty::query::QueryEngine>::analysis
  68: rustc_interface::passes::QueryContext::enter
  69: rustc_interface::queries::<impl rustc_interface::interface::Compiler>::enter
  70: rustc_span::with_source_map
  71: rustc_interface::interface::create_compiler_and_run
  72: scoped_tls::ScopedKey<T>::set
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust-clippy/issues/new

note: Clippy version: clippy 0.1.53 (6df26f8 2021-04-20)

query stack during panic:
#0 [predicates_of] computing predicates of `std::marker::Freeze`
#1 [evaluate_obligation] evaluating trait selection obligation `user_id::UserId: std::marker::Freeze`
#2 [is_freeze_raw] computing whether `user_id::UserId` is freeze
#3 [analysis] running analysis passes on this crate
end of query stack
```

**Comment by 132ikl** [comment]
Nevermind, this seems to actually be a compiler issue. I won't be able to make a full bug report tonight, but when I do I will link it here.
