### ISSUE TITLE
Panic in `clippy_lints/src/implicit_return.rs:150:66`

### ISSUE THREAD

**Issue by phil-opp** [rust-lang/rust-clippy#7231]
Link to CI build where the issue occured: https://github.com/phil-opp/blog_os/runs/2600559391?check_suite_focus=true#step:4:226

Panic output with backtrace:

```
thread 'rustc' panicked at 'called `Option::unwrap()` on a `None` value', src/tools/clippy/clippy_lints/src/implicit_return.rs:150:66
stack backtrace:
   0: rust_begin_unwind
             at /rustc/fe72845f7bb6a77b9e671e6a4f32fe714962cec4/library/std/src/panicking.rs:515:5
   1: core::panicking::panic_fmt
             at /rustc/fe72845f7bb6a77b9e671e6a4f32fe714962cec4/library/core/src/panicking.rs:92:14
   2: core::panicking::panic
             at /rustc/fe72845f7bb6a77b9e671e6a4f32fe714962cec4/library/core/src/panicking.rs:50:5
   3: <clippy_utils::visitors::visit_break_exprs::V<F> as rustc_hir::intravisit::Visitor>::visit_expr
   4: rustc_hir::intravisit::walk_expr
   5: clippy_lints::implicit_return::lint_implicit_returns
   6: clippy_lints::implicit_return::lint_implicit_returns
   7: <rustc_lint::late::LateLintPassObjects as rustc_lint::passes::LateLintPass>::check_fn
   8: <rustc_lint::late::LateContextAndPass<T> as rustc_hir::intravisit::Visitor>::visit_fn
   9: rustc_hir::intravisit::walk_item
  10: rustc_hir::intravisit::Visitor::visit_nested_item
  11: rustc_hir::intravisit::walk_mod
  12: <rustc_lint::late::LateContextAndPass<T> as rustc_hir::intravisit::Visitor>::visit_mod
  13: rustc_hir::intravisit::Visitor::visit_nested_item
  14: rustc_hir::intravisit::walk_mod
  15: <rustc_lint::late::LateContextAndPass<T> as rustc_hir::intravisit::Visitor>::visit_mod
  16: rustc_hir::intravisit::Visitor::visit_nested_item
  17: rustc_hir::intravisit::walk_mod
  18: <rustc_lint::late::LateContextAndPass<T> as rustc_hir::intravisit::Visitor>::visit_mod
  19: rustc_hir::intravisit::walk_crate
  20: rustc_lint::late::late_lint_pass_crate
  21: rustc_lint::late::late_lint_crate
  22: rustc_data_structures::sync::join
  23: std::panic::catch_unwind
  24: rustc_session::utils::<impl rustc_session::session::Session>::time
  25: rustc_interface::passes::analysis
  26: rustc_middle::dep_graph::<impl rustc_query_system::dep_graph::DepKind for rustc_middle::dep_graph::dep_node::DepKind>::with_deps
  27: rustc_query_system::dep_graph::graph::DepGraph<K>::with_task_impl
  28: rustc_data_structures::stack::ensure_sufficient_stack
  29: rustc_query_system::query::plumbing::force_query_with_job
  30: rustc_query_system::query::plumbing::get_query_impl
  31: <rustc_query_impl::Queries as rustc_middle::ty::query::QueryEngine>::analysis
  32: rustc_interface::queries::<impl rustc_interface::interface::Compiler>::enter
  33: rustc_span::with_source_map
  34: rustc_interface::interface::create_compiler_and_run
  35: scoped_tls::ScopedKey<T>::set
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

error: internal compiler error: unexpected panic
Error: internal compiler error: unexpected panic
note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust-clippy/issues/new

note: Clippy version: clippy 0.1.54 (fe72845 2021-05-16)

query stack during panic:
#0 [analysis] running analysis passes on this crate
end of query stack
```

**Comment by Nashenas88** [comment]
I just ran into the same issue. Seems to be related to 22f8c13cf5650d6c9d6ee7b4f0e88bffba9076ca. CC @Jarcho

**Comment by matthiaskrgr** [comment]
The issue is relatively easy to fix I think (just don't blindly unwrap) but i want able to reduce a proper testcase in the no_std code linked above :/

**Comment by mikerite** [comment]
Got it down to
```
pub async fn f() {
    while let Some(true) = Some(false) {
        match 'x' {
            _ => (),
        }
    }
}
```

**Comment by mikerite** [comment]
```
#[allow(clippy::unused_unit)]
pub async fn f() {
    while false {
        ()
    }
}
```
