### ISSUE TITLE
Clippy is panicing when `async fn` with loop inside does not have resurn value

### ISSUE THREAD

**Issue by Eraden** [rust-lang/rust-clippy#7251]
### Code

This will panic:

```rust
async fn foo() {
  loop {
    break;
  }
}
```

This is ok:

```rust
async fn foo() -> Option<()> {
  #[allow(clippy::never_loop)]
  loop {
    break;
  }
  None
}
```

### Meta

- `cargo clippy -V`: clippy 0.1.54 (f94942d 2021-05-19)
- `rustc -Vv`:
  ```
  rustc 1.54.0-nightly (f94942d84 2021-05-19)
  binary: rustc
  commit-hash: f94942d8421dc4b1da86d07069571ddb43127235
  commit-date: 2021-05-19
  host: x86_64-unknown-linux-gnu
  release: 1.54.0-nightly
  LLVM version: 12.0.1
  ```

### Error output

```
thread 'rustc' panicked at 'called `Option::unwrap()` on a `None` value', src/tools/clippy/clippy_lints/src/implicit_return.rs:150:66
```

<details><summary>Backtrace</summary>
  <p>
  
  ```
thread 'rustc' panicked at 'called `Option::unwrap()` on a `None` value', src/tools/clippy/clippy_lints/src/implicit_return.rs:150:66
stack backtrace:
   0: rust_begin_unwind
             at /rustc/f94942d8421dc4b1da86d07069571ddb43127235/library/std/src/panicking.rs:515:5
   1: core::panicking::panic_fmt
             at /rustc/f94942d8421dc4b1da86d07069571ddb43127235/library/core/src/panicking.rs:92:14
   2: core::panicking::panic
             at /rustc/f94942d8421dc4b1da86d07069571ddb43127235/library/core/src/panicking.rs:50:5
   3: <clippy_utils::visitors::visit_break_exprs::V<F> as rustc_hir::intravisit::Visitor>::visit_expr
   4: clippy_lints::implicit_return::lint_implicit_returns
   5: clippy_lints::implicit_return::lint_implicit_returns
   6: <rustc_lint::late::LateLintPassObjects as rustc_lint::passes::LateLintPass>::check_fn
   7: <rustc_lint::late::LateContextAndPass<T> as rustc_hir::intravisit::Visitor>::visit_fn
   8: rustc_hir::intravisit::walk_item
   9: rustc_hir::intravisit::Visitor::visit_nested_item
  10: rustc_hir::intravisit::walk_mod
  11: <rustc_lint::late::LateContextAndPass<T> as rustc_hir::intravisit::Visitor>::visit_mod
  12: rustc_hir::intravisit::walk_crate
  13: rustc_lint::late::late_lint_pass_crate
  14: rustc_lint::late::late_lint_crate
  15: rustc_data_structures::sync::join
  16: std::panic::catch_unwind
  17: rustc_session::utils::<impl rustc_session::session::Session>::time
  18: rustc_interface::passes::analysis
  19: rustc_middle::dep_graph::<impl rustc_query_system::dep_graph::DepKind for rustc_middle::dep_graph::dep_node::DepKind>::with_deps
  20: rustc_query_system::dep_graph::graph::DepGraph<K>::with_task_impl
  21: rustc_data_structures::stack::ensure_sufficient_stack
  22: rustc_query_system::query::plumbing::force_query_with_job
  23: rustc_query_system::query::plumbing::get_query_impl
  24: <rustc_query_impl::Queries as rustc_middle::ty::query::QueryEngine>::analysis
  25: rustc_interface::passes::QueryContext::enter
  26: rustc_interface::queries::<impl rustc_interface::interface::Compiler>::enter
  27: rustc_span::with_source_map
  28: rustc_interface::interface::create_compiler_and_run
  29: rustc_span::with_session_globals
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust-clippy/issues/new

note: Clippy version: clippy 0.1.54 (f94942d 2021-05-19)

query stack during panic:
#0 [analysis] running analysis passes on this crate
end of query stack
  ```
  
  </p>
</details>

**Comment by Eraden** [comment]
Fixed here: https://github.com/rust-lang/rust-clippy/commit/36be8ba64218a580011fc3507357e1c4c64ed274
