### ISSUE TITLE
Panic at '`LateContext::typeck_results` called outside of body'

### ISSUE THREAD

**Issue by cmichi** [rust-lang/rust-clippy#7455]
I tried this code:

```
git clone https://github.com/paritytech/ink.git
cd ink/
cargo clippy --verbose --all-features --manifest-path crates/env/Cargo.toml -- -D warnings
```

I expected to see this happen: `clippy` should succeed without panicking.

Instead, this happened: 
```
…
thread 'rustc' panicked at '`LateContext::typeck_results` called outside of body', src/tools/clippy/clippy_lints/src/use_self.rs:213:20
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust-clippy/issues/new

note: Clippy version: clippy 0.1.55 (7a16cfc 2021-07-11)
```

### Meta

- `cargo clippy -V`: clippy 0.1.55 (7a16cfc 2021-07-11)
- `rustc -Vv`:
  ```
  rustc 1.46.0-nightly (f455e46ea 2020-06-20)
  binary: rustc
  commit-hash: f455e46eae1a227d735091091144601b467e1565
  commit-date: 2020-06-20
  host: x86_64-unknown-linux-gnu
  release: 1.46.0-nightly
  LLVM version: 10.0
  ```

<details><summary>Backtrace</summary>
  <p>
  
  ```
         Fresh unicode-xid v0.2.2
       Fresh cfg-if v1.0.0
       Fresh version_check v0.9.3
       Fresh tap v1.0.1
       Fresh wyz v0.2.0
       Fresh funty v1.1.0
       Fresh byte-slice-cast v1.0.0
       Fresh arrayvec v0.7.1
       Fresh autocfg v1.0.1
       Fresh opaque-debug v0.3.0
       Fresh block-padding v0.2.1
       Fresh subtle v2.4.0
       Fresh cpufeatures v0.1.5
       Fresh ppv-lite86 v0.2.10
       Fresh cfg-if v0.1.10
       Fresh memory_units v0.4.0
       Fresh keccak v0.1.0
       Fresh sp-std v3.0.0
       Fresh arrayref v0.3.6
       Fresh static_assertions v1.1.0
       Fresh paste v1.0.5
       Fresh ink_prelude v3.0.0-rc3 (/tmp/ink/crates/prelude)
       Fresh proc-macro2 v1.0.27
       Fresh typenum v1.13.0
       Fresh radium v0.6.2
       Fresh libc v0.2.98
       Fresh quote v1.0.9
       Fresh generic-array v0.14.4
       Fresh bitvec v0.20.4
       Fresh getrandom v0.2.3
       Fresh wee_alloc v0.4.5
       Fresh syn v1.0.73
       Fresh digest v0.9.0
       Fresh block-buffer v0.9.0
       Fresh rand_core v0.6.3
       Fresh crypto-mac v0.8.0
       Fresh num-traits v0.2.14
       Fresh ink_allocator v3.0.0-rc3 (/tmp/ink/crates/allocator)
       Fresh serde_derive v1.0.126
       Fresh thiserror-impl v1.0.26
       Fresh impl-trait-for-tuples v0.2.1
       Fresh derive_more v0.99.16
       Fresh blake2 v0.9.1
       Fresh integer-sqrt v0.1.5
       Fresh sha3 v0.9.1
       Fresh rand_chacha v0.3.1
       Fresh sha2 v0.9.5
       Fresh sp-debug-derive v3.0.0
       Fresh thiserror v1.0.26
       Fresh serde v1.0.126
       Fresh rand v0.8.4
       Fresh toml v0.5.8
       Fresh impl-serde v0.3.1
       Fresh proc-macro-crate v1.0.0
       Fresh proc-macro-crate v0.1.5
       Fresh parity-scale-codec-derive v2.2.0
       Fresh scale-info-derive v0.4.0
       Fresh parity-scale-codec v2.2.0
       Fresh scale-info v0.6.0
       Fresh sp-arithmetic v3.0.0
       Fresh ink_engine v3.0.0-rc3 (/tmp/ink/crates/engine)
       Fresh ink_primitives v3.0.0-rc3 (/tmp/ink/crates/primitives)
       Fresh ink_metadata v3.0.0-rc3 (/tmp/ink/crates/metadata)
    Checking ink_env v3.0.0-rc3 (/tmp/ink/crates/env)
     Running `sccache /home/michi/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/bin/clippy-driver rustc --crate-name ink_env --edition=2018 crates/env/src/lib.rs --error-format=json --json=diagnostic-rendered-ansi --crate-type lib --emit=dep-info,metadata -C embed-bitcode=no -C debuginfo=2 --cfg 'feature="blake2"' --cfg 'feature="default"' --cfg 'feature="ink-debug"' --cfg 'feature="ink-experimental-engine"' --cfg 'feature="ink_engine"' --cfg 'feature="ink_metadata"' --cfg 'feature="rand"' --cfg 'feature="scale-info"' --cfg 'feature="sha2"' --cfg 'feature="sha3"' --cfg 'feature="std"' -C metadata=bea0644b70c5b615 -C extra-filename=-bea0644b70c5b615 --out-dir /tmp/ink/target/debug/deps -C incremental=/tmp/ink/target/debug/incremental -L dependency=/tmp/ink/target/debug/deps --extern arrayref=/tmp/ink/target/debug/deps/libarrayref-8b0492b6c718a608.rmeta --extern blake2=/tmp/ink/target/debug/deps/libblake2-f284ff27378d6feb.rmeta --extern cfg_if=/tmp/ink/target/debug/deps/libcfg_if-621b92c8c202d759.rmeta --extern derive_more=/tmp/ink/target/debug/deps/libderive_more-bb2cca2b152bc737.so --extern ink_allocator=/tmp/ink/target/debug/deps/libink_allocator-752e42b68041ed82.rmeta --extern ink_engine=/tmp/ink/target/debug/deps/libink_engine-f7394986ca0c25a5.rmeta --extern ink_metadata=/tmp/ink/target/debug/deps/libink_metadata-7a665dddcc08014c.rmeta --extern ink_prelude=/tmp/ink/target/debug/deps/libink_prelude-1b19cd9a796fa664.rmeta --extern ink_primitives=/tmp/ink/target/debug/deps/libink_primitives-77a7a63be1575654.rmeta --extern num_traits=/tmp/ink/target/debug/deps/libnum_traits-164152519441692e.rmeta --extern scale=/tmp/ink/target/debug/deps/libparity_scale_codec-076e4ee0099cd52b.rmeta --extern paste=/tmp/ink/target/debug/deps/libpaste-e38a6a68334ba7ca.so --extern rand=/tmp/ink/target/debug/deps/librand-4eaee687b84da4bf.rmeta --extern scale_info=/tmp/ink/target/debug/deps/libscale_info-43001ece80acec57.rmeta --extern sha2=/tmp/ink/target/debug/deps/libsha2-4f763afe1773168b.rmeta --extern sha3=/tmp/ink/target/debug/deps/libsha3-441d27c18c4994d7.rmeta --extern sp_arithmetic=/tmp/ink/target/debug/deps/libsp_arithmetic-2cbb109db6077f15.rmeta --extern static_assertions=/tmp/ink/target/debug/deps/libstatic_assertions-b8fd312976fd468b.rmeta`
thread 'rustc' panicked at '`LateContext::typeck_results` called outside of body', src/tools/clippy/clippy_lints/src/use_self.rs:213:20
stack backtrace:
   0: rust_begin_unwind
             at /rustc/7a16cfcffc58cd6994984a2c014b0cc27ed8f66b/library/std/src/panicking.rs:515:5
   1: core::panicking::panic_fmt
             at /rustc/7a16cfcffc58cd6994984a2c014b0cc27ed8f66b/library/core/src/panicking.rs:92:14
   2: core::option::expect_failed
             at /rustc/7a16cfcffc58cd6994984a2c014b0cc27ed8f66b/library/core/src/option.rs:1243:5
   3: rustc_lint::context::LateContext::typeck_results
   4: <clippy_lints::use_self::UseSelf as rustc_lint::passes::LateLintPass>::check_ty
   5: <rustc_lint::late::LateLintPassObjects as rustc_lint::passes::LateLintPass>::check_ty
   6: <rustc_lint::late::LateContextAndPass<T> as rustc_hir::intravisit::Visitor>::visit_ty
   7: rustc_hir::intravisit::walk_ty
   8: rustc_hir::intravisit::walk_item
   9: rustc_hir::intravisit::Visitor::visit_nested_item
  10: <rustc_lint::late::LateContextAndPass<T> as rustc_hir::intravisit::Visitor>::visit_stmt
  11: rustc_hir::intravisit::walk_block
  12: <rustc_lint::late::LateContextAndPass<T> as rustc_hir::intravisit::Visitor>::visit_block
  13: <rustc_lint::late::LateContextAndPass<T> as rustc_hir::intravisit::Visitor>::visit_expr
  14: <rustc_lint::late::LateContextAndPass<T> as rustc_hir::intravisit::Visitor>::visit_nested_body
  15: <rustc_lint::late::LateContextAndPass<T> as rustc_hir::intravisit::Visitor>::visit_fn
  16: rustc_hir::intravisit::walk_impl_item
  17: rustc_hir::intravisit::Visitor::visit_nested_impl_item
  18: rustc_hir::intravisit::walk_impl_item_ref
  19: rustc_hir::intravisit::walk_item
  20: rustc_hir::intravisit::Visitor::visit_nested_item
  21: rustc_hir::intravisit::walk_mod
  22: <rustc_lint::late::LateContextAndPass<T> as rustc_hir::intravisit::Visitor>::visit_mod
  23: rustc_hir::intravisit::Visitor::visit_nested_item
  24: rustc_hir::intravisit::walk_mod
  25: <rustc_lint::late::LateContextAndPass<T> as rustc_hir::intravisit::Visitor>::visit_mod
  26: rustc_hir::intravisit::Visitor::visit_nested_item
  27: rustc_hir::intravisit::walk_mod
  28: <rustc_lint::late::LateContextAndPass<T> as rustc_hir::intravisit::Visitor>::visit_mod
  29: rustc_hir::intravisit::Visitor::visit_nested_item
  30: rustc_hir::intravisit::walk_mod
  31: <rustc_lint::late::LateContextAndPass<T> as rustc_hir::intravisit::Visitor>::visit_mod
  32: rustc_hir::intravisit::walk_crate
  33: rustc_lint::late::late_lint_pass_crate
  34: rustc_lint::late::late_lint_crate
  35: rustc_session::utils::<impl rustc_session::session::Session>::time
  36: <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
  37: rustc_session::utils::<impl rustc_session::session::Session>::time
  38: rustc_interface::passes::analysis
  39: rustc_middle::dep_graph::<impl rustc_query_system::dep_graph::DepKind for rustc_middle::dep_graph::dep_node::DepKind>::with_deps
  40: rustc_query_system::dep_graph::graph::DepGraph<K>::with_task_impl
  41: rustc_query_system::dep_graph::graph::DepGraph<K>::with_eval_always_task
  42: rustc_data_structures::stack::ensure_sufficient_stack
  43: rustc_query_system::query::plumbing::force_query_with_job
  44: rustc_query_system::query::plumbing::get_query_impl
  45: <rustc_query_impl::Queries as rustc_middle::ty::query::QueryEngine>::analysis
  46: rustc_interface::queries::<impl rustc_interface::interface::Compiler>::enter
  47: rustc_span::with_source_map
  48: rustc_interface::interface::create_compiler_and_run
  49: scoped_tls::ScopedKey<T>::set
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust-clippy/issues/new

note: Clippy version: clippy 0.1.55 (7a16cfc 2021-07-11)

query stack during panic:
#0 [analysis] running analysis passes on this crate
end of query stack
error: could not compile `ink_env`

Caused by:
  process didn't exit successfully: `sccache /home/michi/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/bin/clippy-driver rustc --crate-name ink_env --edition=2018 crates/env/src/lib.rs --error-format=json --json=diagnostic-rendered-ansi --crate-type lib --emit=dep-info,metadata -C embed-bitcode=no -C debuginfo=2 --cfg 'feature="blake2"' --cfg 'feature="default"' --cfg 'feature="ink-debug"' --cfg 'feature="ink-experimental-engine"' --cfg 'feature="ink_engine"' --cfg 'feature="ink_metadata"' --cfg 'feature="rand"' --cfg 'feature="scale-info"' --cfg 'feature="sha2"' --cfg 'feature="sha3"' --cfg 'feature="std"' -C metadata=bea0644b70c5b615 -C extra-filename=-bea0644b70c5b615 --out-dir /tmp/ink/target/debug/deps -C incremental=/tmp/ink/target/debug/incremental -L dependency=/tmp/ink/target/debug/deps --extern arrayref=/tmp/ink/target/debug/deps/libarrayref-8b0492b6c718a608.rmeta --extern blake2=/tmp/ink/target/debug/deps/libblake2-f284ff27378d6feb.rmeta --extern cfg_if=/tmp/ink/target/debug/deps/libcfg_if-621b92c8c202d759.rmeta --extern derive_more=/tmp/ink/target/debug/deps/libderive_more-bb2cca2b152bc737.so --extern ink_allocator=/tmp/ink/target/debug/deps/libink_allocator-752e42b68041ed82.rmeta --extern ink_engine=/tmp/ink/target/debug/deps/libink_engine-f7394986ca0c25a5.rmeta --extern ink_metadata=/tmp/ink/target/debug/deps/libink_metadata-7a665dddcc08014c.rmeta --extern ink_prelude=/tmp/ink/target/debug/deps/libink_prelude-1b19cd9a796fa664.rmeta --extern ink_primitives=/tmp/ink/target/debug/deps/libink_primitives-77a7a63be1575654.rmeta --extern num_traits=/tmp/ink/target/debug/deps/libnum_traits-164152519441692e.rmeta --extern scale=/tmp/ink/target/debug/deps/libparity_scale_codec-076e4ee0099cd52b.rmeta --extern paste=/tmp/ink/target/debug/deps/libpaste-e38a6a68334ba7ca.so --extern rand=/tmp/ink/target/debug/deps/librand-4eaee687b84da4bf.rmeta --extern scale_info=/tmp/ink/target/debug/deps/libscale_info-43001ece80acec57.rmeta --extern sha2=/tmp/ink/target/debug/deps/libsha2-4f763afe1773168b.rmeta --extern sha3=/tmp/ink/target/debug/deps/libsha3-441d27c18c4994d7.rmeta --extern sp_arithmetic=/tmp/ink/target/debug/deps/libsp_arithmetic-2cbb109db6077f15.rmeta --extern static_assertions=/tmp/ink/target/debug/deps/libstatic_assertions-b8fd312976fd468b.rmeta` (exit status: 101)
  ```
  
  </p>
</details>

**Comment by cmichi** [comment]
Just discovered this is a duplicate of https://github.com/rust-lang/rust-clippy/issues/7423.
