### ISSUE TITLE
thread 'rustc' panicked at 'Found unstable fingerprints for evaluate_obligation(6bba2fe2781ce34a-6081bcd845d1e7e1): Ok(EvaluatedToOk)'

### ISSUE THREAD

**Issue by ekroon** [rust-lang/rust-clippy#7970]
### Code

```shell
git clone https://github.com/ekroon/roapi.git
git checkout clippy-internal-error
cargo clippy
cargo fmt 
cargo clippy
```

### Meta

**Rust version (`rustc -Vv`):**
```
rustc 1.56.1 (59eed8a2a 2021-11-01)
binary: rustc
commit-hash: 59eed8a2aac0230a8b53e89d4e99d55912ba6b35
commit-date: 2021-11-01
host: x86_64-apple-darwin
release: 1.56.1
LLVM version: 13.0.0
```

### Error output

```
thread 'rustc' panicked at 'Found unstable fingerprints for evaluate_obligation(6bba2fe2781ce34a-6081bcd845d1e7e1): Ok(EvaluatedToOk)', /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/compiler/rustc_query_system/src/query/plumbing.rs:644:13
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust-clippy/issues/new

note: Clippy version: clippy 0.1.56 (59eed8a2 2021-11-01)

query stack during panic:
#0 [evaluate_obligation] evaluating trait selection obligation `hyper::proto::h1::dispatch::Server<axum::Router, hyper::Body>: std::marker::Send`
#1 [typeck] type-checking `startup::<impl at roapi-http/src/startup.rs:18:1: 56:2>::run_until_stopped`
end of query stack
```

<details><summary>Backtrace</summary>
  <p>
  
  ```
  thread 'rustc' panicked at 'Found unstable fingerprints for evaluate_obligation(6bba2fe2781ce34a-6081bcd845d1e7e1): Ok(EvaluatedToOk)', /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/compiler/rustc_query_system/src/query/plumbing.rs:644:13
stack backtrace:
   0: _rust_begin_unwind
   1: std::panicking::begin_panic_fmt
   2: rustc_query_system::query::plumbing::incremental_verify_ich
   3: rustc_query_system::query::plumbing::load_from_disk_and_cache_in_memory
   4: rustc_data_structures::stack::ensure_sufficient_stack
   5: rustc_query_system::query::plumbing::get_query_impl
   6: <rustc_query_impl::Queries as rustc_middle::ty::query::QueryEngine>::evaluate_obligation
   7: <rustc_infer::infer::InferCtxt as rustc_trait_selection::traits::query::evaluate_obligation::InferCtxtExt>::evaluate_obligation
   8: <rustc_infer::infer::InferCtxt as rustc_trait_selection::traits::query::evaluate_obligation::InferCtxtExt>::evaluate_obligation_no_overflow
   9: rustc_trait_selection::traits::fulfill::FulfillProcessor::process_trait_obligation
  10: rustc_trait_selection::traits::fulfill::FulfillProcessor::progress_changed_obligations
  11: rustc_data_structures::obligation_forest::ObligationForest<O>::process_obligations
  12: rustc_trait_selection::traits::fulfill::FulfillmentContext::select
  13: <rustc_trait_selection::traits::fulfill::FulfillmentContext as rustc_infer::traits::engine::TraitEngine>::select_with_constness_where_possible
  14: rustc_typeck::check::fn_ctxt::checks::<impl rustc_typeck::check::fn_ctxt::FnCtxt>::check_argument_types
  15: rustc_typeck::check::callee::<impl rustc_typeck::check::fn_ctxt::FnCtxt>::confirm_builtin_call
  16: rustc_typeck::check::callee::<impl rustc_typeck::check::fn_ctxt::FnCtxt>::check_call
  17: rustc_typeck::check::expr::<impl rustc_typeck::check::fn_ctxt::FnCtxt>::check_expr_kind
  18: rustc_typeck::check::expr::<impl rustc_typeck::check::fn_ctxt::FnCtxt>::check_expr_with_expectation
  19: rustc_typeck::check::fn_ctxt::checks::<impl rustc_typeck::check::fn_ctxt::FnCtxt>::check_argument_types
  20: rustc_typeck::check::callee::<impl rustc_typeck::check::fn_ctxt::FnCtxt>::confirm_builtin_call
  21: rustc_typeck::check::callee::<impl rustc_typeck::check::fn_ctxt::FnCtxt>::check_call
  22: rustc_typeck::check::expr::<impl rustc_typeck::check::fn_ctxt::FnCtxt>::check_expr_kind
  23: rustc_typeck::check::expr::<impl rustc_typeck::check::fn_ctxt::FnCtxt>::check_expr_with_expectation
  24: rustc_typeck::check::fn_ctxt::checks::<impl rustc_typeck::check::fn_ctxt::FnCtxt>::check_block_with_expected
  25: rustc_typeck::check::expr::<impl rustc_typeck::check::fn_ctxt::FnCtxt>::check_expr_with_expectation
  26: rustc_typeck::check::_match::<impl rustc_typeck::check::fn_ctxt::FnCtxt>::demand_scrutinee_type
  27: rustc_typeck::check::_match::<impl rustc_typeck::check::fn_ctxt::FnCtxt>::check_match
  28: rustc_typeck::check::expr::<impl rustc_typeck::check::fn_ctxt::FnCtxt>::check_expr_kind
  29: rustc_typeck::check::expr::<impl rustc_typeck::check::fn_ctxt::FnCtxt>::check_expr_with_expectation
  30: rustc_typeck::check::fn_ctxt::checks::<impl rustc_typeck::check::fn_ctxt::FnCtxt>::check_stmt
  31: rustc_typeck::check::fn_ctxt::checks::<impl rustc_typeck::check::fn_ctxt::FnCtxt>::check_block_with_expected
  32: rustc_typeck::check::fn_ctxt::checks::<impl rustc_typeck::check::fn_ctxt::FnCtxt>::check_block_no_value
  33: rustc_typeck::check::expr::<impl rustc_typeck::check::fn_ctxt::FnCtxt>::check_expr_kind
  34: rustc_typeck::check::expr::<impl rustc_typeck::check::fn_ctxt::FnCtxt>::check_expr_with_expectation
  35: rustc_typeck::check::_match::<impl rustc_typeck::check::fn_ctxt::FnCtxt>::check_match
  36: rustc_typeck::check::expr::<impl rustc_typeck::check::fn_ctxt::FnCtxt>::check_expr_kind
  37: rustc_typeck::check::expr::<impl rustc_typeck::check::fn_ctxt::FnCtxt>::check_expr_with_expectation
  38: rustc_typeck::check::fn_ctxt::checks::<impl rustc_typeck::check::fn_ctxt::FnCtxt>::check_argument_types
  39: rustc_typeck::check::callee::<impl rustc_typeck::check::fn_ctxt::FnCtxt>::confirm_builtin_call
  40: rustc_typeck::check::callee::<impl rustc_typeck::check::fn_ctxt::FnCtxt>::check_call
  41: rustc_typeck::check::expr::<impl rustc_typeck::check::fn_ctxt::FnCtxt>::check_expr_kind
  42: rustc_typeck::check::expr::<impl rustc_typeck::check::fn_ctxt::FnCtxt>::check_expr_with_expectation
  43: rustc_typeck::check::_match::<impl rustc_typeck::check::fn_ctxt::FnCtxt>::demand_scrutinee_type
  44: rustc_typeck::check::_match::<impl rustc_typeck::check::fn_ctxt::FnCtxt>::check_match
  45: rustc_typeck::check::expr::<impl rustc_typeck::check::fn_ctxt::FnCtxt>::check_expr_kind
  46: rustc_typeck::check::expr::<impl rustc_typeck::check::fn_ctxt::FnCtxt>::check_expr_with_expectation
  47: rustc_typeck::check::fn_ctxt::checks::<impl rustc_typeck::check::fn_ctxt::FnCtxt>::check_argument_types
  48: rustc_typeck::check::callee::<impl rustc_typeck::check::fn_ctxt::FnCtxt>::confirm_builtin_call
  49: rustc_typeck::check::callee::<impl rustc_typeck::check::fn_ctxt::FnCtxt>::check_call
  50: rustc_typeck::check::expr::<impl rustc_typeck::check::fn_ctxt::FnCtxt>::check_expr_kind
  51: rustc_typeck::check::expr::<impl rustc_typeck::check::fn_ctxt::FnCtxt>::check_expr_with_expectation
  52: rustc_typeck::check::fn_ctxt::checks::<impl rustc_typeck::check::fn_ctxt::FnCtxt>::check_block_with_expected
  53: rustc_typeck::check::expr::<impl rustc_typeck::check::fn_ctxt::FnCtxt>::check_expr_with_expectation
  54: rustc_typeck::check::expr::<impl rustc_typeck::check::fn_ctxt::FnCtxt>::check_expr_with_expectation
  55: rustc_typeck::check::fn_ctxt::checks::<impl rustc_typeck::check::fn_ctxt::FnCtxt>::check_block_with_expected
  56: rustc_typeck::check::expr::<impl rustc_typeck::check::fn_ctxt::FnCtxt>::check_expr_with_expectation
  57: rustc_typeck::check::expr::<impl rustc_typeck::check::fn_ctxt::FnCtxt>::check_return_expr
  58: rustc_typeck::check::check::check_fn
  59: rustc_typeck::check::closure::<impl rustc_typeck::check::fn_ctxt::FnCtxt>::check_expr_closure
  60: rustc_typeck::check::expr::<impl rustc_typeck::check::fn_ctxt::FnCtxt>::check_expr_kind
  61: rustc_typeck::check::expr::<impl rustc_typeck::check::fn_ctxt::FnCtxt>::check_expr_with_expectation
  62: rustc_typeck::check::fn_ctxt::checks::<impl rustc_typeck::check::fn_ctxt::FnCtxt>::check_argument_types
  63: rustc_typeck::check::callee::<impl rustc_typeck::check::fn_ctxt::FnCtxt>::confirm_builtin_call
  64: rustc_typeck::check::callee::<impl rustc_typeck::check::fn_ctxt::FnCtxt>::check_call
  65: rustc_typeck::check::expr::<impl rustc_typeck::check::fn_ctxt::FnCtxt>::check_expr_kind
  66: rustc_typeck::check::expr::<impl rustc_typeck::check::fn_ctxt::FnCtxt>::check_expr_with_expectation
  67: rustc_typeck::check::expr::<impl rustc_typeck::check::fn_ctxt::FnCtxt>::check_return_expr
  68: rustc_typeck::check::check::check_fn
  69: rustc_infer::infer::InferCtxtBuilder::enter
  70: rustc_typeck::check::typeck
  71: rustc_query_system::dep_graph::graph::DepGraph<K>::with_task_impl
  72: rustc_data_structures::stack::ensure_sufficient_stack
  73: rustc_query_system::query::plumbing::force_query_with_job
  74: rustc_query_system::query::plumbing::force_query_impl
  75: rustc_query_impl::query_callbacks::typeck::force_from_dep_node
  76: rustc_query_system::dep_graph::graph::DepGraph<K>::try_mark_previous_green
  77: rustc_query_system::dep_graph::graph::DepGraph<K>::try_mark_previous_green
  78: rustc_query_system::dep_graph::graph::DepGraph<K>::try_mark_previous_green
  79: rustc_query_system::dep_graph::graph::DepGraph<K>::try_mark_previous_green
  80: rustc_query_system::dep_graph::graph::DepGraph<K>::try_mark_previous_green
  81: rustc_query_system::dep_graph::graph::DepGraph<K>::try_mark_previous_green
  82: rustc_query_system::dep_graph::graph::DepGraph<K>::try_mark_previous_green
  83: rustc_query_system::dep_graph::graph::DepGraph<K>::try_mark_green
  84: rustc_query_system::query::plumbing::ensure_must_run
  85: <rustc_query_impl::Queries as rustc_middle::ty::query::QueryEngine>::check_mod_item_types
  86: rustc_session::utils::<impl rustc_session::session::Session>::time
  87: rustc_typeck::check_crate
  88: rustc_interface::passes::analysis
  89: rustc_query_system::dep_graph::graph::DepGraph<K>::with_task_impl
  90: rustc_data_structures::stack::ensure_sufficient_stack
  91: rustc_query_system::query::plumbing::force_query_with_job
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust-clippy/issues/new

note: Clippy version: clippy 0.1.56 (59eed8a2 2021-11-01)

query stack during panic:
#0 [evaluate_obligation] evaluating trait selection obligation `hyper::proto::h1::dispatch::Server<axum::Router, hyper::Body>: std::marker::Send`
#1 [typeck] type-checking `startup::<impl at roapi-http/src/startup.rs:18:1: 56:2>::run_until_stopped`
#2 [analysis] running analysis passes on this crate
end of query stack
  ```
  
  </p>
</details>

**Comment by ekroon** [comment]
Seems to be fixed in `1.57.0-beta.3`

**Comment by matthiaskrgr** [comment]
Thanks for the ticket.
This is a rustc problem, there is nothing the clippy folks can do about that
https://github.com/rust-lang/rust/issues?q=is%3Aissue+%22Found+unstable+fingerprints%22+

I was not able to repro the rust crash though
````
   Updating git repository `https://github.com/tower-rs/tower-http.git`
error: failed to get `tower-http` as a dependency of package `roapi-http v0.4.4 (/tmp/roapi/roapi-http)`

Caused by:
  failed to load source for dependency `tower-http`

Caused by:
  Unable to update https://github.com/tower-rs/tower-http.git?branch=cors#44b79e09

Caused by:
  object not found - no match for id (44b79e09fe0a53f2abd0a6775deef264f3d2af69); class=Odb (9); code=NotFound (-3)
````
closng.

**Comment by ekroon** [comment]
I see, sorry for that. That is caused by a missing git dependency.
