### ISSUE TITLE
ICE on undocumented_unsafe_blocks lint

### ISSUE THREAD

**Issue by pymongo** [rust-lang/rust-clippy#7979]
```
73 ~     // Safety: ...
74 +     unsafe {
   |

thread 'rustc' panicked at 'internal error: entered unreachable code: attempted to remap an already remapped filename', compiler/rustc_span/src/source_map.rs:1107:34
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust-clippy/issues/new

note: Clippy version: clippy 0.1.58 (891ca5f 2021-11-15)

query stack during panic:
#0 [analysis] running analysis passes on this crate
```

## step to reproduce
1. git clone https://github.com/pymongo/leetcode-rust
2. git checkout 5432649be7c7fb82e24c5eac83585fe4936e1b77
3. cargo clippy

### Meta

**Rust version (`rustc -Vv`):**

```
rustc 1.58.0-nightly (891ca5f63 2021-11-15)
binary: rustc
commit-hash: 891ca5f63c3b3cfe3939710a728671243e881ed6
commit-date: 2021-11-15
host: x86_64-unknown-linux-gnu
release: 1.58.0-nightly
LLVM version: 13.0.0
```

### If I apply some `// Safety: ...` line to solve undocumented_unsafe_blocks lint, then cause another ICE panic

```
    Checking leetcode-rust v0.1.1 (/home/w/repos/my_repos/leetcode-rust)
thread 'rustc' panicked at 'assertion failed: self.start_pos.to_u32() + total_extra_bytes <= bpos.to_u32()', compiler/rustc_span/src/lib.rs:1677:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust-clippy/issues/new

note: Clippy version: clippy 0.1.58 (891ca5f 2021-11-15)
```

**Comment by pymongo** [comment]
@ rustbot label +I-ICE

**Comment by pymongo** [comment]
I am trying to find a minimal reproduce code, but when I copy some unsafe code from my leetcode-rust repo to a single file cargo project, then this ICE was not reproduce. So I think currenly the only way to reproduce this bug/ICE is to clone my leetcode-rust repo

**Comment by hellow554** [comment]
Here's the MCVE:

```rust
#![warn(clippy::restriction)]

pub fn print_binary_tree() {
    println!("{}", unsafe {
        String::from_utf8_unchecked(vec![])
    });
}
```

**Comment by hellow554** [comment]
Judging from the backtrace it is probably this line:

https://github.com/rust-lang/rust-clippy/blob/5b1b65b876b500e15de45155a04d055ff3cd126f/clippy_lints/src/undocumented_unsafe_blocks.rs#L147
