### ISSUE TITLE
Regression: raw pointer slice cast causes ICE

### ISSUE THREAD

**Issue by CAD97** [rust-lang/rust-clippy#8708]
### Summary

```rust
pub fn cast(x: *mut [u16]) -> *mut [u8] {
    x as *mut _
}
```

```
D:\repos\cad97\playground> cargo +stable clippy
    Finished dev [unoptimized + debuginfo] target(s) in 0.15s
D:\repos\cad97\playground> cargo +nightly clippy
    Checking playground v0.1.0 (D:\repos\cad97\playground)
thread 'rustc' panicked at 'internal error: entered unreachable code: expr should be a cast as checked by expr_cast_chain_tys', src\tools\clippy\clippy_lints\src\casts\cast_slice_different_sizes.rs:64:34
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust-clippy/issues/new

note: Clippy version: clippy 0.1.62 (e7575f96 2022-04-14)

query stack during panic:
#0 [analysis] running analysis passes on this crate
end of query stack
error: could not compile `playground`
```

@rustbot modify labels: +regression-from-stable-to-nightly +regression-from-stable-to-beta

### Version

```text
rustc 1.62.0-nightly (e7575f967 2022-04-14)
binary: rustc
commit-hash: e7575f9670f3c837def3d186ae09366c75c7632e
commit-date: 2022-04-14
host: x86_64-pc-windows-msvc
release: 1.62.0-nightly
LLVM version: 14.0.0
```

### Error output

<details><summary>Backtrace</summary>
  <p>

  ```
thread 'rustc' panicked at 'internal error: entered unreachable code: expr should be a cast as checked by expr_cast_chain_tys', src\tools\clippy\clippy_lints\src\casts\cast_slice_different_sizes.rs:64:34
stack backtrace:
   0:     0x7ffcb0a097ff - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::hcb66cd6e4a888daf
   1:     0x7ffcb0a35eda - core::fmt::write::h2711f328a6658074
   2:     0x7ffcb09fbea9 - <std::io::IoSliceMut as core::fmt::Debug>::fmt::h7d18a60dbc9a3a29
   3:     0x7ffcb0a0cdfb - std::panicking::default_hook::h7ea169da84a3db7b
   4:     0x7ffcb0a0c9ee - std::panicking::default_hook::h7ea169da84a3db7b
   5:     0x7ff7233aac51 - <unknown>
   6:     0x7ffcb0a0d6da - std::panicking::rust_panic_with_hook::haed8da8f0631eeb7
   7:     0x7ffcb0a0d42d - <std::panicking::begin_panic_handler::StrPanicPayload as core::panic::BoxMeUp>::get::hed3ca6aea0d30925
   8:     0x7ffcb0a0a107 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::hcb66cd6e4a888daf
   9:     0x7ffcb0a0d109 - rust_begin_unwind
  10:     0x7ffcb0a73e45 - core::panicking::panic_fmt::h38421ab7701e5f81
  11:     0x7ff7235a11f2 - <unknown>
  12:     0x7ffc8dc2aea1 - rustc_middle[2aac09aac179ac40]::lint::struct_lint_level::struct_lint_level_impl
  13:     0x7ff72365b3f6 - <unknown>
  14:     0x7ff7235d50a3 - <unknown>
  15:     0x7ffc8d7d9813 - <rustc_lint[ab25e93c39d09558]::late::LateLintPassObjects as rustc_lint[ab25e93c39d09558]::passes::LateLintPass>::check_expr
  16:     0x7ffc89687716 - <rustc_interface[9c157cdd4792df79]::queries::Linker>::link
  17:     0x7ffc89644331 - <rustc_interface[9c157cdd4792df79]::queries::Linker>::link
  18:     0x7ffc89689b34 - <rustc_interface[9c157cdd4792df79]::queries::Linker>::link
  19:     0x7ffc89645cbc - <rustc_interface[9c157cdd4792df79]::queries::Linker>::link
  20:     0x7ffc89642ecc - <rustc_interface[9c157cdd4792df79]::queries::Linker>::link
  21:     0x7ffc89641d55 - <rustc_interface[9c157cdd4792df79]::queries::Linker>::link
  22:     0x7ffc89637e25 - <rustc_interface[9c157cdd4792df79]::queries::Linker>::link
  23:     0x7ffc8963820c - <rustc_interface[9c157cdd4792df79]::queries::Linker>::link
  24:     0x7ffc896453c9 - <rustc_interface[9c157cdd4792df79]::queries::Linker>::link
  25:     0x7ffc8963b300 - <rustc_interface[9c157cdd4792df79]::queries::Linker>::link
  26:     0x7ffc895e4977 - rustc_interface[9c157cdd4792df79]::passes::analysis
  27:     0x7ffc8cc9e79e - <rustc_query_impl[92a0e8d32005c9f5]::queries::global_backend_features as rustc_query_system[f01b0922df95c9f8]::query::config::QueryDescription<rustc_query_impl[92a0e8d32005c9f5]::plumbing::QueryCtxt>>::describe
  28:     0x7ffc8cd17dbf - <&rustc_index[dd7e5a48b09a788b]::vec::IndexVec<rustc_middle[2aac09aac179ac40]::mir::Promoted, rustc_middle[2aac09aac179ac40]::mir::Body> as rustc_serialize[2f3d4e803a806232]::serialize::Decodable<rustc_query_impl[92a0e8d32005c9f5]::on_disk_cache::CacheDecoder>>::decode
  29:     0x7ffc8ce7380b - <&rustc_index[dd7e5a48b09a788b]::vec::IndexVec<rustc_middle[2aac09aac179ac40]::mir::Promoted, rustc_middle[2aac09aac179ac40]::mir::Body> as rustc_serialize[2f3d4e803a806232]::serialize::Decodable<rustc_query_impl[92a0e8d32005c9f5]::on_disk_cache::CacheDecoder>>::decode
  30:     0x7ffc8cf29616 - <&rustc_index[dd7e5a48b09a788b]::vec::IndexVec<rustc_middle[2aac09aac179ac40]::mir::Promoted, rustc_middle[2aac09aac179ac40]::mir::Body> as rustc_serialize[2f3d4e803a806232]::serialize::Decodable<rustc_query_impl[92a0e8d32005c9f5]::on_disk_cache::CacheDecoder>>::decode
  31:     0x7ffc894b888f - <rustc_driver[8e4916da9438242b]::args::Error as core[6c1fd69403610879]::fmt::Debug>::fmt
  32:     0x7ffc8948e5a7 - <rustc_typeck[aa57359b1a13d717]::collect::const_evaluatable_predicates_of::ConstCollector as rustc_hir[d89e430c0dd5ad20]::intravisit::Visitor>::visit_const_param_default
  33:     0x7ffc89509be5 - rustc_driver[8e4916da9438242b]::pretty::print_after_hir_lowering
  34:     0x7ffc8948f8e6 - <rustc_typeck[aa57359b1a13d717]::collect::const_evaluatable_predicates_of::ConstCollector as rustc_hir[d89e430c0dd5ad20]::intravisit::Visitor>::visit_const_param_default
  35:     0x7ffc894bb8c6 - <rustc_driver[8e4916da9438242b]::args::Error as core[6c1fd69403610879]::fmt::Debug>::fmt
  36:     0x7ffc894bc688 - <rustc_driver[8e4916da9438242b]::args::Error as core[6c1fd69403610879]::fmt::Debug>::fmt
  37:     0x7ffcb0a1d30c - std::sys::windows::thread::Thread::new::hab24d75508209865
  38:     0x7ffd281c7034 - BaseThreadInitThunk
  39:     0x7ffd28f62651 - RtlUserThreadStart
  ```

  </p>
</details>

**Comment by asquared31415** [comment]
I caused this in #8445 whoops
@rustbot claim
