### ISSUE TITLE
[bug]  compile panicked unexpectly at rustc_metadata

### ISSUE THREAD

**Issue by lyang24** [rust-lang/rust-clippy#8808]
this happens on a cargo build with one of our internal crates
```
thread 'rustc' panicked at 'called `Option::unwrap()` on a `None` value', compiler/rustc_metadata/src/rmeta/def_path_hash_map.rs:18:85
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust-clippy/issues/new

note: Clippy version: clippy 0.1.60 (7737e0b 2022-04-04)

query stack during panic:
#0 [evaluate_obligation] evaluating trait selection obligation `impl core::future::future::Future<Output = connection_pool::endpoint_pool::EndpointPool<pool_roblox::PoolConnectionManager>>: core::marker::Send`
#1 [analysis] running analysis passes on this crate
end of query stack
error: could not compile `cockroachdb-pool`
warning: build failed, waiting for other jobs to finish...
thread 'rustc' panicked at 'called `Option::unwrap()` on a `None` value', compiler/rustc_metadata/src/rmeta/def_path_hash_map.rs:18:85
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust-clippy/issues/new

note: Clippy version: clippy 0.1.60 (7737e0b 2022-04-04)

query stack during panic:
#0 [evaluate_obligation] evaluating trait selection obligation `impl core::future::future::Future<Output = connection_pool::endpoint_pool::EndpointPool<cockroachdb_pool::pool_roblox::PoolConnectionManager>>: core::marker::Send`
#1 [analysis] running analysis passes on this crate
end of query stack
error: build failed
make: *** [Makefile:22: lint] Error 101
```

**Comment by giraffate** [comment]
Thanks for the report!

It seems to be duplicate of https://github.com/rust-lang/rust-clippy/issues/8254.
