### ISSUE TITLE
ICE for compiler/rustc_metadata/src/rmeta/decoder/cstore_impl.rs:123:1

### ISSUE THREAD

**Issue by cmichi** [rust-lang/rust-clippy#8821]
### Summary

I'm getting the below ICE for the last clippy nightlies. I haven't bisected it in more detail, but it started some time after `nightly-2022-05-05` (that one doesn't have the ICE).

### Reproducer

I tried this code:

`Cargo.toml`:
```toml
[package]
name = "foo"
version = "0.1.0"
authors = ["[your_name] <[your_email]>"]
edition = "2021"

[dependencies]
ink_primitives = { version = "3.0", default-features = false }
ink_metadata = { version = "3.0", default-features = false, features = ["derive"], optional = true }
ink_env = { version = "3.0", default-features = false }
ink_storage = { version = "3.0", default-features = false }
ink_lang = { version = "3.0", default-features = false }

scale = { package = "parity-scale-codec", version = "3", default-features = false, features = ["derive"] }
scale-info = { version = "2", default-features = false, features = ["derive"], optional = true }

[lib]
name = "foo"
path = "lib.rs"
crate-type = [
	# Used for normal contract Wasm blobs.
	"cdylib",
]

[features]
default = ["std"]
std = [
    "ink_metadata/std",
    "ink_env/std",
    "ink_storage/std",
    "ink_primitives/std",
    "scale/std",
    "scale-info/std",
]
ink-as-dependency = []
```

`lib.rs`:
```rust
#![cfg_attr(not(feature = "std"), no_std)]

use ink_lang as ink;

#[ink::contract]
mod my_contract {
    #[ink(storage)]
    pub struct MyContract {}

    /// Exemplary event
    #[ink(event)]
    pub struct MyEvent {
        v0: bool,
    }

    impl MyContract {
        /// Creates a new `MyContract` instance.
        #[ink(constructor)]
        pub fn new() -> Self {
            MyContract {}
        }

        /// Emits a `MyEvent`.
        #[ink(message)]
        pub fn emit_my_event(&self) {}
    }
}
```

Then I executed `cargo clippy`.

I expected to see this happen: The clippy run should not panic.

Instead, this happened:

```
thread 'rustc' panicked at 'DefId(20:412 ~ ink_lang[dcb0]::reflect::dispatch::DispatchableMessageInfo::CALLABLE) does not have a "fn_sig"', compiler/rustc_metadata/src/rmeta/decoder/cstore_impl.rs:123:1
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust-clippy/issues/new

note: Clippy version: clippy 0.1.62 (6dd6840 2022-05-11)

query stack during panic:
#0 [fn_sig] computing function signature of `ink_lang::reflect::dispatch::DispatchableMessageInfo::CALLABLE`
#1 [analysis] running analysis passes on this crate
end of query stack
```

### Version

```text
rustc 1.62.0-nightly (6dd68402c 2022-05-11)
binary: rustc
commit-hash: 6dd68402c5d7da168f87d8551dd9aed1d8a21893
commit-date: 2022-05-11
host: x86_64-unknown-linux-gnu
release: 1.62.0-nightly
LLVM version: 14.0.1
```

**Comment by giraffate** [comment]
Thanks for the report!

Could you provide a backtrace?

**Comment by cmichi** [comment]
Ah yeah, ofc!

```
    Checking foo v0.1.0 (/tmp/foo)
warning: this lifetime isn't used in the impl
 --> lib.rs:5:1
  |
5 | #[ink::contract]
  | ^^^^^^^^^^^^^^^^
  |
  = note: `#[warn(clippy::extra_unused_lifetimes)]` on by default
  = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#extra_unused_lifetimes
  = note: this warning originates in the attribute macro `ink::contract` (in Nightly builds, run with -Z macro-backtrace for more info)

thread 'rustc' panicked at 'DefId(20:412 ~ ink_lang[58c0]::reflect::dispatch::DispatchableMessageInfo::CALLABLE) does not have a "fn_sig"', compiler/rustc_metadata/src/rmeta/decoder/cstore_impl.rs:123:1
stack backtrace:
   0: rust_begin_unwind
             at /rustc/a5ad0d29a401007b51715852cc702e441ac2248c/library/std/src/panicking.rs:584:5
   1: core::panicking::panic_fmt
             at /rustc/a5ad0d29a401007b51715852cc702e441ac2248c/library/core/src/panicking.rs:142:14
   2: rustc_metadata::rmeta::decoder::cstore_impl::provide_extern::fn_sig::{closure#0}
   3: rustc_metadata::rmeta::decoder::cstore_impl::provide_extern::fn_sig
   4: <rustc_query_system::dep_graph::graph::DepGraph<rustc_middle::dep_graph::dep_node::DepKind>>::with_task::<rustc_middle::ty::context::TyCtxt, rustc_span::def_id::DefId, rustc_middle::ty::sty::Binder<rustc_middle::ty::sty::FnSig>>
   5: rustc_query_system::query::plumbing::try_execute_query::<rustc_query_impl::plumbing::QueryCtxt, rustc_query_system::query::caches::DefaultCache<rustc_span::def_id::DefId, rustc_middle::ty::sty::Binder<rustc_middle::ty::sty::FnSig>>>
   6: <rustc_query_impl::Queries as rustc_middle::ty::query::QueryEngine>::fn_sig
   7: clippy_lints::unit_types::let_unit_value::needs_inferred_result_ty
   8: clippy_utils::visitors::for_each_value_source::<(), clippy_lints::unit_types::let_unit_value::check::{closure#0}>
   9: clippy_lints::unit_types::let_unit_value::check
  10: <rustc_lint::late::LateLintPassObjects as rustc_lint::passes::LateLintPass>::check_stmt
  11: <rustc_lint::late::LateContextAndPass<rustc_lint::late::LateLintPassObjects> as rustc_hir::intravisit::Visitor>::visit_stmt
  12: rustc_hir::intravisit::walk_block::<rustc_lint::late::LateContextAndPass<rustc_lint::late::LateLintPassObjects>>
  13: <rustc_lint::late::LateContextAndPass<rustc_lint::late::LateLintPassObjects> as rustc_hir::intravisit::Visitor>::visit_block
  14: <rustc_lint::late::LateContextAndPass<rustc_lint::late::LateLintPassObjects> as rustc_hir::intravisit::Visitor>::visit_expr
  15: rustc_hir::intravisit::walk_expr::<rustc_lint::late::LateContextAndPass<rustc_lint::late::LateLintPassObjects>>
  16: <rustc_lint::late::LateContextAndPass<rustc_lint::late::LateLintPassObjects> as rustc_hir::intravisit::Visitor>::visit_expr
  17: rustc_hir::intravisit::walk_block::<rustc_lint::late::LateContextAndPass<rustc_lint::late::LateLintPassObjects>>
  18: <rustc_lint::late::LateContextAndPass<rustc_lint::late::LateLintPassObjects> as rustc_hir::intravisit::Visitor>::visit_block
  19: <rustc_lint::late::LateContextAndPass<rustc_lint::late::LateLintPassObjects> as rustc_hir::intravisit::Visitor>::visit_expr
  20: <rustc_lint::late::LateContextAndPass<rustc_lint::late::LateLintPassObjects> as rustc_hir::intravisit::Visitor>::visit_nested_body
  21: <rustc_lint::late::LateContextAndPass<rustc_lint::late::LateLintPassObjects> as rustc_hir::intravisit::Visitor>::visit_fn
  22: rustc_hir::intravisit::walk_impl_item::<rustc_lint::late::LateContextAndPass<rustc_lint::late::LateLintPassObjects>>
  23: <rustc_lint::late::LateContextAndPass<rustc_lint::late::LateLintPassObjects> as rustc_hir::intravisit::Visitor>::visit_nested_impl_item
  24: rustc_hir::intravisit::walk_impl_item_ref::<rustc_lint::late::LateContextAndPass<rustc_lint::late::LateLintPassObjects>>
  25: rustc_hir::intravisit::walk_item::<rustc_lint::late::LateContextAndPass<rustc_lint::late::LateLintPassObjects>>
  26: <rustc_lint::late::LateContextAndPass<rustc_lint::late::LateLintPassObjects> as rustc_hir::intravisit::Visitor>::visit_nested_item
  27: rustc_hir::intravisit::walk_block::<rustc_lint::late::LateContextAndPass<rustc_lint::late::LateLintPassObjects>>
  28: <rustc_lint::late::LateContextAndPass<rustc_lint::late::LateLintPassObjects> as rustc_hir::intravisit::Visitor>::visit_block
  29: <rustc_lint::late::LateContextAndPass<rustc_lint::late::LateLintPassObjects> as rustc_hir::intravisit::Visitor>::visit_expr
  30: <rustc_lint::late::LateContextAndPass<rustc_lint::late::LateLintPassObjects> as rustc_hir::intravisit::Visitor>::visit_nested_body
  31: <rustc_lint::late::LateContextAndPass<rustc_lint::late::LateLintPassObjects> as rustc_hir::intravisit::Visitor>::visit_nested_item
  32: rustc_hir::intravisit::walk_mod::<rustc_lint::late::LateContextAndPass<rustc_lint::late::LateLintPassObjects>>
  33: <rustc_lint::late::LateContextAndPass<rustc_lint::late::LateLintPassObjects> as rustc_hir::intravisit::Visitor>::visit_mod
  34: <rustc_lint::late::LateContextAndPass<rustc_lint::late::LateLintPassObjects> as rustc_hir::intravisit::Visitor>::visit_nested_item
  35: rustc_hir::intravisit::walk_mod::<rustc_lint::late::LateContextAndPass<rustc_lint::late::LateLintPassObjects>>
  36: <rustc_lint::late::LateContextAndPass<rustc_lint::late::LateLintPassObjects> as rustc_hir::intravisit::Visitor>::visit_mod
  37: rustc_lint::late::late_lint_pass_crate::<rustc_lint::late::LateLintPassObjects>
  38: rustc_lint::late::late_lint_crate::<rustc_lint::BuiltinCombinedLateLintPass>
  39: <rustc_session::session::Session>::time::<(), rustc_lint::late::check_crate<rustc_lint::BuiltinCombinedLateLintPass, rustc_interface::passes::analysis::{closure#5}::{closure#1}::{closure#2}::{closure#0}::{closure#0}>::{closure#0}::{closure#0}>
  40: <rustc_session::session::Session>::time::<(), rustc_interface::passes::analysis::{closure#5}::{closure#1}::{closure#2}::{closure#0}>
  41: <core::panic::unwind_safe::AssertUnwindSafe<rustc_interface::passes::analysis::{closure#5}::{closure#1}> as core::ops::function::FnOnce<()>>::call_once
  42: <rustc_session::session::Session>::time::<(), rustc_interface::passes::analysis::{closure#5}>
  43: rustc_interface::passes::analysis
  44: <rustc_query_system::dep_graph::graph::DepGraph<rustc_middle::dep_graph::dep_node::DepKind>>::with_task::<rustc_middle::ty::context::TyCtxt, (), core::result::Result<(), rustc_errors::ErrorGuaranteed>>
  45: rustc_query_system::query::plumbing::try_execute_query::<rustc_query_impl::plumbing::QueryCtxt, rustc_query_system::query::caches::DefaultCache<(), core::result::Result<(), rustc_errors::ErrorGuaranteed>>>
  46: rustc_query_system::query::plumbing::get_query::<rustc_query_impl::queries::analysis, rustc_query_impl::plumbing::QueryCtxt>
  47: <rustc_interface::passes::QueryContext>::enter::<rustc_driver::run_compiler::{closure#1}::{closure#2}::{closure#3}, core::result::Result<(), rustc_errors::ErrorGuaranteed>>
  48: <rustc_interface::interface::Compiler>::enter::<rustc_driver::run_compiler::{closure#1}::{closure#2}, core::result::Result<core::option::Option<rustc_interface::queries::Linker>, rustc_errors::ErrorGuaranteed>>
  49: rustc_span::with_source_map::<core::result::Result<(), rustc_errors::ErrorGuaranteed>, rustc_interface::interface::create_compiler_and_run<core::result::Result<(), rustc_errors::ErrorGuaranteed>, rustc_driver::run_compiler::{closure#1}>::{closure#1}>
  50: rustc_interface::interface::create_compiler_and_run::<core::result::Result<(), rustc_errors::ErrorGuaranteed>, rustc_driver::run_compiler::{closure#1}>
  51: <scoped_tls::ScopedKey<rustc_span::SessionGlobals>>::set::<rustc_interface::interface::run_compiler<core::result::Result<(), rustc_errors::ErrorGuaranteed>, rustc_driver::run_compiler::{closure#1}>::{closure#0}, core::result::Result<(), rustc_errors::ErrorGuaranteed>>
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust-clippy/issues/new

note: Clippy version: clippy 0.1.62 (a5ad0d2 2022-05-12)

query stack during panic:
#0 [fn_sig] computing function signature of `ink_lang::reflect::dispatch::DispatchableMessageInfo::CALLABLE`
#1 [analysis] running analysis passes on this crate
end of query stack
warning: `foo` (lib) generated 1 warning
error: could not compile `foo`; 1 warning emitted
```
