### ISSUE TITLE
ICE: compiler/rustc_typeck/src/collect.rs:1896:13: to get the signature of a closure, use `substs.as_closure().sig()` not `fn_sig()`

### ISSUE THREAD

**Issue by matthiaskrgr** [rust-lang/rust-clippy#9089]
### Summary

This happens when running clippy on the rustc_errors crate

### Version

```text
clippy 0.1.64 (ca1e68b 2022-07-01)
```

### Error output

<details><summary>Backtrace</summary>
  <p>

  ```
  error: internal compiler error: compiler/rustc_typeck/src/collect.rs:1896:13: to get the signature of a closure, use `substs.as_closure().sig()` not `fn_sig()`

thread 'rustc' panicked at 'Box<dyn Any>', /rustc/ddcbba036aee08f0709f98a92a342a278eae5c05/compiler/rustc_errors/src/lib.rs:1391:9
stack backtrace:
   0:     0x7f804d0a15cd - std::backtrace_rs::backtrace::libunwind::trace::h79327ccd22e2164a
                               at /rustc/ddcbba036aee08f0709f98a92a342a278eae5c05/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
   1:     0x7f804d0a15cd - std::backtrace_rs::backtrace::trace_unsynchronized::h7474da7e45f82fef
                               at /rustc/ddcbba036aee08f0709f98a92a342a278eae5c05/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x7f804d0a15cd - std::sys_common::backtrace::_print_fmt::h6c7edbb20ad2f451
                               at /rustc/ddcbba036aee08f0709f98a92a342a278eae5c05/library/std/src/sys_common/backtrace.rs:66:5
   3:     0x7f804d0a15cd - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::hed6df72de1722661
                               at /rustc/ddcbba036aee08f0709f98a92a342a278eae5c05/library/std/src/sys_common/backtrace.rs:45:22
   4:     0x7f804d0fa90c - core::fmt::write::h11f5d0f6418e15ab
                               at /rustc/ddcbba036aee08f0709f98a92a342a278eae5c05/library/core/src/fmt/mod.rs:1198:17
   5:     0x7f804d092c41 - std::io::Write::write_fmt::h2287344a97990f36
                               at /rustc/ddcbba036aee08f0709f98a92a342a278eae5c05/library/std/src/io/mod.rs:1672:15
   6:     0x7f804d0a4295 - std::sys_common::backtrace::_print::h5503bb3e2c3786ac
                               at /rustc/ddcbba036aee08f0709f98a92a342a278eae5c05/library/std/src/sys_common/backtrace.rs:48:5
   7:     0x7f804d0a4295 - std::sys_common::backtrace::print::hd93eff6347adc6af
                               at /rustc/ddcbba036aee08f0709f98a92a342a278eae5c05/library/std/src/sys_common/backtrace.rs:35:9
   8:     0x7f804d0a4295 - std::panicking::default_hook::{{closure}}::h77c8a625f7da619f
                               at /rustc/ddcbba036aee08f0709f98a92a342a278eae5c05/library/std/src/panicking.rs:295:22
   9:     0x7f804d0a3fb6 - std::panicking::default_hook::h975ef4f484179dc7
                               at /rustc/ddcbba036aee08f0709f98a92a342a278eae5c05/library/std/src/panicking.rs:314:9
  10:     0x56412db95763 - <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call::h55b0933e6d483624
                               at /rustc/ddcbba036aee08f0709f98a92a342a278eae5c05/library/alloc/src/boxed.rs:1965:9
  11:     0x56412db967d0 - clippy_driver::report_clippy_ice::h958742afd16a5289
                               at /home/matthias/vcs/github/rust-clippy/src/driver.rs:165:5
  12:     0x56412db9135a - clippy_driver::ICE_HOOK::{{closure}}::{{closure}}::hacfb41f5441c9e3a
                               at /home/matthias/vcs/github/rust-clippy/src/driver.rs:159:37
  13:     0x7f804d0a496a - std::panicking::rust_panic_with_hook::h4c5237b27a09590d
                               at /rustc/ddcbba036aee08f0709f98a92a342a278eae5c05/library/std/src/panicking.rs:702:17
  14:     0x7f804e9ff8b1 - std[da9e0d8df6b8e369]::panicking::begin_panic::<rustc_errors[ace5696c6a45b28d]::ExplicitBug>::{closure#0}
  15:     0x7f804e9fdcd6 - std[da9e0d8df6b8e369]::sys_common::backtrace::__rust_end_short_backtrace::<std[da9e0d8df6b8e369]::panicking::begin_panic<rustc_errors[ace5696c6a45b28d]::ExplicitBug>::{closure#0}, !>
  16:     0x7f804e9764f6 - std[da9e0d8df6b8e369]::panicking::begin_panic::<rustc_errors[ace5696c6a45b28d]::ExplicitBug>
  17:     0x7f804e996cc6 - std[da9e0d8df6b8e369]::panic::panic_any::<rustc_errors[ace5696c6a45b28d]::ExplicitBug>
  18:     0x7f804e990a15 - <rustc_errors[ace5696c6a45b28d]::HandlerInner>::bug::<&alloc[cd27a1bb7ed2ecb3]::string::String>
  19:     0x7f804e990770 - <rustc_errors[ace5696c6a45b28d]::Handler>::bug::<&alloc[cd27a1bb7ed2ecb3]::string::String>
  20:     0x7f804ea078ed - rustc_middle[c60e04a357c374ab]::ty::context::tls::with_opt::<rustc_middle[c60e04a357c374ab]::util::bug::opt_span_bug_fmt<rustc_span[25b14a9e1900d955]::span_encoding::Span>::{closure#0}, ()>
  21:     0x7f804ea08196 - rustc_middle[c60e04a357c374ab]::util::bug::opt_span_bug_fmt::<rustc_span[25b14a9e1900d955]::span_encoding::Span>
  22:     0x7f804ea08113 - rustc_middle[c60e04a357c374ab]::util::bug::bug_fmt
  23:     0x7f804ef7bdd7 - rustc_typeck[4ddd1cd5073c5620]::collect::fn_sig
  24:     0x7f804ff9d4f6 - <rustc_query_system[f0362db6bb700839]::dep_graph::graph::DepGraph<rustc_middle[c60e04a357c374ab]::dep_graph::dep_node::DepKind>>::with_task::<rustc_middle[c60e04a357c374ab]::ty::context::TyCtxt, rustc_span[25b14a9e1900d955]::def_id::DefId, rustc_middle[c60e04a357c374ab]::ty::sty::Binder<rustc_middle[c60e04a357c374ab]::ty::sty::FnSig>>
  25:     0x7f804f4e94b9 - rustc_query_system[f0362db6bb700839]::query::plumbing::try_execute_query::<rustc_query_impl[665c4da890f8de3f]::plumbing::QueryCtxt, rustc_query_system[f0362db6bb700839]::query::caches::DefaultCache<rustc_span[25b14a9e1900d955]::def_id::DefId, rustc_middle[c60e04a357c374ab]::ty::sty::Binder<rustc_middle[c60e04a357c374ab]::ty::sty::FnSig>>>
  26:     0x7f804f4b5813 - <rustc_query_impl[665c4da890f8de3f]::Queries as rustc_middle[c60e04a357c374ab]::ty::query::QueryEngine>::fn_sig
  27:     0x56412e17fe1f - rustc_middle::ty::query::TyCtxtAt::fn_sig::h2d2f11c8cabff6a7
                               at /rustc/ddcbba036aee08f0709f98a92a342a278eae5c05/compiler/rustc_middle/src/ty/query.rs:258:17
  28:     0x56412e17fe1f - rustc_middle::ty::query::<impl rustc_middle::ty::context::TyCtxt>::fn_sig::h51c6071254c6db92
                               at /rustc/ddcbba036aee08f0709f98a92a342a278eae5c05/compiler/rustc_middle/src/ty/query.rs:239:17
  29:     0x56412e17fe1f - clippy_lints::dereference::walk_parents::{{closure}}::h38738973f4736ff5
                               at /home/matthias/vcs/github/rust-clippy/clippy_lints/src/dereference.rs:720:34
  30:     0x56412e17e973 - core::ops::function::impls::<impl core::ops::function::FnMut<A> for &mut F>::call_mut::hc0bf156c568bf0ea
                               at /rustc/ddcbba036aee08f0709f98a92a342a278eae5c05/library/core/src/ops/function.rs:290:13
  31:     0x56412de75f9e - clippy_utils::walk_to_expr_usage::hf360934ec3f33617
                               at /home/matthias/vcs/github/rust-clippy/clippy_utils/src/lib.rs:2206:26
  32:     0x56412de248e0 - clippy_lints::dereference::walk_parents::h2732a5772b7d8615
                               at /home/matthias/vcs/github/rust-clippy/clippy_lints/src/dereference.rs:655:20
  33:     0x56412de226b6 - <clippy_lints::dereference::Dereferencing as rustc_lint::passes::LateLintPass>::check_expr::h8a1011d07631d5f0
                               at /home/matthias/vcs/github/rust-clippy/clippy_lints/src/dereference.rs:253:47
  34:     0x7f804e794954 - <rustc_lint[5ef7e7f23e41ca0f]::late::LateLintPassObjects as rustc_lint[5ef7e7f23e41ca0f]::passes::LateLintPass>::check_expr
  35:     0x7f804d9bbad0 - <rustc_lint[5ef7e7f23e41ca0f]::late::LateContextAndPass<rustc_lint[5ef7e7f23e41ca0f]::late::LateLintPassObjects> as rustc_hir[67106ace806a6a70]::intravisit::Visitor>::visit_expr
  36:     0x7f804d9bbadb - <rustc_lint[5ef7e7f23e41ca0f]::late::LateContextAndPass<rustc_lint[5ef7e7f23e41ca0f]::late::LateLintPassObjects> as rustc_hir[67106ace806a6a70]::intravisit::Visitor>::visit_expr
  37:     0x7f804d9c52b7 - rustc_hir[67106ace806a6a70]::intravisit::walk_block::<rustc_lint[5ef7e7f23e41ca0f]::late::LateContextAndPass<rustc_lint[5ef7e7f23e41ca0f]::late::LateLintPassObjects>>
  38:     0x7f804d9bbc49 - <rustc_lint[5ef7e7f23e41ca0f]::late::LateContextAndPass<rustc_lint[5ef7e7f23e41ca0f]::late::LateLintPassObjects> as rustc_hir[67106ace806a6a70]::intravisit::Visitor>::visit_block
  39:     0x7f804d9bbadb - <rustc_lint[5ef7e7f23e41ca0f]::late::LateContextAndPass<rustc_lint[5ef7e7f23e41ca0f]::late::LateLintPassObjects> as rustc_hir[67106ace806a6a70]::intravisit::Visitor>::visit_expr
  40:     0x7f804d9c6c56 - rustc_hir[67106ace806a6a70]::intravisit::walk_expr::<rustc_lint[5ef7e7f23e41ca0f]::late::LateContextAndPass<rustc_lint[5ef7e7f23e41ca0f]::late::LateLintPassObjects>>
  41:     0x7f804d9bbadb - <rustc_lint[5ef7e7f23e41ca0f]::late::LateContextAndPass<rustc_lint[5ef7e7f23e41ca0f]::late::LateLintPassObjects> as rustc_hir[67106ace806a6a70]::intravisit::Visitor>::visit_expr
  42:     0x7f804d9c52b7 - rustc_hir[67106ace806a6a70]::intravisit::walk_block::<rustc_lint[5ef7e7f23e41ca0f]::late::LateContextAndPass<rustc_lint[5ef7e7f23e41ca0f]::late::LateLintPassObjects>>
  43:     0x7f804d9bbc49 - <rustc_lint[5ef7e7f23e41ca0f]::late::LateContextAndPass<rustc_lint[5ef7e7f23e41ca0f]::late::LateLintPassObjects> as rustc_hir[67106ace806a6a70]::intravisit::Visitor>::visit_block
  44:     0x7f804d9bbadb - <rustc_lint[5ef7e7f23e41ca0f]::late::LateContextAndPass<rustc_lint[5ef7e7f23e41ca0f]::late::LateLintPassObjects> as rustc_hir[67106ace806a6a70]::intravisit::Visitor>::visit_expr
  45:     0x7f804d9bc004 - <rustc_lint[5ef7e7f23e41ca0f]::late::LateContextAndPass<rustc_lint[5ef7e7f23e41ca0f]::late::LateLintPassObjects> as rustc_hir[67106ace806a6a70]::intravisit::Visitor>::visit_nested_body
  46:     0x7f804d9bc255 - <rustc_lint[5ef7e7f23e41ca0f]::late::LateContextAndPass<rustc_lint[5ef7e7f23e41ca0f]::late::LateLintPassObjects> as rustc_hir[67106ace806a6a70]::intravisit::Visitor>::visit_fn
  47:     0x7f804d9c6cfb - rustc_hir[67106ace806a6a70]::intravisit::walk_expr::<rustc_lint[5ef7e7f23e41ca0f]::late::LateContextAndPass<rustc_lint[5ef7e7f23e41ca0f]::late::LateLintPassObjects>>
  48:     0x7f804d9bbadb - <rustc_lint[5ef7e7f23e41ca0f]::late::LateContextAndPass<rustc_lint[5ef7e7f23e41ca0f]::late::LateLintPassObjects> as rustc_hir[67106ace806a6a70]::intravisit::Visitor>::visit_expr
  49:     0x7f804d9c6bef - rustc_hir[67106ace806a6a70]::intravisit::walk_expr::<rustc_lint[5ef7e7f23e41ca0f]::late::LateContextAndPass<rustc_lint[5ef7e7f23e41ca0f]::late::LateLintPassObjects>>
  50:     0x7f804d9bbadb - <rustc_lint[5ef7e7f23e41ca0f]::late::LateContextAndPass<rustc_lint[5ef7e7f23e41ca0f]::late::LateLintPassObjects> as rustc_hir[67106ace806a6a70]::intravisit::Visitor>::visit_expr
  51:     0x7f804d9bbc49 - <rustc_lint[5ef7e7f23e41ca0f]::late::LateContextAndPass<rustc_lint[5ef7e7f23e41ca0f]::late::LateLintPassObjects> as rustc_hir[67106ace806a6a70]::intravisit::Visitor>::visit_block
  52:     0x7f804d9bbadb - <rustc_lint[5ef7e7f23e41ca0f]::late::LateContextAndPass<rustc_lint[5ef7e7f23e41ca0f]::late::LateLintPassObjects> as rustc_hir[67106ace806a6a70]::intravisit::Visitor>::visit_expr
  53:     0x7f804d9c6c93 - rustc_hir[67106ace806a6a70]::intravisit::walk_expr::<rustc_lint[5ef7e7f23e41ca0f]::late::LateContextAndPass<rustc_lint[5ef7e7f23e41ca0f]::late::LateLintPassObjects>>
  54:     0x7f804d9bbadb - <rustc_lint[5ef7e7f23e41ca0f]::late::LateContextAndPass<rustc_lint[5ef7e7f23e41ca0f]::late::LateLintPassObjects> as rustc_hir[67106ace806a6a70]::intravisit::Visitor>::visit_expr
  55:     0x7f804d9bbc49 - <rustc_lint[5ef7e7f23e41ca0f]::late::LateContextAndPass<rustc_lint[5ef7e7f23e41ca0f]::late::LateLintPassObjects> as rustc_hir[67106ace806a6a70]::intravisit::Visitor>::visit_block
  56:     0x7f804d9bbadb - <rustc_lint[5ef7e7f23e41ca0f]::late::LateContextAndPass<rustc_lint[5ef7e7f23e41ca0f]::late::LateLintPassObjects> as rustc_hir[67106ace806a6a70]::intravisit::Visitor>::visit_expr
  57:     0x7f804d9bc004 - <rustc_lint[5ef7e7f23e41ca0f]::late::LateContextAndPass<rustc_lint[5ef7e7f23e41ca0f]::late::LateLintPassObjects> as rustc_hir[67106ace806a6a70]::intravisit::Visitor>::visit_nested_body
  58:     0x7f804d9bc255 - <rustc_lint[5ef7e7f23e41ca0f]::late::LateContextAndPass<rustc_lint[5ef7e7f23e41ca0f]::late::LateLintPassObjects> as rustc_hir[67106ace806a6a70]::intravisit::Visitor>::visit_fn
  59:     0x7f804d9c5a13 - rustc_hir[67106ace806a6a70]::intravisit::walk_impl_item::<rustc_lint[5ef7e7f23e41ca0f]::late::LateContextAndPass<rustc_lint[5ef7e7f23e41ca0f]::late::LateLintPassObjects>>
  60:     0x7f804d9bd09f - <rustc_lint[5ef7e7f23e41ca0f]::late::LateContextAndPass<rustc_lint[5ef7e7f23e41ca0f]::late::LateLintPassObjects> as rustc_hir[67106ace806a6a70]::intravisit::Visitor>::visit_nested_impl_item
  61:     0x7f804d9c61a8 - rustc_hir[67106ace806a6a70]::intravisit::walk_impl_item_ref::<rustc_lint[5ef7e7f23e41ca0f]::late::LateContextAndPass<rustc_lint[5ef7e7f23e41ca0f]::late::LateLintPassObjects>>
  62:     0x7f804d9c7210 - rustc_hir[67106ace806a6a70]::intravisit::walk_item::<rustc_lint[5ef7e7f23e41ca0f]::late::LateContextAndPass<rustc_lint[5ef7e7f23e41ca0f]::late::LateLintPassObjects>>
  63:     0x7f804d9bcdae - <rustc_lint[5ef7e7f23e41ca0f]::late::LateContextAndPass<rustc_lint[5ef7e7f23e41ca0f]::late::LateLintPassObjects> as rustc_hir[67106ace806a6a70]::intravisit::Visitor>::visit_nested_item
  64:     0x7f804d9c6837 - rustc_hir[67106ace806a6a70]::intravisit::walk_mod::<rustc_lint[5ef7e7f23e41ca0f]::late::LateContextAndPass<rustc_lint[5ef7e7f23e41ca0f]::late::LateLintPassObjects>>
  65:     0x7f804d9bc37c - <rustc_lint[5ef7e7f23e41ca0f]::late::LateContextAndPass<rustc_lint[5ef7e7f23e41ca0f]::late::LateLintPassObjects> as rustc_hir[67106ace806a6a70]::intravisit::Visitor>::visit_mod
  66:     0x7f804d9bb9f3 - rustc_lint[5ef7e7f23e41ca0f]::late::late_lint_pass_crate::<rustc_lint[5ef7e7f23e41ca0f]::late::LateLintPassObjects>
  67:     0x7f804ec6eba8 - rustc_lint[5ef7e7f23e41ca0f]::late::late_lint_crate::<rustc_lint[5ef7e7f23e41ca0f]::BuiltinCombinedLateLintPass>
  68:     0x7f804fb10928 - rustc_data_structures[ceb9da85d74dec0b]::sync::join::<rustc_lint[5ef7e7f23e41ca0f]::late::check_crate<rustc_lint[5ef7e7f23e41ca0f]::BuiltinCombinedLateLintPass, rustc_interface[8131206a6d8b1989]::passes::analysis::{closure#5}::{closure#1}::{closure#2}::{closure#0}::{closure#0}>::{closure#0}, rustc_lint[5ef7e7f23e41ca0f]::late::check_crate<rustc_lint[5ef7e7f23e41ca0f]::BuiltinCombinedLateLintPass, rustc_interface[8131206a6d8b1989]::passes::analysis::{closure#5}::{closure#1}::{closure#2}::{closure#0}::{closure#0}>::{closure#1}, (), ()>
  69:     0x7f804fb0dae0 - <rustc_session[242e584213b6d55f]::session::Session>::time::<(), rustc_interface[8131206a6d8b1989]::passes::analysis::{closure#5}::{closure#1}::{closure#2}::{closure#0}>
  70:     0x7f804fb29b71 - <core[50a63c015f38975a]::panic::unwind_safe::AssertUnwindSafe<rustc_interface[8131206a6d8b1989]::passes::analysis::{closure#5}::{closure#1}> as core[50a63c015f38975a]::ops::function::FnOnce<()>>::call_once
  71:     0x7f804fb0f48a - <rustc_session[242e584213b6d55f]::session::Session>::time::<(), rustc_interface[8131206a6d8b1989]::passes::analysis::{closure#5}>
  72:     0x7f804fb0928c - rustc_interface[8131206a6d8b1989]::passes::analysis
  73:     0x7f804ffb6475 - <rustc_query_system[f0362db6bb700839]::dep_graph::graph::DepGraph<rustc_middle[c60e04a357c374ab]::dep_graph::dep_node::DepKind>>::with_task::<rustc_middle[c60e04a357c374ab]::ty::context::TyCtxt, (), core[50a63c015f38975a]::result::Result<(), rustc_errors[ace5696c6a45b28d]::ErrorGuaranteed>>
  74:     0x7f8050061b5c - rustc_query_system[f0362db6bb700839]::query::plumbing::try_execute_query::<rustc_query_impl[665c4da890f8de3f]::plumbing::QueryCtxt, rustc_query_system[f0362db6bb700839]::query::caches::DefaultCache<(), core[50a63c015f38975a]::result::Result<(), rustc_errors[ace5696c6a45b28d]::ErrorGuaranteed>>>
  75:     0x7f80500ab02e - rustc_query_system[f0362db6bb700839]::query::plumbing::get_query::<rustc_query_impl[665c4da890f8de3f]::queries::analysis, rustc_query_impl[665c4da890f8de3f]::plumbing::QueryCtxt>
  76:     0x7f804faebb47 - <rustc_interface[8131206a6d8b1989]::passes::QueryContext>::enter::<rustc_driver[bb5018aaf4248976]::run_compiler::{closure#1}::{closure#2}::{closure#3}, core[50a63c015f38975a]::result::Result<(), rustc_errors[ace5696c6a45b28d]::ErrorGuaranteed>>
  77:     0x7f804fad644f - <rustc_interface[8131206a6d8b1989]::interface::Compiler>::enter::<rustc_driver[bb5018aaf4248976]::run_compiler::{closure#1}::{closure#2}, core[50a63c015f38975a]::result::Result<core[50a63c015f38975a]::option::Option<rustc_interface[8131206a6d8b1989]::queries::Linker>, rustc_errors[ace5696c6a45b28d]::ErrorGuaranteed>>
  78:     0x7f804fafa83f - rustc_span[25b14a9e1900d955]::with_source_map::<core[50a63c015f38975a]::result::Result<(), rustc_errors[ace5696c6a45b28d]::ErrorGuaranteed>, rustc_interface[8131206a6d8b1989]::interface::create_compiler_and_run<core[50a63c015f38975a]::result::Result<(), rustc_errors[ace5696c6a45b28d]::ErrorGuaranteed>, rustc_driver[bb5018aaf4248976]::run_compiler::{closure#1}>::{closure#1}>
  79:     0x7f804fad72e2 - <scoped_tls[8c665c213b0e261f]::ScopedKey<rustc_span[25b14a9e1900d955]::SessionGlobals>>::set::<rustc_interface[8131206a6d8b1989]::interface::run_compiler<core[50a63c015f38975a]::result::Result<(), rustc_errors[ace5696c6a45b28d]::ErrorGuaranteed>, rustc_driver[bb5018aaf4248976]::run_compiler::{closure#1}>::{closure#0}, core[50a63c015f38975a]::result::Result<(), rustc_errors[ace5696c6a45b28d]::ErrorGuaranteed>>
  80:     0x7f804faec1df - std[da9e0d8df6b8e369]::sys_common::backtrace::__rust_begin_short_backtrace::<rustc_interface[8131206a6d8b1989]::util::run_in_thread_pool_with_globals<rustc_interface[8131206a6d8b1989]::interface::run_compiler<core[50a63c015f38975a]::result::Result<(), rustc_errors[ace5696c6a45b28d]::ErrorGuaranteed>, rustc_driver[bb5018aaf4248976]::run_compiler::{closure#1}>::{closure#0}, core[50a63c015f38975a]::result::Result<(), rustc_errors[ace5696c6a45b28d]::ErrorGuaranteed>>::{closure#0}, core[50a63c015f38975a]::result::Result<(), rustc_errors[ace5696c6a45b28d]::ErrorGuaranteed>>
  81:     0x7f804faec319 - <<std[da9e0d8df6b8e369]::thread::Builder>::spawn_unchecked_<rustc_interface[8131206a6d8b1989]::util::run_in_thread_pool_with_globals<rustc_interface[8131206a6d8b1989]::interface::run_compiler<core[50a63c015f38975a]::result::Result<(), rustc_errors[ace5696c6a45b28d]::ErrorGuaranteed>, rustc_driver[bb5018aaf4248976]::run_compiler::{closure#1}>::{closure#0}, core[50a63c015f38975a]::result::Result<(), rustc_errors[ace5696c6a45b28d]::ErrorGuaranteed>>::{closure#0}, core[50a63c015f38975a]::result::Result<(), rustc_errors[ace5696c6a45b28d]::ErrorGuaranteed>>::{closure#1} as core[50a63c015f38975a]::ops::function::FnOnce<()>>::call_once::{shim:vtable#0}
  82:     0x7f804d0ae4e3 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h22d0ff7b39ccc53a
                               at /rustc/ddcbba036aee08f0709f98a92a342a278eae5c05/library/alloc/src/boxed.rs:1951:9
  83:     0x7f804d0ae4e3 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::hef50bc84dfaa11d1
                               at /rustc/ddcbba036aee08f0709f98a92a342a278eae5c05/library/alloc/src/boxed.rs:1951:9
  84:     0x7f804d0ae4e3 - std::sys::unix::thread::Thread::new::thread_start::h07be67d12c7b8c55
                               at /rustc/ddcbba036aee08f0709f98a92a342a278eae5c05/library/std/src/sys/unix/thread.rs:108:17
  85:     0x7f804cd9954d - <unknown>
  86:     0x7f804ce1e874 - clone
  87:                0x0 - <unknown>

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust-clippy/issues/new

note: Clippy version: clippy 0.1.64 (d7e5dab6c 2022-06-30)

query stack during panic:
#0 [fn_sig] computing function signature of `<impl at compiler/rustc_arena/src/lib.rs:371:1: 534:2>::alloc_from_iter::{closure#0}`
#1 [analysis] running analysis passes on this crate
end of query stack
error: could not compile `rustc_arena` due to 6 previous errors
warning: build failed, waiting for other jobs to finish...
  ```

  </p>
</details>

**Comment by matthiaskrgr** [comment]
The problem might be
````rust
                    let output = cx
                        .tcx
                        .fn_sig(cx.tcx.hir().body_owner_def_id(cx.enclosing_body.unwrap())) // this
                        .skip_binder()
                        .output();
````
in clippy_lints/src/dereference.rs

**Comment by dtolnay** [comment]
Minimal repro minimized from `async_trait` crate's test suite:

```rust
pub struct Struct;

pub trait Trait {}

impl Trait for Struct {}

pub async fn fail() -> &'static dyn Trait {
    return &Struct;
}
```

```console
$ cargo +nightly-2022-07-01 clippy
    Checking repro v0.0.0
warning: unneeded `return` statement
 --> src/main.rs:8:5
  |
8 |     return &Struct;
  |     ^^^^^^^^^^^^^^^ help: remove `return`: `&Struct`
  |
  = note: `#[warn(clippy::needless_return)]` on by default
  = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#needless_return

warning: `repro` (bin "repro") generated 1 warning
    Finished dev [unoptimized + debuginfo] target(s) in 0.30s
```

```console
$ cargo +nightly-2022-07-02 clippy
    Checking repro v0.0.0
warning: unneeded `return` statement
 --> src/main.rs:8:5
  |
8 |     return &Struct;
  |     ^^^^^^^^^^^^^^^ help: remove `return`: `&Struct`
  |
  = note: `#[warn(clippy::needless_return)]` on by default
  = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#needless_return

error: internal compiler error: compiler/rustc_typeck/src/collect.rs:1896:13: to get the signature of a closure, use `substs.as_closure().sig()` not `fn_sig()`

thread 'rustc' panicked at 'Box<dyn Any>', /rustc/46b8c23f3eb5e4d0e0aa27eb3f20d5b8fc3ed51f/compiler/rustc_errors/src/lib.rs:1391:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust-clippy/issues/new

note: Clippy version: clippy 0.1.64 (46b8c23 2022-07-01)

query stack during panic:
#0 [fn_sig] computing function signature of `fail::{closure#0}`
#1 [analysis] running analysis passes on this crate
end of query stack
warning: `repro` (bin "repro") generated 1 warning
error: could not compile `repro`; 1 warning emitted
```

**Comment by poliorcetics** [comment]
I saw it again recently:

```
error: internal compiler error: compiler/rustc_typeck/src/collect.rs:1896:13: to get the signature of a closure, use `substs.as_closure().sig()` not `fn_sig()`
thread 'rustc' panicked at 'Box<dyn Any>', /rustc/7665c3543079ebc3710b676d0fd6951bedfd4b29/compiler/rustc_errors/src/lib.rs:1391:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
note: the compiler unexpectedly panicked. this is a bug.
note: we would appreciate a bug report: https://github.com/rust-lang/rust-clippy/issues/new
note: Clippy version: clippy 0.1.64 (7665c35 2022-07-06)
query stack during panic:
#0 [fn_sig] computing function signature of `sys::windows::hlprotect::connect_to_driver::{closure#0}`
#1 [analysis] running analysis passes on this crate
end of query stack
```
