### ISSUE TITLE
thread 'rustc' panicked at 'assertion failed: `(left == right)`

### ISSUE THREAD

**Issue by azzamsa** [rust-lang/rust-clippy#9168]
```
✗ cargo clippy
    Checking cli v0.1.0 (/home/user/playground/rust-cli)
thread 'rustc' panicked at 'assertion failed: `(left == right)`
  left: `7828999432193921317874746873709055`,
 right: `1002111927320821928687967599834759150`', compiler/rustc_query_impl/src/on_disk_cache.rs:540:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust-clippy/issues/new

note: Clippy version: clippy 0.1.62 (a8314ef 2022-06-27)

query stack during panic:
end of query stack
error: could not compile `cli`
```

```rust
✗ RUST_BACKTRACE=1 cargo clippy
    Checking cli v0.1.0 (/home/user/playground/rust-cli)
thread 'rustc' panicked at 'assertion failed: `(left == right)`
  left: `7828999432193921317874746873709055`,
 right: `1002111927320821928687967599834759150`', compiler/rustc_query_impl/src/on_disk_cache.rs:540:5
stack backtrace:
   0: rust_begin_unwind
             at /rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library/std/src/panicking.rs:584:5
   1: core::panicking::panic_fmt
             at /rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library/core/src/panicking.rs:142:14
   2: core::panicking::assert_failed_inner
   3: core::panicking::assert_failed::<u128, u128>
   4: <rustc_query_impl::on_disk_cache::OnDiskCache as rustc_middle::ty::context::OnDiskCache>::new
   5: rustc_incremental::persist::load::load_query_result_cache::<rustc_query_impl::on_disk_cache::OnDiskCache>
   6: rustc_interface::passes::create_global_ctxt
   7: <rustc_interface::queries::Queries>::global_ctxt
   8: <rustc_interface::interface::Compiler>::enter::<rustc_driver::run_compiler::{closure#1}::{closure#2}, core::result::Result<core::option::Option<rustc_interface::queries::Linker>, rustc_errors::ErrorGuaranteed>>
   9: rustc_span::with_source_map::<core::result::Result<(), rustc_errors::ErrorGuaranteed>, rustc_interface::interface::create_compiler_and_run<core::result::Result<(), rustc_errors::ErrorGuaranteed>, rustc_driver::run_compiler::{closure#1}>::{closure#1}>
  10: rustc_interface::interface::create_compiler_and_run::<core::result::Result<(), rustc_errors::ErrorGuaranteed>, rustc_driver::run_compiler::{closure#1}>
  11: <scoped_tls::ScopedKey<rustc_span::SessionGlobals>>::set::<rustc_interface::interface::run_compiler<core::result::Result<(), rustc_errors::ErrorGuaranteed>, rustc_driver::run_compiler::{closure#1}>::{closure#0}, core::result::Result<(), rustc_errors::ErrorGuaranteed>>
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust-clippy/issues/new

note: Clippy version: clippy 0.1.62 (a8314ef 2022-06-27)

query stack during panic:
end of query stack
error: could not compile `cli`
```
```
OS: Debian GNU/Linux 11 (bullseye)
Kernel: Linux 5.10.0-15-amd64
CPU: Intel(R) Core(TM) i7-8565U CPU @ 1.80GHz
Memory: 15893412 kB
```

**Comment by xFrednet** [comment]
This could be an incremental compilation problem. Does the same thing happen if you run `cargo clean` and then `cargo clippy`?

**Comment by azzamsa** [comment]
Yes. solved with `cargo clean`.
