### ISSUE TITLE
ICE: Not an int type

### ISSUE THREAD

**Issue by Byter09** [rust-lang/rust-clippy#9853]
### Summary

Hello!

I was unsure whether to leave this under #9625 or make a new issue, but given that this is a new version and the other one also has no labels, I'm creating this new issue.

Basically, we were in the process of upgrading our Rust version to 1.65.0 and we have a very strict clippy, so now the process of fixing lints has started. Some time into fixing and annotating, clippy started to panic. I have no information on what changed, but I didn't really mind as it still gave me lints to fix. I've now reached the end of all lints and it still produces the below panic.

Given that this is a proprietary project, I sadly can not provide any code. If I knew which specific area started to cause this, I'd try to make a minimal example, but I can't really tell when this started happening as I was simply working along the long list of lints to fix.

If it helps, our upgrade went from 1.61.0 to 1.65.0.

### Version

```text
rustc 1.65.0 (897e37553 2022-11-02)
binary: rustc
commit-hash: 897e37553bba8b42751c67658967889d11ecd120
commit-date: 2022-11-02
host: x86_64-unknown-linux-gnu
release: 1.65.0
LLVM version: 15.0.0
```

### Error output

<details><summary>Backtrace</summary>
  <p>

  ```
error: internal compiler error: src/tools/clippy/clippy_utils/src/consts.rs:134:22: Not an int type

thread 'rustc' panicked at 'Box<dyn Any>', /rustc/897e37553bba8b42751c67658967889d11ecd120/compiler/rustc_errors/src/lib.rs:1462:9
stack backtrace:
   0:     0x7fddf0175d40 - std::backtrace_rs::backtrace::libunwind::trace::h32eb3e08e874dd27
                               at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
   1:     0x7fddf0175d40 - std::backtrace_rs::backtrace::trace_unsynchronized::haa3f451d27bc11a5
                               at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x7fddf0175d40 - std::sys_common::backtrace::_print_fmt::h5b94a01bb4289bb5
                               at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/std/src/sys_common/backtrace.rs:66:5
   3:     0x7fddf0175d40 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::hb070b7fa7e3175df
                               at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/std/src/sys_common/backtrace.rs:45:22
   4:     0x7fddf01d0bfe - core::fmt::write::hd5207aebbb9a86e9
                               at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/core/src/fmt/mod.rs:1202:17
   5:     0x7fddf0166935 - std::io::Write::write_fmt::h3bd699bbd129ab8a
                               at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/std/src/io/mod.rs:1679:15
   6:     0x7fddf01789f3 - std::sys_common::backtrace::_print::h7a21be552fdf58da
                               at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/std/src/sys_common/backtrace.rs:48:5
   7:     0x7fddf01789f3 - std::sys_common::backtrace::print::ha85c41fe4dd80b13
                               at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/std/src/sys_common/backtrace.rs:35:9
   8:     0x7fddf01789f3 - std::panicking::default_hook::{{closure}}::h04cca40023d0eeca
                               at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/std/src/panicking.rs:295:22
   9:     0x7fddf01786df - std::panicking::default_hook::haa3ca8c310ed5402
                               at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/std/src/panicking.rs:314:9
  10:     0x56103f4718af - clippy_driver[8edfe2ebdb33510b]::ICE_HOOK::{closure#0}::{closure#0}
  11:     0x7fddf017922d - std::panicking::rust_panic_with_hook::h7b190ce1a948faac
                               at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/std/src/panicking.rs:702:17
  12:     0x7fddefb24e51 - std[71cb4861428b0c25]::panicking::begin_panic::<rustc_errors[f77a66b68db622d5]::ExplicitBug>::{closure#0}
  13:     0x7fddefb22966 - std[71cb4861428b0c25]::sys_common::backtrace::__rust_end_short_backtrace::<std[71cb4861428b0c25]::panicking::begin_panic<rustc_errors[f77a66b68db622d5]::ExplicitBug>::{closure#0}, !>
  14:     0x7fddefb7c316 - std[71cb4861428b0c25]::panicking::begin_panic::<rustc_errors[f77a66b68db622d5]::ExplicitBug>
  15:     0x7fddefb1f5f6 - std[71cb4861428b0c25]::panic::panic_any::<rustc_errors[f77a66b68db622d5]::ExplicitBug>
  16:     0x7fddefb1e1dd - <rustc_errors[f77a66b68db622d5]::HandlerInner>::bug::<&alloc[188ed69dc0d14b4b]::string::String>
  17:     0x7fddefb1dc10 - <rustc_errors[f77a66b68db622d5]::Handler>::bug::<&alloc[188ed69dc0d14b4b]::string::String>
  18:     0x7fddefbda7ed - rustc_middle[a9ca1c3f9fd197cd]::ty::context::tls::with_context_opt::<rustc_middle[a9ca1c3f9fd197cd]::ty::context::tls::with_opt<rustc_middle[a9ca1c3f9fd197cd]::util::bug::opt_span_bug_fmt<rustc_span[8f00505efff112e2]::span_encoding::Span>::{closure#0}, ()>::{closure#0}, ()>
  19:     0x7fddefbddc86 - rustc_middle[a9ca1c3f9fd197cd]::util::bug::opt_span_bug_fmt::<rustc_span[8f00505efff112e2]::span_encoding::Span>
  20:     0x7fdded57ba83 - rustc_middle[a9ca1c3f9fd197cd]::util::bug::bug_fmt
  21:     0x56103f8a15b1 - <clippy_utils[6f190657543f79d8]::consts::Constant>::partial_cmp
  22:     0x56103f77b851 - clippy_lints[641d7bf63abf0cc3]::ranges::check_possible_range_contains
  23:     0x56103f77b116 - <clippy_lints[641d7bf63abf0cc3]::ranges::Ranges as rustc_lint[dab68e85e8b6d341]::passes::LateLintPass>::check_expr
  24:     0x7fddef968954 - <rustc_lint[dab68e85e8b6d341]::early::EarlyLintPassObjects as rustc_lint[dab68e85e8b6d341]::passes::EarlyLintPass>::check_generic_arg
  25:     0x7fddeec62643 - <rustc_lint[dab68e85e8b6d341]::late::LateContextAndPass<rustc_lint[dab68e85e8b6d341]::late::LateLintPassObjects> as rustc_hir[f29014e7b3f8eb6c]::intravisit::Visitor>::visit_expr
  26:     0x7fddeec62adc - <rustc_lint[dab68e85e8b6d341]::late::LateContextAndPass<rustc_lint[dab68e85e8b6d341]::late::LateLintPassObjects> as rustc_hir[f29014e7b3f8eb6c]::intravisit::Visitor>::visit_nested_body
  27:     0x7fddeec62cd9 - <rustc_lint[dab68e85e8b6d341]::late::LateContextAndPass<rustc_lint[dab68e85e8b6d341]::late::LateLintPassObjects> as rustc_hir[f29014e7b3f8eb6c]::intravisit::Visitor>::visit_fn
  28:     0x7fddeec65472 - rustc_hir[f29014e7b3f8eb6c]::intravisit::walk_expr::<rustc_lint[dab68e85e8b6d341]::late::LateContextAndPass<rustc_lint[dab68e85e8b6d341]::late::LateLintPassObjects>>
  29:     0x7fddeec6264e - <rustc_lint[dab68e85e8b6d341]::late::LateContextAndPass<rustc_lint[dab68e85e8b6d341]::late::LateLintPassObjects> as rustc_hir[f29014e7b3f8eb6c]::intravisit::Visitor>::visit_expr
  30:     0x7fddeec65305 - rustc_hir[f29014e7b3f8eb6c]::intravisit::walk_expr::<rustc_lint[dab68e85e8b6d341]::late::LateContextAndPass<rustc_lint[dab68e85e8b6d341]::late::LateLintPassObjects>>
  31:     0x7fddeec6264e - <rustc_lint[dab68e85e8b6d341]::late::LateContextAndPass<rustc_lint[dab68e85e8b6d341]::late::LateLintPassObjects> as rustc_hir[f29014e7b3f8eb6c]::intravisit::Visitor>::visit_expr
  32:     0x7fddeec652e9 - rustc_hir[f29014e7b3f8eb6c]::intravisit::walk_expr::<rustc_lint[dab68e85e8b6d341]::late::LateContextAndPass<rustc_lint[dab68e85e8b6d341]::late::LateLintPassObjects>>
  33:     0x7fddeec6264e - <rustc_lint[dab68e85e8b6d341]::late::LateContextAndPass<rustc_lint[dab68e85e8b6d341]::late::LateLintPassObjects> as rustc_hir[f29014e7b3f8eb6c]::intravisit::Visitor>::visit_expr
  34:     0x7fddeec62adc - <rustc_lint[dab68e85e8b6d341]::late::LateContextAndPass<rustc_lint[dab68e85e8b6d341]::late::LateLintPassObjects> as rustc_hir[f29014e7b3f8eb6c]::intravisit::Visitor>::visit_nested_body
  35:     0x7fddeec62cd9 - <rustc_lint[dab68e85e8b6d341]::late::LateContextAndPass<rustc_lint[dab68e85e8b6d341]::late::LateLintPassObjects> as rustc_hir[f29014e7b3f8eb6c]::intravisit::Visitor>::visit_fn
  36:     0x7fddeec65472 - rustc_hir[f29014e7b3f8eb6c]::intravisit::walk_expr::<rustc_lint[dab68e85e8b6d341]::late::LateContextAndPass<rustc_lint[dab68e85e8b6d341]::late::LateLintPassObjects>>
  37:     0x7fddeec6264e - <rustc_lint[dab68e85e8b6d341]::late::LateContextAndPass<rustc_lint[dab68e85e8b6d341]::late::LateLintPassObjects> as rustc_hir[f29014e7b3f8eb6c]::intravisit::Visitor>::visit_expr
  38:     0x7fddeec65305 - rustc_hir[f29014e7b3f8eb6c]::intravisit::walk_expr::<rustc_lint[dab68e85e8b6d341]::late::LateContextAndPass<rustc_lint[dab68e85e8b6d341]::late::LateLintPassObjects>>
  39:     0x7fddeec6264e - <rustc_lint[dab68e85e8b6d341]::late::LateContextAndPass<rustc_lint[dab68e85e8b6d341]::late::LateLintPassObjects> as rustc_hir[f29014e7b3f8eb6c]::intravisit::Visitor>::visit_expr
  40:     0x7fddeec62adc - <rustc_lint[dab68e85e8b6d341]::late::LateContextAndPass<rustc_lint[dab68e85e8b6d341]::late::LateLintPassObjects> as rustc_hir[f29014e7b3f8eb6c]::intravisit::Visitor>::visit_nested_body
  41:     0x7fddeec62cd9 - <rustc_lint[dab68e85e8b6d341]::late::LateContextAndPass<rustc_lint[dab68e85e8b6d341]::late::LateLintPassObjects> as rustc_hir[f29014e7b3f8eb6c]::intravisit::Visitor>::visit_fn
  42:     0x7fddeec65472 - rustc_hir[f29014e7b3f8eb6c]::intravisit::walk_expr::<rustc_lint[dab68e85e8b6d341]::late::LateContextAndPass<rustc_lint[dab68e85e8b6d341]::late::LateLintPassObjects>>
  43:     0x7fddeec6264e - <rustc_lint[dab68e85e8b6d341]::late::LateContextAndPass<rustc_lint[dab68e85e8b6d341]::late::LateLintPassObjects> as rustc_hir[f29014e7b3f8eb6c]::intravisit::Visitor>::visit_expr
  44:     0x7fddeec65305 - rustc_hir[f29014e7b3f8eb6c]::intravisit::walk_expr::<rustc_lint[dab68e85e8b6d341]::late::LateContextAndPass<rustc_lint[dab68e85e8b6d341]::late::LateLintPassObjects>>
  45:     0x7fddeec6264e - <rustc_lint[dab68e85e8b6d341]::late::LateContextAndPass<rustc_lint[dab68e85e8b6d341]::late::LateLintPassObjects> as rustc_hir[f29014e7b3f8eb6c]::intravisit::Visitor>::visit_expr
  46:     0x7fddeec62799 - <rustc_lint[dab68e85e8b6d341]::late::LateContextAndPass<rustc_lint[dab68e85e8b6d341]::late::LateLintPassObjects> as rustc_hir[f29014e7b3f8eb6c]::intravisit::Visitor>::visit_block
  47:     0x7fddeec6264e - <rustc_lint[dab68e85e8b6d341]::late::LateContextAndPass<rustc_lint[dab68e85e8b6d341]::late::LateLintPassObjects> as rustc_hir[f29014e7b3f8eb6c]::intravisit::Visitor>::visit_expr
  48:     0x7fddeec62adc - <rustc_lint[dab68e85e8b6d341]::late::LateContextAndPass<rustc_lint[dab68e85e8b6d341]::late::LateLintPassObjects> as rustc_hir[f29014e7b3f8eb6c]::intravisit::Visitor>::visit_nested_body
  49:     0x7fddeec62cd9 - <rustc_lint[dab68e85e8b6d341]::late::LateContextAndPass<rustc_lint[dab68e85e8b6d341]::late::LateLintPassObjects> as rustc_hir[f29014e7b3f8eb6c]::intravisit::Visitor>::visit_fn
  50:     0x7fddeec6562d - rustc_hir[f29014e7b3f8eb6c]::intravisit::walk_item::<rustc_lint[dab68e85e8b6d341]::late::LateContextAndPass<rustc_lint[dab68e85e8b6d341]::late::LateLintPassObjects>>
  51:     0x7fddeec635de - <rustc_lint[dab68e85e8b6d341]::late::LateContextAndPass<rustc_lint[dab68e85e8b6d341]::late::LateLintPassObjects> as rustc_hir[f29014e7b3f8eb6c]::intravisit::Visitor>::visit_nested_item
  52:     0x7fddeec63f8a - rustc_hir[f29014e7b3f8eb6c]::intravisit::walk_block::<rustc_lint[dab68e85e8b6d341]::late::LateContextAndPass<rustc_lint[dab68e85e8b6d341]::late::LateLintPassObjects>>
  53:     0x7fddeec62799 - <rustc_lint[dab68e85e8b6d341]::late::LateContextAndPass<rustc_lint[dab68e85e8b6d341]::late::LateLintPassObjects> as rustc_hir[f29014e7b3f8eb6c]::intravisit::Visitor>::visit_block
  54:     0x7fddeec6264e - <rustc_lint[dab68e85e8b6d341]::late::LateContextAndPass<rustc_lint[dab68e85e8b6d341]::late::LateLintPassObjects> as rustc_hir[f29014e7b3f8eb6c]::intravisit::Visitor>::visit_expr
  55:     0x7fddeec62adc - <rustc_lint[dab68e85e8b6d341]::late::LateContextAndPass<rustc_lint[dab68e85e8b6d341]::late::LateLintPassObjects> as rustc_hir[f29014e7b3f8eb6c]::intravisit::Visitor>::visit_nested_body
  56:     0x7fddeec62cd9 - <rustc_lint[dab68e85e8b6d341]::late::LateContextAndPass<rustc_lint[dab68e85e8b6d341]::late::LateLintPassObjects> as rustc_hir[f29014e7b3f8eb6c]::intravisit::Visitor>::visit_fn
  57:     0x7fddeec6562d - rustc_hir[f29014e7b3f8eb6c]::intravisit::walk_item::<rustc_lint[dab68e85e8b6d341]::late::LateContextAndPass<rustc_lint[dab68e85e8b6d341]::late::LateLintPassObjects>>
  58:     0x7fddeec635de - <rustc_lint[dab68e85e8b6d341]::late::LateContextAndPass<rustc_lint[dab68e85e8b6d341]::late::LateLintPassObjects> as rustc_hir[f29014e7b3f8eb6c]::intravisit::Visitor>::visit_nested_item
  59:     0x7fddeec64f27 - rustc_hir[f29014e7b3f8eb6c]::intravisit::walk_mod::<rustc_lint[dab68e85e8b6d341]::late::LateContextAndPass<rustc_lint[dab68e85e8b6d341]::late::LateLintPassObjects>>
  60:     0x7fddeec635de - <rustc_lint[dab68e85e8b6d341]::late::LateContextAndPass<rustc_lint[dab68e85e8b6d341]::late::LateLintPassObjects> as rustc_hir[f29014e7b3f8eb6c]::intravisit::Visitor>::visit_nested_item
  61:     0x7fddeec64f27 - rustc_hir[f29014e7b3f8eb6c]::intravisit::walk_mod::<rustc_lint[dab68e85e8b6d341]::late::LateContextAndPass<rustc_lint[dab68e85e8b6d341]::late::LateLintPassObjects>>
  62:     0x7fddeec635de - <rustc_lint[dab68e85e8b6d341]::late::LateContextAndPass<rustc_lint[dab68e85e8b6d341]::late::LateLintPassObjects> as rustc_hir[f29014e7b3f8eb6c]::intravisit::Visitor>::visit_nested_item
  63:     0x7fddeec64f27 - rustc_hir[f29014e7b3f8eb6c]::intravisit::walk_mod::<rustc_lint[dab68e85e8b6d341]::late::LateContextAndPass<rustc_lint[dab68e85e8b6d341]::late::LateLintPassObjects>>
  64:     0x7fddeec62563 - rustc_lint[dab68e85e8b6d341]::late::late_lint_pass_crate::<rustc_lint[dab68e85e8b6d341]::late::LateLintPassObjects>
  65:     0x7fddedf17511 - rustc_lint[dab68e85e8b6d341]::late::late_lint_crate::<rustc_lint[dab68e85e8b6d341]::BuiltinCombinedLateLintPass>
  66:     0x7fddedf15ad6 - <rustc_session[c5946fac61f8bc34]::session::Session>::time::<(), rustc_lint[dab68e85e8b6d341]::late::check_crate<rustc_lint[dab68e85e8b6d341]::BuiltinCombinedLateLintPass, rustc_interface[3182dd864eff9d7d]::passes::analysis::{closure#5}::{closure#1}::{closure#2}::{closure#0}::{closure#0}>::{closure#0}::{closure#0}>
  67:     0x7fddedf159d9 - <rustc_session[c5946fac61f8bc34]::session::Session>::time::<(), rustc_interface[3182dd864eff9d7d]::passes::analysis::{closure#5}::{closure#1}::{closure#2}::{closure#0}>
  68:     0x7fddedf157cf - <core[8c92e53db3fc2eaa]::panic::unwind_safe::AssertUnwindSafe<rustc_interface[3182dd864eff9d7d]::passes::analysis::{closure#5}::{closure#1}> as core[8c92e53db3fc2eaa]::ops::function::FnOnce<()>>::call_once
  69:     0x7fddedf14d9a - <rustc_session[c5946fac61f8bc34]::session::Session>::time::<(), rustc_interface[3182dd864eff9d7d]::passes::analysis::{closure#5}>
  70:     0x7fddedf10cbc - rustc_interface[3182dd864eff9d7d]::passes::analysis
  71:     0x7fddee96f382 - <rustc_query_system[860ed7b39cdfb46b]::dep_graph::graph::DepGraph<rustc_middle[a9ca1c3f9fd197cd]::dep_graph::dep_node::DepKind>>::with_task::<rustc_middle[a9ca1c3f9fd197cd]::ty::context::TyCtxt, (), core[8c92e53db3fc2eaa]::result::Result<(), rustc_errors[f77a66b68db622d5]::ErrorGuaranteed>>
  72:     0x7fddee96ea4a - rustc_query_system[860ed7b39cdfb46b]::query::plumbing::try_execute_query::<rustc_query_impl[d6191eea714bd250]::plumbing::QueryCtxt, rustc_query_system[860ed7b39cdfb46b]::query::caches::DefaultCache<(), core[8c92e53db3fc2eaa]::result::Result<(), rustc_errors[f77a66b68db622d5]::ErrorGuaranteed>>>
  73:     0x7fddee96e517 - rustc_query_system[860ed7b39cdfb46b]::query::plumbing::get_query::<rustc_query_impl[d6191eea714bd250]::queries::analysis, rustc_query_impl[d6191eea714bd250]::plumbing::QueryCtxt>
  74:     0x7fddeda5a897 - <rustc_interface[3182dd864eff9d7d]::passes::QueryContext>::enter::<rustc_driver[cfb34b1539811fe8]::run_compiler::{closure#1}::{closure#2}::{closure#3}, core[8c92e53db3fc2eaa]::result::Result<(), rustc_errors[f77a66b68db622d5]::ErrorGuaranteed>>
  75:     0x7fddeda4e28c - rustc_interface[3182dd864eff9d7d]::interface::create_compiler_and_run::<core[8c92e53db3fc2eaa]::result::Result<(), rustc_errors[f77a66b68db622d5]::ErrorGuaranteed>, rustc_driver[cfb34b1539811fe8]::run_compiler::{closure#1}>
  76:     0x7fddeda4cac1 - <scoped_tls[e395fa6e23b19669]::ScopedKey<rustc_span[8f00505efff112e2]::SessionGlobals>>::set::<rustc_interface[3182dd864eff9d7d]::interface::run_compiler<core[8c92e53db3fc2eaa]::result::Result<(), rustc_errors[f77a66b68db622d5]::ErrorGuaranteed>, rustc_driver[cfb34b1539811fe8]::run_compiler::{closure#1}>::{closure#0}, core[8c92e53db3fc2eaa]::result::Result<(), rustc_errors[f77a66b68db622d5]::ErrorGuaranteed>>
  77:     0x7fddeda4c7af - std[71cb4861428b0c25]::sys_common::backtrace::__rust_begin_short_backtrace::<rustc_interface[3182dd864eff9d7d]::util::run_in_thread_pool_with_globals<rustc_interface[3182dd864eff9d7d]::interface::run_compiler<core[8c92e53db3fc2eaa]::result::Result<(), rustc_errors[f77a66b68db622d5]::ErrorGuaranteed>, rustc_driver[cfb34b1539811fe8]::run_compiler::{closure#1}>::{closure#0}, core[8c92e53db3fc2eaa]::result::Result<(), rustc_errors[f77a66b68db622d5]::ErrorGuaranteed>>::{closure#0}, core[8c92e53db3fc2eaa]::result::Result<(), rustc_errors[f77a66b68db622d5]::ErrorGuaranteed>>
  78:     0x7fddeea01d70 - <<std[71cb4861428b0c25]::thread::Builder>::spawn_unchecked_<rustc_interface[3182dd864eff9d7d]::util::run_in_thread_pool_with_globals<rustc_interface[3182dd864eff9d7d]::interface::run_compiler<core[8c92e53db3fc2eaa]::result::Result<(), rustc_errors[f77a66b68db622d5]::ErrorGuaranteed>, rustc_driver[cfb34b1539811fe8]::run_compiler::{closure#1}>::{closure#0}, core[8c92e53db3fc2eaa]::result::Result<(), rustc_errors[f77a66b68db622d5]::ErrorGuaranteed>>::{closure#0}, core[8c92e53db3fc2eaa]::result::Result<(), rustc_errors[f77a66b68db622d5]::ErrorGuaranteed>>::{closure#1} as core[8c92e53db3fc2eaa]::ops::function::FnOnce<()>>::call_once::{shim:vtable#0}
  79:     0x7fddf0183003 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h49f797984e2121bf
                               at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/alloc/src/boxed.rs:1940:9
  80:     0x7fddf0183003 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::hfa4f3d0ee6440e0b
                               at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/alloc/src/boxed.rs:1940:9
  81:     0x7fddf0183003 - std::sys::unix::thread::Thread::new::thread_start::h62ca48b42d48a8fc
                               at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/std/src/sys/unix/thread.rs:108:17
  82:     0x7fddec1b78fd - <unknown>
  83:     0x7fddec239a60 - <unknown>
  84:                0x0 - <unknown>

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust-clippy/issues/new

note: Clippy version: clippy 0.1.65 (897e375 2022-11-02)

query stack during panic:
#0 [analysis] running analysis passes on this crate
end of query stack
  ```

  </p>
</details>

**Comment by Alexendoo** [comment]
Could you give nightly a go? It may have been fixed by #9627

**Comment by Byter09** [comment]
It's 23:03. I gave it a quick shot and it gives me a lint at a dependency (that is in the same workspace) way earlier, so I can't tell if it would still panic at the same spot like the report. It's a good plan though. I'll simply finish all linting errors on Thursday (tomorrow is a holiday), and report back.

Also I didn't even consider that that PR would fix this, given that I thought that ICE's get priority and assumed it would be fixed with the next version. So this might just be a useless bug report. Still, thanks for the suggestion though. It gives me a plan on how to finish this on Thursday.

We had over 500 new lints because moving from 1.61.0 to 1.65.0 with a pretty large project and clippy this strict, it's quite the task :D

**Comment by Byter09** [comment]
I have fixed all lints using nightly and can confirm, that the ICE is gone. I guess I should close this issue then? I'm still a bit perplexed, that the fix didn't land in the release :thinking:

**Comment by Byter09** [comment]
Hm. Minor problem. Our CI would now panic using clippy on 1.65.0. Is there any hot fix?
